### PR TITLE
[waybar] Capability to have user modules by adding  "#tag"

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

Ability https://github.com/prasanthrangan/hyprdots/pull/1337  to add hyprland/workspaces#kanji 

image

image

* atomic change, I hope this does not borke ,

### CODE REVIEW

**Comment by abenezerw** [comment]
Ohhh yes smart implementation, the kanji workspaces work so yeah this works.

**Review by Enigma1309 — APPROVED** [review]

**Comment by kRHYME7** [comment]
Needs more test please.

**Comment by kRHYME7** [comment]
@rubiin  Can you help me merge this one? Open a new PR then I'll merge

**Comment by rubiin** [comment]
ok

**Pull request closed without merging**
