### PR TITLE
feat: add cava module on waybar

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

closes https://github.com/prasanthrangan/hyprdots/issues/1861
Code are imported from Jakolit repo

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots
image

### CODE REVIEW

**Comment by zeerayne** [comment]
I'm not sure, but looks like waybar have [native `cava` module](https://github.com/Alexays/Waybar/wiki/Module:-Cava) and maybe it's a good idea to try it instead of custom one

**Comment by rubiin** [comment]
didnt realize there was a native . Will compare the cpu usage and update the pr

**Comment by rubiin** [comment]
Couldnt make the native work lol

**Comment by zeerayne** [comment]
I assume it requires `libcava` to be installed, it is not obvious from the doc

**Comment by rubiin** [comment]
> I assume it requires `libcava` to be installed, it is not obvious from the doc

yeah . thats another dep so I am skeptical we will add that . But even after libcava i couldnt make it work

**Comment by rubiin** [comment]
Also by default waybar is built without cava, so I guess the one they have on their wiki is a pain in the ass with extra module and manual compilation :D

https://github.com/Alexays/Waybar/issues/2490#issuecomment-1712792259

**Comment by zeerayne** [comment]
I didn't know that, so no native cava module is available I guess

**Comment by zeerayne** [comment]
p.s. in AUR `waybar-cava` package is available, but come on, change the whole package for one module? Sounds like and overkill

**Comment by rubiin** [comment]
> p.s. in AUR `waybar-cava` package is available, but come on, change the whole package for one module? Sounds like and overkill

yeah true and  I also tried that but its way laggy . The script one seems to be more responsive and took only 5MB

**Comment by kRHYME7** [comment]
TBH, I didn't add the module when it's a separate package. So this should be good, I guess. Let me try to test it.

**Comment by rubiin** [comment]
Yeah the one mentioned on the wiki adds a dep plus manual compilation . So this approach is good as its just a shell script and nothing more

**Comment by kRHYME7** [comment]
current 

image


Adding space will make it blank, which IMO is better than a line 
`bar=" ▁▂▃▄▅▆▇█" `
image

Will merge this now but do you guys have an idea what should be the default behavior if no music is playing? 

should it be 
*  line with a padding? 
*  blank but padding still exist
* make it the same as the system update module that disappears. ( In my use case I want this as I have a small monitor)

**Review by kRHYME7 — APPROVED** [review]

**Comment by rubiin** [comment]
Yeah . I noticed the lines when nothing was playing too. Will take a close look sometime soon

**Comment by kRHYME7** [comment]
So what should be the default behavior BTW? 


Also, here's the usage. This script had more rooms for improvements
image
image

**Comment by rubiin** [comment]
default would be to hide. The _____ looks ugly IMO

**Comment by kRHYME7** [comment]
what happens when you run ` waybar_cava.sh ` ?

**Comment by Hareekshith** [comment]
Bro, can I change 40 to 28? The waybar is too big

**Comment by rubiin** [comment]
yeah . Thats totally upto you. This size works on my screen but may or may not work for you. You could set that to the size that works for you

**Pull request merged**
