### PR TITLE
fix: Reformated date to save space for another modules

### PR DESCRIPTION
**Pull request by RAprogramm**
231119_12h12m19s_screenshot

### CODE REVIEW

**Comment by prasanthrangan** [comment]
Hi, it has conflicts...
could you please pull the latest changes and recommit?

**Comment by RAprogramm** [comment]
> Hi, it has conflicts... could you please pull the latest changes and recommit?

done!

**Review by prasanthrangan — APPROVED** [review]
great, thanks!

**Comment by cassiofb-dev** [comment]
Hi, do I need to config some font? I have jet brains font but even so it does not render for me:
image

**Comment by RAprogramm** [comment]
Fonts should be a Nerd Font. You can download it or patch your own font. Does it helps you?

**Comment by RAprogramm** [comment]
> Hi, do I need to config some font? I have jet brains font but even so it does not render for me:
> image
> 

Fonts should be a Nerd Font. You can download it or patch your own font. Does it helps you?

**Comment by cassiofb-dev** [comment]
Yeah, this was the jet brains I was talking about (it's a nerd one):
image

---

I have this font installed on my new machine too but because of some reason does not render, I'll try another nerd font later to see what happens.

**Comment by cassiofb-dev** [comment]
I searched a bit and it seems an issue with nerd font itself: https://github.com/ryanoasis/nerd-fonts/issues/1190

image

---

Next I'll try using https://github.com/loichyan/nerdfix

**Comment by RAprogramm** [comment]
> I searched a bit and it seems an issue with nerd font itself: https://github.com/ryanoasis/nerd-fonts/issues/1190
> 
> image
> 
> ---
> 
> Next I'll try using https://github.com/loichyan/nerdfix

Have you already tried reinstalling fonts?
Was it fresh installed archlinux distro?

**Comment by cassiofb-dev** [comment]
@RAprogramm sorry for the delay, got a busy week. The issue is the default font "JetBrainsMono Nerd Font", when I installed another nerd font it worked for me.

Yeah, I also tried reinstalling, I ran the setup from a minimal install arch.

**Pull request merged**
