### PR TITLE
feat: include symlinks when finding files in scripts

### PR DESCRIPTION
**Pull request by richen604**
# Pull Request

## Description

includes symlinks in find commands scripts to provide support for nixos & home-manager systems. 

the only potential risk i can think of would be symlinks causing circular dependencies. however this should be non existent considering the scripts changed reference files pulled from git repositories ie themes. only home-manager and nixos operating systems would have symlinks for files related. decided not to make it a flag, but can if requested.

motivation for this change is that i'm currently working on a home-manager implementation of hyprdots at [hyprdots-nix](https://github.com/richen604/hyprdots-nix)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by kRHYME7 — APPROVED** [review]
Cool. As of now this repo copies files to target files/directories. Therefore symlinks should still be fine.

I will test it further though..

**Comment by kRHYME7** [comment]
@rubiin @abenezerw

**Comment by abenezerw** [comment]
> @rubiin @abenezerw

I tried looking up what these are and don’t really understand it so I can’t test

**Comment by kRHYME7** [comment]
@richen604  do ` find -L `  returns the  realpath? Or the softlink filename ? This might break if `find`  returns  the realtpath

**Comment by rubiin** [comment]
This might break things IMO . We have to test all cases to be sure before merge

**Comment by richen604** [comment]
> @richen604 do `find -L` returns the realpath? Or the softlink filename ? This might break if `find` returns the realtpath




would need pipe to `readlink -f <file>` to get a realpath, this will return file regardless if its a symlink or not

for file references, we can test this for example in [global_control.sh](https://github.com/prasanthrangan/hyprdots/pull/1850/files#diff-1824fe6ad5778299510feeb9fe7d38c39c8d509e212f7c46eb151895f358b514) 

```bash
hashMap=$(find -L "${wallSource}" -type f \( -iname "*.gif" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec "${hashMech}" {} + | sort -k2)
```

navigate to wallpapers or `git clone -b Catppuccin-Mocha git@github.com:prasanthrangan/hyde-themes.git && cd Configs/.config/hyde/themes/Catppuccin\ Mocha/wallpapers`

use find with both `-L` and without

```bash
$ find . -type f \( -iname "*.gif" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec "sha1sum" {} + | sort -k2

a96dac249950cef9e8d9b3331b104b5cbebf17d8  ./1 rain_world.png
53a79e21e526c7f809747304679db1e23fd35743  ./2 rain_world.png
8cb5616b5ab98323751abe8ecf44bf590c89ab75  ./3 rain_world.png
<etc>
$ find -L . -type f \( -iname "*.gif" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec "sha1sum" {} + | sort -k2
<same output>
```

creating symlinks to these files
```bash
➜  wallpapers_symlinks find . -type f \( -iname "*.gif" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec "sha1sum" {} + | sort -k2
****<no output>****
➜  wallpapers_symlinks find -L . -type f \( -iname "*.gif" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec "sha1sum" {} + | sort -k2
<same output as before>
```

most changes reference files only. I do want to test [restore_lnk.sh](https://github.com/prasanthrangan/hyprdots/pull/1850/files#diff-79310b507b1488dde24a9a15c5d84f50fcf8b72be0fe643b4cce74228f45f4cb) as it grabs symlinks.

**Comment by richen604** [comment]
> > @rubiin @abenezerw
> 
> I tried looking up what these are and don’t really understand it so I can’t test

in all fairness these changes would only benefit nixos / home-manager and would be entirely understandable if closed

**Comment by rubiin** [comment]
I guess we can merge this on a separate branch

**Comment by kRHYME7** [comment]
this one is fine.

**Comment by richen604** [comment]
feel free to not include this if you want, i run [these edits](https://github.com/richen604/hyprdots-nix/blob/a366b97a393bc8732e6ccd89c5def7e3b877e36f/modules/hyprdots/build.sh#L51) in the derivation I'm building regardless

makes more sense to maintain support there

**Comment by rubiin** [comment]
@richen604 Maybe you can add a Pr to link your repo in the readme here

**Comment by kRHYME7** [comment]
@richen604  We will be maintaining a repo for configs alone and a separate stack for the scripts only wrap by a command line. Will try to do this patch on that repo.

**Comment by rubiin** [comment]
@kRHYME7 any thoughts on moving this repo to the Project Org

**Pull request closed without merging**
