### PR TITLE
Added Much More Features in Clipboard

### PR DESCRIPTION
**Pull request by XBEAST1**
Added Following Features In Clipboard

1.Clear History At Once
2.Delete Specific Clips From History
3.Support For Adding And Managing Favourites

image

You Can Check The Video Here

https://youtu.be/EzqB5o0s_lk

### CODE REVIEW

**Comment by JunaidQrysh** [comment]
I have modified the the code to only show history if any argument is passed
So that I  can use Super+v to show history directly  and Super+Shift+v to show proper menu.

`if [ $# -eq 0 ]; then
	# Show main menu
	main_action=$(echo -e "History\nDelete\nView Favorites\nManage Favorites\nClear History" | rofi -dmenu -theme-str "entry { placeholder: \"Choose action\";}" -theme-str "${r_scale}" -theme-str "${r_override}" -config "${roconf}")
else
	main_action="History"
fi`

**Comment by XBEAST1** [comment]
> I have modified the the code to only show history if any argument is passed So that I can use Super+v to show history directly and Super+Shift+v to show proper menu.
> 
> `if [ $# -eq 0 ]; then # Show main menu main_action=$(echo -e "History\nDelete\nView Favorites\nManage Favorites\nClear History" | rofi -dmenu -theme-str "entry { placeholder: \"Choose action\";}" -theme-str "${r_scale}" -theme-str "${r_override}" -config "${roconf}") else main_action="History" fi`

Well Thats a Really Good Approach Lemme Do Another Commit For This But The Real Question Is If This Gets Merged Into The Main Branch

**Comment by kRHYME7** [comment]
@rubiin  @abenezerw

**Comment by rubiin** [comment]
Looks good, can be merged

**Comment by abenezerw** [comment]
image
LGTM

**Review by abenezerw — APPROVED** [review]
image
LGTM

**Review by kRHYME7 — APPROVED** [review]
Thanks @XBEAST1 Also I will try to add this to the HyDE CLI too! Pretty Cool

**Comment by XBEAST1** [comment]
> Thanks @XBEAST1 Also I will try to add this to the HyDE CLI too! Pretty Cool

I'm Glad To Hear That You Guys Liked It 💓

**Pull request merged**
