### PR TITLE
Sourced Hyprland

### PR DESCRIPTION
**Pull request by dieBakterie**
# Pull Request

## Type of change

- [x] **New feature** (non-breaking change which adds functionality)
- [x] **Other** (provide details below)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Important

Empty lines cause problems so i commented them out to prevent breakage or issues.

### CODE REVIEW

**Comment by Skerse** [comment]
> Empty lines cause problems so i commented them out to prevent breakage or issues.

How so? I've literally never had an issue or can think of an issue.

**Comment by dieBakterie** [comment]
You can Look at my issue on Hyprland don't know why, but it's there.

**Comment by kRHYME7** [comment]
I don't approve this. It's too fragmented. And could contribute to more confusion.  Any changes on launch will break the dots and hard to debug.  

Adding exec in the ./userprefs.conf is enough because Hyprland will first read it all then render the compositor. (Tried making the splash screen and I can render it first even if I added the splashscreen script at the bottom.) 


Everything I said above is just my opinion.  Will wait for Tittu's approval on this. Thanks!

As for your issue, maybe you're looping your configs? 

 output for this ? 

` grep "source" ~/.config/hypr/* `

**Comment by dieBakterie** [comment]
`/home/bakterie/.config/hypr/hypridle.conf:# source = ~/.config/hypridle/*
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/environments.conf # Set your environment variables here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/animations.conf # Set your preferred animations in here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/keybindings.conf # Set your preferred keybindings in here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/windowrules.conf # Set your preferred rules for windows(blur, opaque...) in here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/monitors.conf # Set your Monitor confoiguration here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/launch.conf # Autostarted Applications are listed here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/workspaces.conf # Set and define your own Workspaces here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/input.conf # Set your Input Devices here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/layouts.conf # Set your Layouts here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/misc.conf # For miscellaneous things(misc section)
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/vm.conf # Submap for VM's
/home/bakterie/.config/hypr/hyprland.conf:# source = ~/.config/hypr/userprefs.conf # Set your preferences in here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/scratchpads.conf # Configure your scratchpads in here
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/themes/common.conf # Shared theme settings
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/themes/theme.conf # Theme specific settings
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/themes/colors.conf # Wallbash color override
/home/bakterie/.config/hypr/hyprland.conf:source = ~/.config/hypr/nvidia.conf # Auto sourced vars for Nvidia
grep: /home/bakterie/.config/hypr/themes: Ist ein Verzeichnis` that's the output

**Pull request closed without merging**
