### PR TITLE
Add conditional flow in some installation scripts

### PR DESCRIPTION
**Pull request by Gigas002**
## Description

Implementation of conditional flow for:

- `install.sh`: nvidia drivers
- `install.sh`: aur helper
- `install.sh`: install shell
- `install.sh`: `install_pkg.lst` packages installaton
- `install_pre.sh`: GRUB configuration
- `install_pre.sh`: systemd-boot configuration
- `install_pre.sh`: pacman configuration
- `install_pst.sh`: sddm configuration
- `install_pst.sh`: dolphin configuration
- `install_pst.sh`: change shell configuration
- `install_pst.sh`: install flatpak

## Type of change

- [x] **New feature** (non-breaking change which adds functionality)
- [x] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kRHYME7** [comment]
@Gigas002  Maybe it is better to collaborate with https://github.com/jpx40/hyperdots_installer

Here's the thread
 https://github.com/prasanthrangan/hyprdots/pull/1179

**Comment by Gigas002** [comment]
Oh, no problem, I'll take a look out there then :+1:

**Comment by jpx40** [comment]
> Oh, no problem, I'll take a look out there then :+1: 

If you have interest you can help me. It was a little bit selfish of me to use rust. Maybe it's overkill . But I saw u know rust. It isn't ready yet but might finish it this weekend. Basically i use rustyline to provide a shell menu where the user can choose software. I have to find a way to make it scriptaple so software isn't hard coded thought of python or simple toml configs.

**Comment by Gigas002** [comment]
Hey, @jpx40 ! I'm a bit busy lately, so I can't promise I'll contribute soon, but since I am interested in such project I'll try to help you when I'll have a chance

**Comment by jpx40** [comment]
@Gigas002 hey, currently my programm is broken because of an stupid matching bug. can u help solve it?
i really don't where the error is

**Comment by dieBakterie** [comment]
If this pullrequest is outdated could you close it?

**Comment by Gigas002** [comment]
I may be incorrect, but the mentioned `hyprdots-installer` project in it's current state looks more like an addition to a current scripts, rather than replacement for me now. That would mean, that calling existing scripts is still required for it.
That being said, even if it's replacement and the scripts from this repos will be removed, I don't see the downside in implementing this feature for scripts too. I understand that the PR may be incomplete or some changes could be required, but I still think that merging it would benefit, even if it's a short-range benefit. Decision is up to maintainers, though. I won't object if they decide to close this PR.

**Comment by dieBakterie** [comment]
This Project is currently getting bigger so i just wanted to "clean" up things. I never Said this pPR is bad or sth similar i just wanted to know what's the state and if it's outdated that it gets closed. Oh and is it possible to automate this i'm only meaning locally 'cause i'm install IT very often and therefore want to install my Things. So Like an config where you can set to install additional Themes, flatpak, shell(zsh, fish) etc and then the Installer Just asks once for sudo. Or implement this in @jpx40 Installer Projekt?

**Review by dieBakterie — COMMENTED** [review]
Is it possible to just add starfish theme/prompt to the installed Shell without changing it to zsh or fish?

**Comment by Gigas002** [comment]
I think you'll need to edit the `custom_hypr.lst` for that behavior. I don't see the point in forcing shell for tools like `eza`, `lsd` and `starfish` too, these are working in any shell AFAIK. IMO it's better to introduce this fix in a separate PR anyways.

**Comment by prasanthrangan** [comment]
Hi @Gigas002 , thanks for the PR...
But adding user input to the flow will definitely break the process, for example if the user decides to install nvidia-dkms and skip the grub config, then it wont boot to sddm.
If the user decides to skip aur helper then it will fail when it tried to install aur packages...

the install script is not designed to handle user options, just run it and forget about it. I'll look into https://github.com/jpx40/hyperdots_installer to build a proper installer...

**Pull request closed without merging**
