### PR TITLE
Feature: waybar privacy module

### PR DESCRIPTION
**Pull request by zeerayne**
# Pull Request

## Description

This module shows icons in waybar when screen is recorded/shared or microphone is used.
Looks useful for me, especially screen recording, as I'm using `wf-recorder` often.

Please note that I added new variable to `wbarconfgen.sh` named `i_priv`. Thats because if existing `i_task` variable is used for `icon-size` in this module, icons are ridiculously larger than should be.

**p.s. I'm not sure about if it is a good idea or not to add `privacy` module to `config.ctl` by default. If it is not - i'll revert this commit**

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

Only microphone is used
image

Only screen is shared/captured
image

Both screen is shared and microphone is used
image

### CODE REVIEW

**Review by kRHYME7 — COMMENTED** [review]
Just a question. What happens if we remove icon_size for the module. will it fall back to a constant value? or will it respect the Parent bar?

**Comment by zeerayne** [comment]
Without setting `icon_size` it defaults to 20. Have checked myself and this is stated in [doc](https://github.com/Alexays/Waybar/wiki/Module:-Privacy).

**Review by kRHYME7 — APPROVED** [review]
Thanks!

**Comment by se7en-x230** [comment]
Is it wf- specific or why does it not show any icon while recording with wl-screenrecorder?
image

image

**Comment by kRHYME7** [comment]
@se7en-x230  Might be a waybar issue. will try to check it later

**Comment by se7en-x230** [comment]
my config.ctl file is fairly simple

1||top|( hyprland/workspaces hyprland/window ) ( custom/invest )|( clock )|( network pulseaudio ) ( privacy tray battery )  ( mpris ) ( custom/cava )

**Comment by zeerayne** [comment]
I've tested it with `wf-recorder` and `gpu-screen-recorder`, both worked. Maybe diffetent methods of screen recording are used and not all of them are detected by waybar

**Comment by se7en-x230** [comment]
hmm neither of them work for me. I have a constant mic icon that does not change at all.

if I start waybar from the cli I get this error
[2024-09-01 14:57:12.866] [warning] module : Unknown module:

not sure if that realates to 
image

**Comment by kRHYME7** [comment]
I only tested this on this platforms. I merged that PR as It's more likely users will be using obs as screen recorder. Maybe this is a waybar issue on how the module polls/queries the status or the screen recorder themeselves 



| pkg          | audio | video |                                      |
| ------------ | ----- | ----- | ------------------------------------ |
| wl-screenrec | /     |       |image |
| obs          | /     | /     | image |
| wf-recorder  | /     |       |image |
|              |       |       |                                      |


BTW ` wl-screenrec ` works better now in Hyprland.

**Comment by se7en-x230** [comment]
image

custom notification if screenrecorder is running. Not the same but fits my needs

**Pull request merged**
