### PR TITLE
Clipboard (Update cliphist.sh)

### PR DESCRIPTION
**Pull request by kRHYME7**
+ Clipboard follows mouse (Sorry I used Windows Clipboard )
+ Respect monitor scaling (sizing? )
+Respect monitor position(for weird monitor arrangement)
+follows   $HOME/.config/rofi/clipboard.rasi for height and width

Please Leave Comments for improvements!

https://github.com/prasanthrangan/hyprdots/assets/53417443/0d7d5c27-0b5e-4cfe-8dad-4332af6f8615

### CODE REVIEW

**Comment by kRHYME7** [comment]
!!! 'bc' is a Dependency, ill try to not use bc

**Comment by prasanthrangan** [comment]
Hi, when its launched from (or near) corners, the rofi menu goes out of screen...

image

**Comment by kRHYME7** [comment]
Is your monitor somewhat Rotated? If not Ill try to fix this tomorrow.  Maybe I did not commit my latest change.

**Comment by kRHYME7** [comment]
Maybe this is not ready yet

**Comment by prasanthrangan** [comment]
> Is your monitor somewhat Rotated? If not Ill try to fix this tomorrow. Maybe I did not commit my latest change.

nope, its not rotated... just normal orientation!
sure, no worries!

**Comment by kRHYME7** [comment]
My guess is the 55%  screen height is used by  .rasi file. I'll try to fix this in my free time. Thanks!

**Comment by kRHYME7** [comment]
Please try and give some screenshots of the issues. Thanks!

**Comment by kRHYME7** [comment]
I'll will be back haha

**Comment by kRHYME7** [comment]
Please someone try

**Review by prasanthrangan — APPROVED** [review]
looks good, thank you so much!

**Pull request merged**
