### PR TITLE
feat: Animate waybar gpuinfo and memory module

### PR DESCRIPTION
**Pull request by mislah**
# Pull Request

## Description

Animated the icons in the gpuinfo module and memory module. The thermometer icons and utilization icons (inclusive of those in tooltip) changes the state depending on the current level of temperature and utilization. 

Also included some minor UI improvements.

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

Look carefully at the thermometers & speedometers (uh oh, ignore the extra one, that's for cpu info, I'll add it in a different PR)

hypr

## Note

I don't like people editing my comments, I'll cry :-/

### CODE REVIEW

**Comment by kRHYME7** [comment]
I love it! 😍 

BTW can we make the emoji into glyphs? Because emoji sometimes won't fit to a certain theme.  
https://www.nerdfonts.com/cheat-sheet

**Comment by mislah** [comment]
> I love it! 😍
> 
> BTW can we make the emoji into glyphs? Because emoji sometimes won't fit to a certain theme. https://www.nerdfonts.com/cheat-sheet Like this? image
> 
>   󱪄 󱪃  󰈸

Umm, but, glyphs just don't quite capture the enchantment that emojis bring

c

Should I convert 'em all back to glyphs? :-|

**Comment by kRHYME7** [comment]
> Umm, but, glyphs just don't quite capture the enchantment that emojis bring

You have a point.
 I can't decide for the Users through.  I am using a fork of this so it would be fine for me.  

Some might prefer the more consistent look. But this is a small detail. 

Looks good BTW

**Review by prasanthrangan — APPROVED** [review]
same as cpuinfo, any reason using arrays and awk to read a key pair value instead of a simple case or json format?

**Pull request merged**
