### PR TITLE
Some minor waybar fixes and enhancements

### PR DESCRIPTION
**Pull request by its-19818942118**
# Pull Request

## Description

some minor fixes of waybar alignments issues. added fonts but didnt know how to make so the scripts read the fonts. waybar works fine. added seconds hand on the clock.

Please read these instructions and remove unnecessary text.

## Type of change

Please put an `x` in the boxes that apply:

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [X] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [X] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [X] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [X] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by its-19818942118** [comment]
@kRHYME7 @Skerse @rubiin @prasanthrangan

**Comment by abenezerw** [comment]
image
looks fine here.

**Review by abenezerw — COMMENTED** [review]
Checked the files out on my pc. they work fine on most of the styles of the waybar, on some the whole thing becomes zoomed in.

**Comment by rubiin** [comment]
> Checked the files out on my pc. they work fine on most of the styles of the waybar, on some the whole thing becomes zoomed in.

can you also share the zoomed in screenshots. Will help in reviewing pr

**Comment by kRHYME7** [comment]
default:
image
image
image


PR
image
image
image


TBH, I really like it! I did not check the files changed though, but please be sure not to hard code some values if possible, in case.


Overall, this is neat! Will further test this.


Spacing issues: 
image

**Comment by abenezerw** [comment]
> > Checked the files out on my pc. they work fine on most of the styles of the waybar, on some the whole thing becomes zoomed in.
> 
> can you also share the zoomed in screenshots. Will help in reviewing pr

image

**Comment by abenezerw** [comment]
1. By the way im using a lenovo legion laptop and it has a feature where you can set the battery to be stuck around 60% and use it while charging to prevent long term battery damage, i always use it charging and was wondering if the script has any parts i could alter to swap to plugged in icon in this state. 
2. A suggestion for the network/wifi icons. why not combine them i personally like the three dotted wifi icon. but the other one where it shows network when hovered on seems to be unused. maybe combine them to have more space?

**Comment by kRHYME7** [comment]
@abenezerw 

re:1. This is handled by the battery module of waybar itself, so the display is based on the default waybar program.
 
re:2. we can't the other one is a system tray Icon other is a module.(if someone wants to make custom script to lauch rofi and handle the wifi would be nice. )

**Comment by kRHYME7** [comment]
One more note to anyone tetsing a  PR and preserving their current configs 

` Hyde backup all `  backs up your config (name it to something you remember) 

` Hyde --dev ` then select ` pull request ` 

` Hyde restore Config ` to populate the Configs 
repeat 


to revert back to your back up ` Hyde backup revert ` select the  backup.

**Comment by its-19818942118** [comment]
> default: image image image
> 
> PR image image image
> 
> TBH, I really like it! I did not check the files changed though, but please be sure not to hard code some values if possible, in case.
> 
> Overall, this is neat! Will further test this.
> 
> Spacing issues: image

tell me the moddules which have spacing issues. none of this is tested on local cuz my waybar is broken. but yeah if you let me know i can fix it. i can also make more custom layouts.

**Comment by abenezerw** [comment]
> > default: image image image
> > PR image image image
> > TBH, I really like it! I did not check the files changed though, but please be sure not to hard code some values if possible, in case.
> > Overall, this is neat! Will further test this.
> > Spacing issues: image
> 
> tell me the moddules which have spacing issues. none of this is tested on local cuz my waybar is broken. but yeah if you let me know i can fix it. i can also make more custom layouts.
> 
> edit: this seems to be like screen scaling. cuz i have a small screen. so it was perfect on my side. but i think i need to add mono spaced fonts.

i agree with the screen scaling cause the modules dont collide on my end too

**Comment by rubiin** [comment]
> > default: image image image
> > PR image image image
> > TBH, I really like it! I did not check the files changed though, but please be sure not to hard code some values if possible, in case.
> > Overall, this is neat! Will further test this.
> > Spacing issues: image
> 
> tell me the moddules which have spacing issues. none of this is tested on local cuz my waybar is broken. but yeah if you let me know i can fix it. i can also make more custom layouts.
> 
> edit: this seems to be like screen scaling. cuz i have a small screen. so it was perfect on my side. but i think i need to add mono spaced fonts.

Will also give it a test when I am free

**Comment by its-19818942118** [comment]
> > > Checked the files out on my pc. they work fine on most of the styles of the waybar, on some the whole thing becomes zoomed in.
> > 
> > 
> > can you also share the zoomed in screenshots. Will help in reviewing pr
> 
> image

this is because the icon size is in percentage. depending on the space and height it will adjust. i made it so that it isnt hardcoded. i guess need to fix it. but my waybar just broke so i couldnt test any of this

**Comment by abenezerw** [comment]
Whats the edit?

**Comment by its-19818942118** [comment]
> > > default: image image image
> > > PR image image image
> > > TBH, I really like it! I did not check the files changed though, but please be sure not to hard code some values if possible, in case.
> > > Overall, this is neat! Will further test this.
> > > Spacing issues: image
> > 
> > 
> > tell me the moddules which have spacing issues. none of this is tested on local cuz my waybar is broken. but yeah if you let me know i can fix it. i can also make more custom layouts.
> > edit: this seems to be like screen scaling. cuz i have a small screen. so it was perfect on my side. but i think i need to add mono spaced fonts.
> 
> Will also give it a test when I am free

sure and will be adding more functionality over all

**Comment by its-19818942118** [comment]
also someone pls test pulse audio cuz my system doesnt have audio. so nothing works. no audio cuz my drivers dont work idk why. but yeah let me if you find something

**Comment by abenezerw** [comment]
image
There's this text on hover.

**Comment by its-19818942118** [comment]
ok i just tested this but mono spaced fonts make it look janky and unprofessional. so unfortunately i cant implement a mono spaced font it ruins it. check the before and after you guys. trust me it makes the older version look shit

**Comment by its-19818942118** [comment]
also @kRHYME7 i found the issue its seems to be the network icon that is interfering and making it collide

**Comment by abenezerw** [comment]
> ok i just tested this but mono spaced fonts make it look janky and unprofessional. so unfortunately i cant implement a mono spaced font it ruins it. check the before and after you guys. trust me it makes the older version look shit

Haha, did you fix the <span> issue

**Comment by its-19818942118** [comment]
> > ok i just tested this but mono spaced fonts make it look janky and unprofessional. so unfortunately i cant implement a mono spaced font it ruins it. check the before and after you guys. trust me it makes the older version look shit
> 
> Haha, did you fix the *span issue

@abenezerw which one

**Comment by abenezerw** [comment]
> > > ok i just tested this but mono spaced fonts make it look janky and unprofessional. so unfortunately i cant implement a mono spaced font it ruins it. check the before and after you guys. trust me it makes the older version look shit
> > 
> > 
> > Haha, did you fix the *span issue
> 
> @abenezerw which one

Hover over brightness, audio, mic or updates. It shows extra text. See the screenshot I left above.

**Comment by its-19818942118** [comment]
> > ok i just tested this but mono spaced fonts make it look janky and unprofessional. so unfortunately i cant implement a mono spaced font it ruins it. check the before and after you guys. trust me it makes the older version look shit
> 
> Haha, did you fix the *span issue

@abenezerw dont have it on my end. i dont get any tooltip lol

**Comment by its-19818942118** [comment]
> > ok i just tested this but mono spaced fonts make it look janky and unprofessional. so unfortunately i cant implement a mono spaced font it ruins it. check the before and after you guys. trust me it makes the older version look shit
> 
> Haha, did you fix the *span issue

@abenezerw broo i didnt get this issue on my end lol

**Comment by its-19818942118** [comment]
aight guys created a dev server just for feedback on pr and new stuff and dev discussion. cuz the HyDE server just makes it cluttered and people feel lost. plus github isnt really intuitive for chatting. if you want to you can join the server.
https://discord.gg/FYJQT9DReV

**Comment by its-19818942118** [comment]
Ok the tooltip thing is fixed substitution with hard coded icons cuz if not it still prints out the guts that fixes the icons. Had not choice 😕😞

**Comment by its-19818942118** [comment]
@kRHYME7 @prasanthrangan ready to go. pls approve this. i need more feedback on this.

**Review by kRHYME7 — COMMENTED** [review]
This  "minor"  is not minor to me. Well, looks good though! 🫰

**Comment by its-19818942118** [comment]
> This "minor" is not minor to me. Well, looks good though! 🫰

what compared to oothers works mine is minimal af. people have good shit i am just tweaking a bit of the waybar to make the ui look nice. lol @kRHYME7

**Comment by kRHYME7** [comment]
Hard-coded colors too.

**Comment by its-19818942118** [comment]
Well yeah colors need to be hardcoded or it looks messed up 😅

**Comment by its-19818942118** [comment]
Well yeah colors need to be hardcoded or it looks messed up 😅

**Comment by its-19818942118** [comment]
@prasanthrangan

**Comment by its-19818942118** [comment]
@rishav12s

**Review by rishav12s — APPROVED** [review]

**Comment by dieBakterie** [comment]
The right click entry for the audio selector is missing in your pulseaudio.jsonc

**Comment by its-19818942118** [comment]
> The right click entry for the audio selector is missing in your pulseaudio.jsonc

i added it. i am sure i did

**Review by abenezerw — COMMENTED** [review]
Finally got to trying this out again, still looks okay. but i guess this counts as big changes so its not merged maybe.

**Comment by its-19818942118** [comment]
@abenezerw :sob: io will just close this

**Comment by rishav12s** [comment]
@its-19818942118 nnnnnnnnnnoooooooooo 😭😭😭😭💔💔💔💔💔

**Comment by its-19818942118** [comment]
> @its-19818942118 nnnnnnnnnnoooooooooo 😭😭😭😭💔💔💔💔💔

@rishav12s 🥺 💔

**Pull request closed without merging**
