### PR TITLE
feat(notification): dnd support  for dunst

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

☑️ Option to enable DND. 
☑️ Use mouse  scroll down to see history. 

image

### CODE REVIEW

**Review by rubiin — APPROVED** [review]
NICE

**Comment by rubiin** [comment]
I think this waybar used here is damn good. Hope we can copy some stuff
[AXWTV/Hyprland-DotFiles](https://github.com/AXWTV/Hyprland-DotFiles) @kRHYME7

**Review by abenezerw — APPROVED** [review]
works, but need to add "custom/notifications" in waybar/config.ctl

**Comment by Sitolam** [comment]
> I think this waybar used here is damn good. Hope we can copy some stuff
> [AXWTV/Hyprland-DotFiles](https://github.com/AXWTV/Hyprland-DotFiles) @kRHYME7 

The bar is made with ags not with waybar.

**Comment by kRHYME7** [comment]
> works, but need to add "custom/notifications" in waybar/config.ctl

It's fine, some config.ctl already have it. Therefore, it's for the users to modify.

**Review by mahaveergurjar — APPROVED** [review]
Work good but more space for dnd icon not look good
image
before 
image
After remove extra space
image

**Review by mahaveergurjar — APPROVED** [review]

**Comment by mahaveergurjar** [comment]
Add I Will and one more feature so see the first 10 notifications instead of  showing 1 notification

This type 
240722_19h47m24s_screenshot
image

**Comment by kRHYME7** [comment]
Yes merge this PR first then  push yours. It would help us track down the commits in case of regressions.

**Comment by mahaveergurjar** [comment]
ok

**Comment by mahaveergurjar** [comment]
So can I make this pr copy and then push pr right ??

**Comment by kRHYME7** [comment]
yup 
* Create a new branch from main 
* merge this PR first 
* Add your changes 
* Push it upstream

**Pull request closed without merging**
