### PR TITLE
Waybar Persistent Workspaces update -- Deprecated value removed 

### PR DESCRIPTION
**Pull request by T-Crypt**
Fixed waybar

*Note: Latest waybar updates sucks. Its tapping 1-3 cores at 100% -- I'm going to downgrade for the time being but I wanted this to be fixed for the updates coming

231103_09h01m08s_screenshot

This is fixed in [0.9.24](https://github.com/Alexays/Waybar/releases/tag/0.9.24)

### CODE REVIEW

**Comment by kRHYME7** [comment]
Hi @T-Crypt. Can I know which waybar version  have issues? I got v 0.9.22.(travel laptop) and v 0.9.23 (docked at home)  and on checkupdates waybar 0.9.24-1 is available . I'm hesistant to updgrade yet.  Because my laptop can't bare greater thermals .  Thank You.

**Comment by T-Crypt** [comment]
@kRHYME7 -- 0.9.24-1 is the fix for the CPU reaping issues. 

0.9.22 is good, 0.9.23 is the issue

**Comment by T-Crypt** [comment]
Anyone with waybar issues.

Yay -Syu waybar 

231103_10h03m42s_screenshot

Fixed in 0.9.24-1

231103_10h04m42s_screenshot

**Review by TheyCallMeSecond — APPROVED** [review]

**Comment by kRHYME7** [comment]
Thanks !

**Review by prasanthrangan — APPROVED** [review]
looks good, thanks!

**Pull request merged**
