### PR TITLE
Adjusting the discord palette generator and fixing the invisible text

### PR DESCRIPTION
**Pull request by Faeziix**
# Pull Request

## Description

This is an attempt to improve the discord theme. Now there are shades of the background color so it results into more beautiful theme. Also no more invisible text as mentioned in this issue (#1407). 

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

### Before: 
image

### After 
image

### CODE REVIEW

**Comment by Faeziix** [comment]
We can also make the theme look like this. 

image

This one looks also good but I noticed it's not as consistent as the first one.

**Review by prasanthrangan — APPROVED** [review]
alright, looks good to me.. thank you!

**Comment by prasanthrangan** [comment]
Hey @Faeziix , looks like you are working on this now, so let me know when its ready to merge.

**Comment by Faeziix** [comment]
@prasanthrangan It is ready for merge now.

**Comment by prasanthrangan** [comment]
great, thank you bro!

**Comment by Faeziix** [comment]
My pleasure. That was my first contribution ever :)

**Pull request merged**
