### PR TITLE
added neovim

### PR DESCRIPTION
**Pull request by jpx40**
push my changes to dev instead of main

### CODE REVIEW

**Comment by RAprogramm** [comment]
hi! look at [NEVIRAIDE](https://github.com/RAprogramm/NEVIRAIDE)! what do you think about it?

**Comment by jpx40** [comment]
> hi! look at [NEVIRAIDE](https://github.com/RAprogramm/NEVIRAIDE)! what do you think about it?
> it's almost done. with all kinds of hyprdots themes. i just dicide to make an AUR installer instead of adding .config/nvim directory to hyprdots

We can add themes in nvim very easy. Lazyvim just uses one function to update the theme. Although lazyvim is one of the best nvim distros. It's made by folke the maintainer of the plugin manager lazy.

**Comment by RAprogramm** [comment]
> > hi! look at [NEVIRAIDE](https://github.com/RAprogramm/NEVIRAIDE)! what do you think about it?
> > it's almost done. with all kinds of hyprdots themes. i just dicide to make an AUR installer instead of adding .config/nvim directory to hyprdots
> 
> We can add themes in nvim very easy. Lazyvim just uses one function to update the theme. Although lazyvim is one of the best nvim distros. It's made by folke the maintainer of the plugin manager lazy.

I know) did you see my repo?

**Comment by jpx40** [comment]
It's a good config. But maybe go with lazyvim since it has more default features. And merge some stuff of neviraid.

**Comment by jpx40** [comment]
> > > hi! look at [NEVIRAIDE](https://github.com/RAprogramm/NEVIRAIDE)! what do you think about it?
> > > it's almost done. with all kinds of hyprdots themes. i just dicide to make an AUR installer instead of adding .config/nvim directory to hyprdots
> > 
> > We can add themes in nvim very easy. Lazyvim just uses one function to update the theme. Although lazyvim is one of the best nvim distros. It's made by folke the maintainer of the plugin manager lazy.
> 
> I know) did you see my repo? 

So that you are a rust dev have interest do some cli tools for this repo in Rust. Start to doing something so that user could decide between the software and stuff.

**Comment by jpx40** [comment]
> > > hi! look at [NEVIRAIDE](https://github.com/RAprogramm/NEVIRAIDE)! what do you think about it?
> > > it's almost done. with all kinds of hyprdots themes. i just dicide to make an AUR installer instead of adding .config/nvim directory to hyprdots
> > 
> > We can add themes in nvim very easy. Lazyvim just uses one function to update the theme. Although lazyvim is one of the best nvim distros. It's made by folke the maintainer of the plugin manager lazy.
> 
> I know) did you see my repo? 

https://github.com/RAprogramm/neviraide-ui.nvim
 ah i see what you have  done ✔️ i mean yeah is it compatible with lazyvim or can we take over some stuff.

**Comment by prasanthrangan** [comment]
Hey @RAprogramm and @jpx40 , the main idea is to create an [installer](https://github.com/jpx40/hyperdots_installer) (built with rust by jpx40) that works like `archinstall`.

So the installer should do these,
- display available user options
- record user input
- generate the install list based on user input
- execute the install script

Here is the user option list I've in mind -

> ### aur
>  - [x] yay
>  - [ ] paru

> ### shell
>  - [x] zsh
>  - [ ] fish

> ### notification
>  - [x] dunst
>  - [ ] swaync

> ### browser
>  - [x] firefox
>  - [x] brave
>  - [ ] tor
>  - [ ] edge
>  - [ ] chrome

> ### IDE
>  - [x] vscode
>  - [ ] code-oss
>  - [ ] naviraide
>  - [ ] lazyvim
>  - [x] neovim

> ### extras
>  - [x] spotify
>  - [x] cava
>  - [x] steam
>  - [ ] gamemode
>  - [ ] gamescope
>  - [ ] mangohud

> ### flatpaks
>  - [x] app1
>  - [x] app2
>  - [ ] app3
>  - [x] app4
>  - [ ] app5
>  - [ ] app6
>  - [ ] app7

> ### source custom list file
> > ```/path/to/your/applist```

**Comment by jpx40** [comment]
> Hey @RAprogramm and @jpx40 , the main idea is to create an [installer](https://github.com/jpx40/hyperdots_installer) (built with rust by jpx40) that works like `archinstall`.
> 
> So the installer should do these,
> - display available user options
> - record user input
> - generate the install list based on user input
> - execute the install script
> 
> Here is the user option list I've in mind -
> 
> > ### aur
> >  - [x] yay
> >  - [ ] paru
> 
> > ### shell
> >  - [x] zsh
> >  - [ ] fish
> 
> > ### notification
> >  - [x] dunst
> >  - [ ] swaync
> 
> > ### browser
> >  - [x] firefox
> >  - [x] brave
> >  - [ ] tor
> >  - [ ] edge
> >  - [ ] chrome
> 
> > ### IDE
> >  - [x] vscode
> >  - [ ] code-oss
> >  - [ ] naviraide
> >  - [ ] lazyvim
> >  - [x] neovim
> 
> > ### extras
> >  - [x] spotify
> >  - [x] cava
> >  - [x] steam
> >  - [ ] gamemode
> >  - [ ] gamescope
> >  - [ ] mangohud
> 
> > ### flatpaks
> >  - [x] app1
> >  - [x] app2
> >  - [ ] app3
> >  - [x] app4
> >  - [ ] app5
> >  - [ ] app6
> >  - [ ] app7
> 
> > ### source custom list file
> > > ```/path/to/your/applist```
> 

Already have the basic functionality to generate the list. Wanna test it?

**Comment by jpx40** [comment]
finished basic functionality of the rust tool. should be usable now

**Comment by rubiin** [comment]
> Hey @RAprogramm and @jpx40 , the main idea is to create an [installer](https://github.com/jpx40/hyperdots_installer) (built with rust by jpx40) that works like `archinstall`.
> 
> So the installer should do these,
> 
> * display available user options
> * record user input
> * generate the install list based on user input
> * execute the install script
> 
> Here is the user option list I've in mind -
> 
> > ### aur
> > 
> > * [x]  yay
> > * [ ]  paru
> 
> > ### shell
> > 
> > * [x]  zsh
> > * [ ]  fish
> 
> > ### notification
> > 
> > * [x]  dunst
> > * [ ]  swaync
> 
> > ### browser
> > 
> > * [x]  firefox
> > * [x]  brave
> > * [ ]  tor
> > * [ ]  edge
> > * [ ]  chrome
> 
> > ### IDE
> > 
> > * [x]  vscode
> > * [ ]  code-oss
> > * [ ]  naviraide
> > * [ ]  lazyvim
> > * [x]  neovim
> 
> > ### extras
> > 
> > * [x]  spotify
> > * [x]  cava
> > * [x]  steam
> > * [ ]  gamemode
> > * [ ]  gamescope
> > * [ ]  mangohud
> 
> > ### flatpaks
> > 
> > * [x]  app1
> > * [x]  app2
> > * [ ]  app3
> > * [x]  app4
> > * [ ]  app5
> > * [ ]  app6
> > * [ ]  app7
> 
> > ### source custom list file
> > > `/path/to/your/applist`

I have been meaning to ask this too. Before applying any config and theming to certain apps, its good to use user prompt. Many have their own config, like in my case I have my own neovim config . This is particularly useful for user who are not using a minimal arch install (jumping from configured desktop) or only want to reapply certain changes

**Comment by kRHYME7** [comment]
Hello the new branch 'HyDE' plus its Hyde-CLI should grant users freedom to cherry-pick what dots will be overwritten, sync( this one is misleading, but it will cp -f the target directory effectively overwriting conflicts )

Should look like this 
image

**Comment by jpx40** [comment]
> (Unrelated to the package installer, but related to user configs )
> Hello the new branch 'HyDE' plus its Hyde-CLI should grant users freedom to cherry-pick what dots will be overwritten, sync( this one is misleading, but it will cp -f the target directory effectively overwriting conflicts )
> 
> Should look like this 
> image
> 

Can you help me make the cli, i don't have much time in the moment since I have exams. I know it's not ready yet.

**Comment by kRHYME7** [comment]
I can test it if you want, I already cloned the repo.
 But rust is a new environment for me. 

I only have a small knowledge of c++ (embedded systems, specifically not for things like this 😭). Then now rust that is totally new for me haha

But I am willing to test this! DM me at discord 'khing0v0'

**Comment by jpx40** [comment]
> I can test it if you want, I already cloned the repo. But rust is a new environment for me.
> 
> I only have a small knowledge of c++ (embedded systems, specifically not for things like this 😭). Then now rust that is totally new for me haha
> 
> But I am willing to test this! DM me at discord 'khing0v0'

if you know cpp rust would be easy for you. Cpp is the closet to Rust

**Comment by rubiin** [comment]
> (Unrelated to the package installer, but related to user configs ) Hello the new branch 'HyDE' plus its Hyde-CLI should grant users freedom to cherry-pick what dots will be overwritten, sync( this one is misleading, but it will cp -f the target directory effectively overwriting conflicts )
> 
> Should look like this image

Is there a usage readme and how to get started. Also is it stable

**Comment by kRHYME7** [comment]
> Is there a usage readme and how to get started. 

> Also is it stable
No, We are on the dev branch so expect rolling changes. And this script will always follow the latest commit (unless this repo will have tags to anchor my commits)

About README here's the repo https://github.com/kRHYME7/Hyde-cli

Did not make a readme yet but ``` Hyde man ``` Should provide information on usage
image


Probably this is installed on your end, run ``` Hyprdots man ```

**Pull request closed without merging**
