### PR TITLE
feat: add OS age and Uptime to fastfetch

### PR DESCRIPTION
**Pull request by sanjyay**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

image

## Additional context
Neofetch used to display Uptime which was missing in fastfetch and also displaying OS age is an interesting feature that lets the user known how long they have been using the particular distro

### CODE REVIEW

**Review by Enigma1309 — APPROVED** [review]

**Review by abenezerw — APPROVED** [review]
Works! Os Age is a pretty cool info, haha just realised been using this for 196 days haha.
image

**Review by rubiin — APPROVED** [review]

**Comment by kRHYME7** [comment]
>  how long they have been using the particular distro

Best fit for a distro hopper. Lol. 
But yeah, It's cool!

Can you send me a screenshot of the latest commits? @rubiin @sanjyay  

Also, please resolve the comments too.

**Comment by Enigma1309** [comment]
image
I smell something wrong

**Comment by sanjyay** [comment]
i am new to git . I messed up using git pull. 

> image I smell something wrong

i am new to git . I messed up with git pull so basically now my pull request as all the commits that have been performed in the project. I tried to solve it but like you can see i was able to do anything. Can you help or will it be better if i just create a new pull request?

**Comment by sanjyay** [comment]
> Happens to anyone. Just create a new one.

thank you. I have created another PR #1697

**Pull request closed without merging**
