### PR TITLE
feat: Add Japanese Kanji Chars in Workspace Names

### PR DESCRIPTION
**Pull request by chrollorifat**
-Instead of the plain old Arabic  Numerals, added the Japanese Kanji characters for aesthethic in the workspace bar.
-Also, made 5 persistence workspaces by default to highlight the kanji characters in the workspace bar.
240419_01h05m57s_screenshot

### CODE REVIEW

**Comment by kRHYME7** [comment]
How to turn this off?

**Comment by rubiin** [comment]
yeah userperfs seems to be a valid point for such thing. Its more of a personal preference than what everyone wants

**Comment by ChrolloRifat** [comment]
> How to turn this off?

You just need to comment out `"format": "{icon}",` and  `"*": 5,`  lines in the `~/.config/waybar/modules/workspaces.jsonc` file. We could even make a script to handle this.

**Comment by ChrolloRifat** [comment]
> Better to add this on your userprefs (hyprland config)?
> 
> https://wiki.hyprland.org/Configuring/Workspace-Rules/#rules https://wiki.hyprland.org/Configuring/Dispatchers/
> 
> Something like image
> 
> `~/.config/hypr/userprefs.conf`
> 
> ```
> workspace = 1, defaultName:一
> workspace = 2, defaultName:二
> workspace = 3, defaultName:三
> workspace = 4, defaultName:四
> workspace = 5, defaultName:五
> workspace = 6, defaultName:六
> workspace = 7, defaultName:七
> workspace = 8, defaultName:八
> workspace = 9, defaultName:九
> workspace = 10, defaultName:十
> 
> 
> workspace = 一, persistent:true
> workspace = 二, persistent:true
> workspace = 三, persistent:true
> workspace = 四, persistent:true
> workspace = 五, persistent:true
> ```

Doing it this way seems to create some issues.

**Comment by ChrolloRifat** [comment]
I could make a script if you guys agree on this.

**Comment by kRHYME7** [comment]
How about this one 

https://github.com/kRHYME7/Hyde-cli/wiki/Dots-Management
image



For custom path options 
add 'userPrefsDir=path/to/user/directory' in '~/.config/hyde/hyde.conf' for custom user path

**Comment by kRHYME7** [comment]
@ChrolloRifat  Hello can you checkout this commit. This way we can add our modules freely without overwriting the default module.

https://github.com/prasanthrangan/hyprdots/pull/1418

**Comment by kRHYME7** [comment]
@chrollorifat 

image

We now can add our own custom version of the module  like this.  
image

**Review by kRHYME7 — CHANGES_REQUESTED** [review]
For point of concept, we can move this changes to ` Configs/.config/waybar/modules/workspaces#kanji.jsonc `  and let the original file unchanged.

**Pull request closed without merging**
