### PR TITLE
Touchpad gestures 

### PR DESCRIPTION
**Pull request by mahaveergurjar**
# Pull Request

## Description

Add touchpad gestures for laptop users 
user can customise the gesture using gesture app or changing in libinput-gestures.conf file 

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x]My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [x] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Screenshots

240316_23h51m51s_screenshot
240316_23h52m02s_screenshot

### CODE REVIEW

**Comment by kRHYME7** [comment]
I only had a laptop too, hence this is useful. However, can we make an adjustment to respect non touchpad users?.

1. Put the libinput packages list to ``` ./custom_app.lst ``` this way, it will be optional.
2. Add an entry to the restore list and ``` libinput-gestures ``` as dependency. Use N|Y flag because it acts like key binds (user pref)
It should look like this 
```
N|Y|${HOME}/.config/hypr|libinput-gestures.conf|libinput-gestures
```


If you needed help implementing the above, surely am happy to help.

**Comment by mahaveergurjar** [comment]
Thanks for guiding  I will make new PR

**Comment by mahaveergurjar** [comment]
And what about exec-once can put in userprefs.t2 or hyprland.config

**Comment by kRHYME7** [comment]
Maybe?  There are multiple ways to do it to avoid error warnings

``` exec-once = command -v libinput-gestures && libinput-gestures ```

**Comment by mahaveergurjar** [comment]
Ok i will put in userprefs.t2

**Pull request closed without merging**
