### PR TITLE
Nordic-Blue Theme (Optional) 

### PR DESCRIPTION
**Pull request by T-Crypt**
Let me know if you would like this theme added to the repo. This goes in line with the Gruvbox type feel.

theme_nordic_1

theme_nordic_2

**Optional: We could also add the package `python-image-go-nord` for users to create there own Nord wallpapers!

### CODE REVIEW

**Comment by kRHYME7** [comment]
Have tried and Patched it 
image

**Comment by T-Crypt** [comment]
@kRHYME7 love that your using glava!

**Comment by kRHYME7** [comment]
> @kRHYME7 love that your using glava!

I can't make Cava work on my system(Not actually committing to it) unless I install it using the Nix package. Also, I think Glava looks better Haha .


> I wish there was wayland support to run glava --desktop

:disappointed:

**Comment by kRHYME7** [comment]
wallbash Enabled ,
some of the wallpapers exhibit this

image

**Comment by T-Crypt** [comment]
@kRHYME7 -- Thanks for the update. 

Ill rework the wallpapers sometime today or tomorrow to make sure the wallbash doesn't conflict!

**Comment by prasanthrangan** [comment]
Whoa @T-Crypt ... looks amazing!
we already have 10 preinstalled themes, so i think we can install this with the themepatcher...
and maintain separate repo so that users can choose and install the theme they like!
I think we can maintain gallery in the wiki section and links to install these themes :)

**Comment by T-Crypt** [comment]
@prasanthrangan Thats perfect, we can add an additional theme install Wiki and link user created themes there for optional install! I like the idea and gives users the ability to pick and choose what they would like! 

I'll close this and just throw my themes in a discussion with the links for you to add to the wiki once you get some time! 

Hope you had a good trip! Tried maintaining the chaos as best as I could!

**Comment by prasanthrangan** [comment]
> @prasanthrangan Thats perfect, we can add an additional theme install Wiki and link user created themes there for optional install! I like the idea and gives users the ability to pick and choose what they would like!
> 
> I'll close this and just throw my themes in a discussion with the links for you to add to the wiki once you get some time!

Ya the wiki is kinda outdated, I've to update it soon as there are many new users now...

> Hope you had a good trip! Tried maintaining the chaos as best as I could!

yup saw that, thank you so much for helping with the issues!

**Comment by T-Crypt** [comment]
@prasanthrangan If you give me access to update or to draft changes to the Wiki, I could work on that for you. 

Also, wouldn't mind having the ability to add labels or help with the issues as I'm a different time zone so I could at least help with sorting out issues! If you don't want to add permissions then no worries, Ill keep doing what I do!

**Comment by prasanthrangan** [comment]
> @prasanthrangan If you give me access to update or to draft changes to the Wiki, I could work on that for you.
> 
> Also, wouldn't mind having the ability to add labels or help with the issues as I'm a different time zone so I could at least help with sorting out issues! If you don't want to add permissions then no worries, Ill keep doing what I do!

Hey, thank you... I've added you as collaborator!

**Pull request closed without merging**
