### PR TITLE
Keyboard Layout Switch - bind SUPER + K 

### PR DESCRIPTION
**Pull request by T-Crypt**
Must have alt keyboard layout defined in hyprland.conf 

Fixes issue #306

### CODE REVIEW

**Comment by kRHYME7** [comment]
image

**Comment by T-Crypt** [comment]
Integrated notification within the script -- no need for alt shellevent or notification for this. 

Ready to merge.

**Comment by kRHYME7** [comment]
@T-Crypt  Can't review your code but I will try to merge this on my repos to check functionality. Thanks

**Comment by kRHYME7** [comment]
Output: 
231012_09h53m10s_screenshot

It works on my system

231010_00h40m35s_screenshot
us
polish

**Comment by prasanthrangan** [comment]
> polish

Hi, Thank you guys for working on this! I'll test this out maybe this weekend...
couple of questions,
1. why is all devices shown in notification?
2. the python script is only using `subprocess` and `sys` commands for bash. so why not use bash directly?

**Comment by T-Crypt** [comment]
@prasanthrangan 

1. the notifications are all showing for his testing cause he installed shellevents on his system. (it notifies him of any keyboard layout changes for all his devices) -- the main script does not show all the notifications, just 1 
2. I was having issues executing this as bash -- I can test this today to see if I can convert this to bash.

**Comment by prasanthrangan** [comment]
this seem to work for me to detect my keyboard -
```
hyprctl -j devices | jq '.keyboards' | jq '.[] | select (.main == true)'
```
so the python script can be directly converted, seems like its straight forward!

**Comment by T-Crypt** [comment]
> this seem to work for me to detect my keyboard -
> 
> ```
> hyprctl -j devices | jq '.keyboards' | jq '.[] | select (.main == true)'
> ```
> 
> so the python script can be directly converted, seems like its straight forward!

The thing I noticed / concerned about is: 

1. My system has my asus-wmi-hotkeys as .main == true so it does not return my actual keybaord. 
2. Don't we want to change the layout for all keyboard devices as so it is uniform across the board and not "US" layout for some devices and changed layout for the main? 

This statement works alot better to get all keyboard devices (working on this now)

`hyprctl devices -j | jq -r '.keyboard[].name'`

then cycle the through the names on 

`hyprctl switchxblayout $name next`

**Comment by T-Crypt** [comment]
Updated -- 

keyboardswitch.py updated to keyboardswitch.sh 

keybindings updated to keyboardswitch.sh on SUPER + K

**Review by prasanthrangan — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
