### PR TITLE
Added the ability to have a random background image for SDDM theme Candy

### PR DESCRIPTION
**Pull request by hui3215**
# Pull Request

## Description

Fixed an issue where the background image of the sddm theme Candy was confusing with multiple results
240228_18h40m30s_screenshot

240228_18h40m09s_screenshot

Added the ability to create a random background image for the SDDM Candy theme

240228_18h37m45s_screenshot

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Review by justsarx — APPROVED** [review]
Working correctly without breaking.
Suitable for merging in the main branch.

**Comment by prasanthrangan** [comment]
> Fixed an issue where the background image of the sddm theme Candy was confusing with multiple results

hmm sorry i don't understand the issue... what was confusing with multiple results??

**Comment by hui3215** [comment]
> > Fixed an issue where the background image of the sddm theme Candy was confusing with multiple results
> 
> 嗯，对不起，我不明白这个问题......什么与多个结果混淆？？




> > Fixed an issue where the background image of the sddm theme Candy was confusing with multiple results
> 
> hmm sorry i don't understand the issue... what was confusing with multiple results??

For example, this display, which contains the content of two images, emm, is it that we want this effect of combining multiple images?

**Comment by hui3215** [comment]
> > Fixed an issue where the background image of the sddm theme Candy was confusing with multiple results
> 
> hmm sorry i don't understand the issue... what was confusing with multiple results??

For example, this display, which contains the content of two images, emm, is it that we want this effect of combining multiple images?

**Review by prasanthrangan — APPROVED** [review]
But this works so I'll merge this

**Pull request merged**
