### PR TITLE
Add battery icon for laptop users

### PR DESCRIPTION
**Pull request by mahaveergurjar**
Add battery for laptop users in waybar

### CODE REVIEW

**Comment by mahaveergurjar** [comment]
Add battery icon in waybar for laptop users

**Comment by jhenrique04** [comment]
For some reason, it doesn't work here for me, is there any other step that I need to do after changing the file? I tried rebooting but still

**Comment by jhenrique04** [comment]
> Add battery for laptop users in waybar 

Worked here, thanks!

**Review by T-Crypt — APPROVED** [review]
-- tested -- verified -- Laptop: ASUS G17

**Comment by jhenrique04** [comment]
-- tested -- verified -- Laptop: Dell Vostro 3525

**Review by jhenrique04 — APPROVED** [review]
-- tested -- verified -- Laptop: Dell Vostro 3525

**Review by prasanthrangan — APPROVED** [review]
great, thank you!

**Pull request merged**
