### PR TITLE
feat(dolphin): show hidden files

### PR DESCRIPTION
**Pull request by rubiin**
This is useful when you want to edit some config from doplhin. As most config files and directory starts with `. `, they tend to be hidden

# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by rubiin** [comment]
Also we should disable starting dolphin from last location, it causes issues when the last postition was a thumb drive which was then removed and dolphin was removed. The issue is not function but from User experience

**Comment by kRHYME7** [comment]
> Also we should disable starting dolphin from last location, it causes issues when the last postition was a thumb drive which was then removed and dolphin was removed. The issue is not functional but from User experience. Somehow I couldnt find the setting for that

Navigate to home again? 

The feature is useful to changing the walls/themes so that the dolphin will go back to the last session.

**Comment by rubiin** [comment]
> > Also we should disable starting dolphin from last location, it causes issues when the last postition was a thumb drive which was then removed and dolphin was removed. The issue is not functional but from User experience. Somehow I couldnt find the setting for that
> 
> Navigate to home again?
> 
> The feature is useful to changing the walls/themes so that the dolphin will go back to the last session.

one downside I found was when an external hard drive was connected and when the folder dolphin was last in was deleted by an external program. Dolphin on launch would still launch on the non existent folder

**Comment by dieBakterie** [comment]
Also could we Change the `dolphinsteterc` it's Set for tittus widescreen with 2880x1090 and it opens the Window when opening a compressed File with ark for example of this size.

**Comment by Skerse** [comment]
So, you just want showing hidden files enabled by default?

Personally, i never found it hard to press the "eye" icon in the bottom right. You can even set `Scripts/restore_cfg.lst` to not overwrite your dolphin config, which would stop it from resetting when restoring.

**Comment by rubiin** [comment]
It also makes the hidden files appear first

**Comment by kRHYME7** [comment]
I personally added dolphinrc as preserve so that I can live with my own preference 
image

**Comment by rubiin** [comment]
Deleting this pr as I created this from main . Will create a new pr

**Pull request closed without merging**
