### PR TITLE
Refactor shebangs

### PR DESCRIPTION
**Pull request by kik4444**
# Pull Request

## Description

- Use `/usr/bin/env` in script shebangs instead of hard-coding paths.
- Trim trailing whitespace in affected files (courtesy of vscode).

### Motivation
I use NixOS and decided to give Hyprland a try, but I severely underestimated the amount of work required to turn a basic Hyprland install into a modern, usable, let alone good-looking, system. When I found this repo I was impressed by the finished state it showcased and wanted to try it for myself. However, many scripts and configs are currently incompatible with NixOS (e.g. everything that looks in `/usr/*` won't work because the only file in `/usr` in NixOS is `/usr/bin/env` which is itself a symlink to `/nix/store/...`).

So I decided to look over all the scripts and configs and try to fix whatever possible to make it compatible with NixOS without breaking existing Arch compatibility. But I still haven't looked over the entirety of this project so who knows whether I'll give up or lose interest in Hyprland before achieving anything significant.

I do **not** intend to touch any of the install scripts. My goal is to make the general usage scripts and configs compatible with NixOS without using Home-Manager and with a manual deployment at most. I imagine this will be easier than trying to port the entirety of Hyprdots to the Nix way since, theoretically, the only changes required would be to file paths.

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [x] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bphd** [comment]
Maybe you should universalize some more path before merging actually the patch. That solution could be really interesting if applied everywhere

**Comment by kik4444** [comment]
I was actually trying to separate it into multiple PRs though.

**Comment by bphd** [comment]
> I was actually trying to separate it into multiple PRs though.

Nice! Multiples commit would have done it aswell but it's even better

**Comment by prasanthrangan** [comment]
I just merged #1143 this looks the same, is this a duplicate?

**Comment by prasanthrangan** [comment]
> @prasanthrangan The PR you merged was from a later point within the same branch. That PR contained all the changes in this PR along with its own ones. I expected this PR to be merged first since it came first and so had less changes. That way the changes in the second PR should have been reduced. But now this is redundant so it doesn't matter.

great... also thank you so much for cleaning up the scripts :)

**Comment by bphd** [comment]
So now the project is officially not Arch only. It has kind of alpha NixOS support (and maybe more upon testing), maybe considerate updating docs

**Pull request closed without merging**
