### PR TITLE
Resolves #1695. Improve rofi's error message style

### LINKED ISSUE #1695: [Feature Request]: Rofi: Add a nicer message when accessing a non existing app
image

Replace the above with a themed error message

### PR DESCRIPTION
**Pull request by ArturLinnik**
# Pull Request

## Description
When trying to open an application in rofi that doesn't exist an unstyled error message with white background is shown.

I added the following code to hyprdots rofi styles in order to center the text and inherit the theme colors.

```rasi
// Error message //
error-message {
    text-color:                  @main-fg;
    background-color:            @main-bg;
    text-transform:              capitalize;
    children:                    [ "textbox" ];
}

textbox {
    text-color:                  inherit;
    background-color:            inherit;
    vertical-align:              0.5;
    horizontal-align:            0.5;
}
``` 
Fixes #1695

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

image

### CODE REVIEW

**Review by sanjyay — APPROVED** [review]
Works! Follows the theme
image

**Review by rubiin — APPROVED** [review]

**Review by abenezerw — APPROVED** [review]
image
Works.

**Review by kRHYME7 — APPROVED** [review]
Cool!

I did not merge this yet because I think there is an option to not accept inputs in dmenu but this is -drun therefore that option is not available in rofi yet. 

Thank you for contributing. 🙏

**Comment by kRHYME7** [comment]
image

**Pull request merged**
