### PR TITLE
[fix] which zsh not in the /etc/shell 

### LINKED ISSUE #896: [Bug]: Cant install ; chsh: "/sbin/zsh" is not listed in /etc/shells.
## Bug Report
```
[DISPLAYMANAGER] detected // sddm
[SKIP] sddm is already configured...
[FILEMANAGER] detected // dolphin
[FILEMANAGER] setting org.kde.dolphin.desktop as default file explorer...
[SHELL] detected // zsh
intalling zsh plugins (git sudo zsh-256color zsh-autosuggestions zsh-syntax-highlighting)
[SHELL] changing shell to zsh...
Changing shell for boobs.
Password: 
chsh: "/sbin/zsh" is not listed in /etc/shells.
Use chsh -l to see list.
```

$ chsh -l
/bin/sh
/bin/bash
/bin/rbash
/usr/bin/sh
/usr/bin/bash
/usr/bin/rbash
/usr/bin/git-shell
/bin/zsh
/usr/bin/zsh
/usr/bin/fish
/bin/fish

### Description

I think the wrong directory is selected somewhere?
/sbin/zsh insteam of /bin/zsh

### Steps to Reproduce

1. Start the installer

### Expected Behavior

install

### Actual Behavior

stops installing because directory doesn't exist

- ArchLinux
- 6.7.5-zen1-1-zen
- Hyprland Version, output of `hyprctl version`:
- Hardware
- 2560 1440

### PR DESCRIPTION
**Pull request by kRHYME7**
Fixes #896

### CODE REVIEW

**Comment by prasanthrangan** [comment]
hmmm... but why?

**Comment by kRHYME7** [comment]
Oh, accidentally removed that echo command. 

Honestly, I do not know why their  zsh is located in /sbin/zsh instead of ``` /usr/bin/zsh ``` . I only knew that ``` chsh ``` works by reading ``` /etc/shells ```. 

Now I am realizing that this is not a good Idea. instead of this PR we should resolve on why their $(which zsh) returns the ``` /sbin/zsh ``` path

**Comment by prasanthrangan** [comment]
but `/usr/bin/zsh` should be added by default when `zsh` is installed, it should not be `/sbin/zsh`.

**Comment by kRHYME7** [comment]
True, Dunno why ``` which zsh ```  gives /sbin/zsh. I am assuming the Error on this Issue #896

**Pull request closed without merging**
