### PR TITLE
Kitty tab bar style

### PR DESCRIPTION
**Pull request by RAprogramm**
# Pull Request

## Description

Colors from waybar exports to kitty theme conf and auto reload when changing theme or wallpaper

## Type of change

Please put an `x` in the boxes that apply:

- [x] **New feature** (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by RAprogramm** [comment]
after updating dyprdots 2 days ago, perhaps, was added kitty terminal wallbash script.
it little bit broke my idea...now active and inactive tab bar background - the same...
when i did this PR kitty background has permanent color, so it was good colored separated inactive and active tabs, because active tab was the same with kitty background.
and idea was that kitty tab bar will be the same as waybar

**Comment by kRHYME7** [comment]
@RAprogramm  

I think you can modify it here? if not you can  comment out this lines. 
image

**Comment by RAprogramm** [comment]
> @RAprogramm  
> 
> I think you can modify it here? if not you can  comment out this lines. 
> image
> 
> 

Oh, thank you!
in fact, changing the terminal background is not bad, now I’m thinking, maybe I should change something?

**Comment by prasanthrangan** [comment]
Cool thanks, let me try to rewrite this, as modifying `themeselect.sh` `themeswitch.sh` `swwwallbash.sh` 
`wallbashtoggle.sh` are not necessary as they are already chained together, so this can be done just in `wallbashkitty.sh` as it will be the last script executed in the chain.

**Pull request closed without merging**
