### PR TITLE
Updated gpuinfo.sh / amdgpu.py / sddmwall.sh - Dynamic sync sddm login screen

### PR DESCRIPTION
**Pull request by T-Crypt**
I added:

python-pyamdgpuinfo to custom_hypr.lst 

so that way the function in the script would basically skip the install section but wanted it just to verify it is installed.

### CODE REVIEW

**Comment by T-Crypt** [comment]
Update: I have added the icons for the Utilization, Power Usage, and Clock Speed 

269930545-e793f661-315a-4fea-8324-268c6cc7bd18

**Comment by prasanthrangan** [comment]
hi, sorry i'm not keeping up with the progress on this, looks like you are still updating this?!? so let me know when its ready to merge.

**Comment by T-Crypt** [comment]
Just waiting for someone to test the output on the new script to verify it does grab the package temp of the intel cores. 

Looks like I have a conflict with the custom_hypr.lst by adding 'python-pyamdgpuinfo'

**Comment by T-Crypt** [comment]
@prasanthrangan This is ready to merge now!

**Review by prasanthrangan — APPROVED** [review]
looks good, thank you so much for your time and effort on this!

**Pull request merged**
