### PR TITLE
Waybar Network Module Styles 

### PR DESCRIPTION
**Pull request by RAprogramm**
# Pull Request

## Description

New waybar network module style.
Now by default only icon (for economy space).
Tooltip with full network information.
Alt view with upload and download speed.
NerdFontIcons

## Screenshots

240123_08h45m30s_screenshot
240123_08h46m22s_screenshot
240123_08h47m00s_screenshot

### CODE REVIEW

**Comment by kRHYME7** [comment]
Wow!

https://archlinux.org/packages/extra/any/ttf-jetbrains-mono-nerd/
Is this a dependency yet?

**Comment by RAprogramm** [comment]
> Wow!
> 
> https://archlinux.org/packages/extra/any/ttf-jetbrains-mono-nerd/
> Is this a dependency yet? 
> 

I got icons from https://www.nerdfonts.com/cheat-sheet.
I think any nerd font must be installed.

**Comment by kRHYME7** [comment]
Got my fonts from there too. 

Thanks for confirming this. Got confused by why some of my custom icons won't show correctly without the ttf-jetbrains-mono-nerd package. 🍻

**Review by prasanthrangan — APPROVED** [review]
Nice, thanks!
only concern I have is that the alt format with up/down bandwidth has static colors, so based on the wallpaper when the waybar bg change, it might be unreadable.
But thats not the default format, so its fine I guess :)

**Pull request merged**
