### PR TITLE
New Feature :  'keybind  hyprpicker + auto copy hex'

### PR DESCRIPTION
**Pull request by WasATrueWarriror**
# Pull Request

- [x ] **New feature** (non-breaking change which adds functionality)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by rubiin — APPROVED** [review]
LGTM

**Comment by kRHYME7** [comment]
image
 
 Can you review if we are not using this. (I guess this is my custom? )

**Comment by rubiin** [comment]
Ya, That id your custom

**Review by kRHYME7 — CHANGES_REQUESTED** [review]
image
 
 
 Should be fine
 
 but can you please make this to `bindd ` format 
 ` bindd = $mainMod+Shift, P,Color Picker , exec, hyprpicker -a # Pick color (Hex) >> clipboard#  `

**Review by rubiin — APPROVED** [review]

**Review by kRHYME7 — APPROVED** [review]

**Pull request merged**
