### PR TITLE
feat: Add cpuinfo module to waybar

### PR DESCRIPTION
**Pull request by mislah**
# Pull Request

Added a CPU info module to display CPU temperature similar to that of existing GPU info module. The tooltip shows CPU name, temperature, utilization and clock speed. 

The temperature, utilization icons are animated and changes according to the value of CPU temperature and utilization.

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

Trust me, the icons and emojis change on temperature and utilization.

b

## Note

I don't like people editing my comments, I'll cry :-/

### CODE REVIEW

**Review by prasanthrangan — APPROVED** [review]
Cool thanks! any impact on cpu for this? as the script runs every 5 mins, please make sure it has no impact.
Also any reason using arrays and awk to read a key pair value instead of a simple case or json format?

**Comment by mislah** [comment]
Why strings instead of arrays? it feels more concise than associative arrays.

Why loop instead of case? input conciseness, re-usability and it is easier to scale.

Why awk? The utilization percentage is float, it is hard to compare using posix operators.

Fixes? As precision is not significant, remove the decimal part

Any impact on performance? hell yeah

image


I'll create a PR after optimizing them :-)

**Comment by prasanthrangan** [comment]
> Why strings instead of arrays? it feels more concise than associative arrays.
> 
> Why loop instead of case? input conciseness, re-usability and it is easier to scale.
> 
> Why awk? The utilization percentage is float, it is hard to compare using posix operators.
> 
> Fixes? As precision is not significant, remove the decimal part

I think this can be simplified just by using json, so no worries I'll do a quick rewrite.

**Comment by mislah** [comment]
> I think this can be simplified just by using json, so no worries I'll do a quick rewrite.

I have tested your revision `d.sh` (22.3ms), it is 37% faster than the original version `c.sh` (30.5ms).

image

I have also tested the original version after minimizing the forks `b.sh` and it turns out to run on 6.58ms (364% faster than original and 238% faster than the revised) .  I also tested possibly the minimal version `a.sh` which contains only if branches completed in 5.4ms.

image

I'm thinking of creating a PR with `b.sh` after further minimizing the forks. `a.sh` is a good alternative, but I would prefer `b.sh` as it follows the Object Oriented principles and the performance difference is only minimal.

#### Test Script:
`python -m timeit -n 10 -s 'import subprocess' "subprocess.call('./test.sh', shell=True)"`
The `python timeit` is not absolute but is highly precise and useful for comparison. I think `strace` or `time` gives more accurate results but are not statistical or precise.


Waiting for your reply :-)

**Pull request merged**
