### PR TITLE
feat :lipstick: Waybar weather plugin

### PR DESCRIPTION
**Pull request by kevinwaxi**
Minor weather plugin optional with tooltip using "https://Wttr.in"

# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added the necessary comments/documentation to my code.
- [x] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by dieBakterie** [comment]
Will this be added to hyde?

**Comment by abenezerw** [comment]
It works as long as you install the dependency 
pacman -S python-requests
image

**Review by abenezerw — APPROVED** [review]
image
It works as long as dependency
pacman -S python-requests is installed

**Comment by rubiin** [comment]
python-requests  should also be added to app list to install during install if this was ti merge

**Review by fcoelhomrc — COMMENTED** [review]
This implementation [comes from this repo](https://gist.github.com/bjesus/f8db49e1434433f78e5200dc403d58a3)
However, as cited there, there is a [better, actively maintained rust alternative](https://github.com/bjesus/wttrbar) (which from my own experience, works better)

Should we reconsider this PR and instead implement the feature with that alternative package?
[Dependencies would be this AUR package](https://aur.archlinux.org/packages/wttrbar)

**Comment by T-Crypt** [comment]
Please fix conflicts and explore wttrbar (which is better rust implementation)

**Pull request closed without merging**
