### PR TITLE
feat: add keybinding for move to special workspace

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

add keybinding for move to special workspace
keeping the pattern similar to how active window is moved with other numbered workspace

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ ] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
Dunno but this one is my key bind for screenshots lol. I don't know why it's familiar to me.

**Comment by zeerayne** [comment]
Likely because this is default keybinding for Windows snipping tool

**Comment by rubiin** [comment]
you can override anyway :D just keeping the semantics

**Comment by XBEAST1** [comment]
> you can override anyway :D just keeping the semantics

same here i'm also using Win+shift+S to move window to special workspace since last 2 months

**Comment by rubiin** [comment]
> > you can override anyway :D just keeping the semantics
> 
> same here i'm also using Win+shift+S to move window to special workspace since last 2 months

Yeah I have just added special workspace to my daily workflow. I was using a numbered workspace as a scratch pad but since special workspace was kind of built for this specific purpose , switched to using it.

**Comment by sitolam** [comment]
I use $MainMod + M, because I like to use the special workspaces as a minimizing feature (so that's why it's an M)

**Pull request closed without merging**
