### PR TITLE
[Ready] Gamelaunch with lutris integration

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

## Description

+ Nothing Change for steam
+ If lutris is installed lutris library will show
+  command with  "steam" flag will show steam lib (Only )

Discussions here:
https://github.com/prasanthrangan/hyprdots/issues/866
Script is inspired from @Enigma1309  https://github.com/prasanthrangan/hyprdots/issues/866#issuecomment-1973045668

~Additional feature for the Mode 5. This is to ensure the image is fitted to the monitor therefore this is cached per monitor. 
image~
Different PR will suit this

### CODE REVIEW

**Comment by zer0cha0s** [comment]
image
Tested and works for me. Battle.net, Epic Games and Pokemon Crystal are from Lutris the rest are from my steam library.

**Comment by kRHYME7** [comment]
@Enigma1309 Sorry for that.  I remembered you tested first the version on the gist right? Maybe there is a conflict with it.   
  These are the files   inside ``` ~/.config/rofi/assets ``` 

image

Can you remove all of these first and give it another try? I'm really sorry for the inconvenience. 

Here's the original file it will be backup, pefixed with "bak". 

```
 cp ~/Hyprdots/Configs/.config/rofi/assets/steamdeck_holographic.png ~/.config/rofi/assets/   

```

**Comment by Enigma1309** [comment]
image
file with _bak on left   and  file with no _bak on right

there's an height difference i guess

**Comment by kRHYME7** [comment]
How about the file with the screen resolution? Still broken ?

image

**Comment by kRHYME7** [comment]
NVM decided to have a separate PR for this after lutris is merged.

**Comment by kRHYME7** [comment]
@zer0cha0s  Wow! what did you modify to achieve it?

**Comment by zer0cha0s** [comment]
> @zer0cha0s Wow! what did you modify to achieve it?

Just copied your latest code, removed those extra assets you mentioned above and ran  
`cp ~/Hyprdots/Configs/.config/rofi/assets/steamdeck_holographic.png ~/.config/rofi/assets/ `
Have not done anything else other than that.

**Comment by kRHYME7** [comment]
Ow okay, thank you. 

Sorry to bother you much but what are the output of these commands

```
grep "convert" ~/.config/hypr/scripts/gamelauncher.sh  
```


```
 ls -a ~/.config/rofi/assets/
```

: I recently removed the block that dynamically change the holographic image, as I think it is better to be pushed on a separate PR. 

Also, should  I modify the script if lutris is installed via flatpak?

**Comment by kRHYME7** [comment]
Thank you! I'll add an option for flatpak too.

**Comment by kRHYME7** [comment]
UPDATE for Lutris gamelauncher:

> #TODO Only call this if new apps are installed...

Almost done HOWEVER:

+ we would wait around 4 seconds to generate the list  (the list is the metadata and is stored into a temp file)
+ If you want to make it faster we can do two things 
1. Save it as a temp file, then requires reboot/ or removal of the tempfile to regenerate it again (we can add a flag like ``` --refresh ``` to remove the tempfile)
2  We should save a hash of a certain dir/file then if the hash is change then regenerate the temp file. This one is nice but I don't know what certain dir/file we can check to see if has been modified (A game is installed / deleted )
3. We can check the time between the temp file and the current file if it is created example: 3 hours ago then regenerate (sounds dumb)


Please test this version

**Comment by Enigma1309** [comment]
It works :D

i don't think we need to increase performance rather we can show an notification that the game-launcher is launching (like we have when toggling wallbash) , it won't take much time after-all.

**Comment by kRHYME7** [comment]
I Added notifs too 

image

image

**Review by prasanthrangan — APPROVED** [review]
works for steam library but i've not tried lutris...
So I'll merge this for now and try to optimize later as its a bit slow.

**Pull request merged**
