### PR TITLE
Update custom_hypr.lst

### PR DESCRIPTION
**Pull request by akashgagda**
fixing grimblast skipping issue while installing arch

### CODE REVIEW

**Comment by T-Crypt** [comment]
Grimblast gets installed already on the custom_hypr.lst -- No need to add the grimblast-git

231018_09h56m51s_screenshot

**Comment by akashgagda** [comment]
i think there is only grimblast-git package not a grimblast

**Comment by kRHYME7** [comment]
But actually I installed this dots lately on my system but the script did not installed grimblast.

**Comment by akashgagda** [comment]
> But actually I installed this dots lately on my system but the script did not installed grimblast. 

Same for me it says package not found something

**Comment by T-Crypt** [comment]
Let me uninstall and test today, it should still locate the package with `grimblast` but we can update if my test doesn't install it.

**Comment by kRHYME7** [comment]
gonna try also on my other machine

**Comment by kRHYME7** [comment]
In my case, I can vouch that it skips the grimblast and only recognizes grimblast-git. 
Thanks

**Review by prasanthrangan — APPROVED** [review]
Thank you bro, for the fix!

**Pull request merged**
