### PR TITLE
Fancy System update

### PR DESCRIPTION
**Pull request by kRHYME7**
+ Fullscreen the systemupdate.sh because we Are using Arch BTW :laughing:
+ Don't show an icon with 0 on the waybar, Display Icon only   /Display icon if an Update is available.
+ Prompts only on what type of Update Category is needed: Official, AUR, Flatpak
+ Prevent multiple Process
+ Interactive Update  > because we're using Arch BTW :laughing:
 
**- NEVER TESTED ON REAL  UPDATES**

Please Simplify this script if you're interested

image

image

image

### CODE REVIEW

**Comment by prasanthrangan** [comment]
> * Fullscreen the systemupdate because we Are using arch BTW 😆
> 
> * Don't show icon with 0 on waybar , Display only  if Update is available.
> 
> * I can remove the lolcat if we don't need it.

Hi, Thanks for update...
I think it will be better without lolcat :)
and using the same ascii fonts from install script!
also, any reason to kill waybar, should the waybar icon update itself??

**Comment by kRHYME7** [comment]
I really would like to ask what Ascii you are using.

The Icon will be reloaded the next day according to the module, because  the module uses the Variables from the script. I guess


BTW I think I will continue working for this next week, I broke my System at the moment.

**Comment by prasanthrangan** [comment]
Hey no worries, take your time!

here is the ascii font generator -
https://patorjk.com/software/taag/#p=display&f=Rectangles&t=System%20Update
                                                          
```
 _____         _                _____       _     _       
|   __|_ _ ___| |_ ___ _____   |  |  |___ _| |___| |_ ___ 
|__   | | |_ -|  _| -_|     |  |  |  | . | . | .'|  _| -_|
|_____|_  |___|_| |___|_|_|_|  |_____|  _|___|__,|_| |___|
      |___|                          |_|                  
```
Font Name: Rectangles

**Comment by prasanthrangan** [comment]
Hi, looks like there is a conflict!

**Comment by kRHYME7** [comment]
Thanks!

**Comment by kRHYME7** [comment]
Gonna close this for a moment.

**Pull request closed without merging**
