### PR TITLE
chore(vscode): update theme extensions

### PR DESCRIPTION
**Pull request by devCKVargas**
Catppuccin 3.4.0 ➡️ 3.6.0
GruvBox-Retro 1.11.0 ➡️ 1.17.0

### CODE REVIEW

**Comment by T-Crypt** [comment]
@devCKVargas -- On these updates, are you making sure to modify the root package.json for the theme name?

**Comment by devCKVargas** [comment]
> @devCKVargas -- On these updates, are you making sure to modify the root package.json for the theme name?

I forgot, my bad. I'm gonna fix it later.

**Comment by devCKVargas** [comment]
This should be fixed now. Thanks again @T-Crypt !

**Comment by prasanthrangan** [comment]
Hi @devCKVargas , the theme names does not seem to be updated -

image


anyways this was just a workaround to get vscode to sync themes... so my idea was to fork the original theme files and consolidate it as a single vscode theme package or extension, so that the updates wont break it... please refer #299

**Comment by devCKVargas** [comment]
It seems that GitHub didn't register the forced push I did a few of days ago. Well, I've re-pushed it. Kindly review if it's properly named now. Thanks!

**Review by prasanthrangan — APPROVED** [review]
great, thanks for updating it!
I'll test it out...

**Pull request merged**
