### PR TITLE
improved waybar cava

### PR DESCRIPTION
**Pull request by keth-real**
Customization capability for waybar cava

# Custom overrides: 

custom
image

standbymode = 0 : clean (default) 
image
standbymode = 1 : blank space
image
standbymode = 2 : full bar preview
image
standbymode = 3 : low -est bar will be displayed
image

# CLI  

image

when set 
width: 
image
range (It isn't good to touch this though, It helps to fine-tune if user wants to add more bar chararacters  )
 image

# Other changes

* Disowns the parent shell so that we can strip off some memory 
* --restart just kills the cava instance then the waybar revives it after 1 second. 
* Added sleep for Cava for better power saving mode when nothing is playing then sed do not write anything

2 monitors so 2 instance 
image
cava sleeping
image
I can't capture it but if Cava is in idle mode it fetches for input every second hence in average it uses 1.2% peak when reading at 100ms and 0.2% peak when reading at 1000ms 
per cava instance which is super low and is efficient
image

# Fixes 
* Waybar cava gets killed by another instance of the script, this fixes it. 

# TODO

* Try to use a single instance of cava and recycle the output.

### CODE REVIEW

**Review by kRHYME7 — APPROVED** [review]
used it for a week and works fine

**Comment by kRHYME7** [comment]
Tried it for a week and looks good

https://github.com/user-attachments/assets/700b2a4c-e590-4d48-934d-826e140d8249

**Comment by sitolam** [comment]
There should be a delay when the module disappears because sometimes it disappears constantly in certain songs because the music stops a little bit.

**Comment by kRHYME7** [comment]
I guess you can use `  standbymode = 1 : blank space ` ? 
image

image

This will allocate a space if no audio is detected

**Comment by kRHYME7** [comment]
Have you try to reload it?

waybar_cava.sh --reset

**Comment by sitolam** [comment]
> waybar_cava.sh --reset

Yeah no that doesn't help

**Comment by kRHYME7** [comment]
Try to use 3 instead

**Pull request merged**
