### PR TITLE
Trigger swaylock when close laptop lid, adjust OBS shortcut and add alt+f4 shortcut...

### PR DESCRIPTION
**Pull request by T3l3sc0p3**
Hi there! I just implemented a new feature that trigger swaylock in whenever we close the laptop lid
I noticed that swaylock wasn't activating when the laptop lid was closed, which could be a potential security risk. So, I added this feature to enhance the security aspect
I've personally tested this on my laptop, and it's working as intended. However, you should double check to ensure everything's functioning seamlessly ✅ 
This feature won't affect desktop computers since they don't have a lid to close, you know =)))

In addition, I've made a small adjustment to the OBS opening shortcut. Instead of using Ctrl + Shift + P, which could clash with the Firefox private browsing tab shortcut, I've opted for Ctrl + Alt + Shift + R. This shortcut is commonly used in Linux for recording screen

Lastly, I've added the keyboard shortcut Alt + F4 for closing the window. When I first started using your dotfile, finding the window close shortcut was a bit challenging. This new shortcut will definitely make it more accessible, especially for newcomers to the dotfile

Also, I made some changes to the comment to capitalize the first letter and adjust some stuff to make it look better

### CODE REVIEW

**Review by stove-jeebs — COMMENTED** [review]
I imagine that in most cases, people close their laptop lids either to carry them around or when they'll be away for an extended period (otherwise they could have just locked the screen instead). In such scenarios, suspending the processes to save power might be a more practical solution than turning off the monitor. Just my 2¢

**Comment by stove-jeebs** [comment]
The only line you need is `bindl=,switch:on:Lid Switch,exec,swaylock && systemctl suspend`

**Comment by T3l3sc0p3** [comment]
@stove-jeebs Thanks, I will adjust it!

**Comment by stove-jeebs** [comment]
oh also, can you put this line in the `userprefs.conf`? It turns off the monitor after 20 mins and suspends after 30mins of inactivity. I'm too lazy to make another pull request XD

```bash
swayidle -w \
  timeout 1200 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
  timeout 1800 'systemctl suspend'
```

**Comment by prasanthrangan** [comment]
Hi, Thanks for the update!
can we keep `swayidle` in hyprland.conf commented out by default, so users can enable it if required.
As `swayidle` cause some systems to crash (i've also faced few crashes) and does not resume the system :(

**Comment by T3l3sc0p3** [comment]
@prasanthrangan I just keep swayidle in hyprland.conf commented out as you said 👍🏼

**Review by prasanthrangan — APPROVED** [review]
great, thanks for the help!

**Comment by mahaveergurjar** [comment]
> oh also, can you replace this code with line 42 in the `hyprland.conf`? It turns off the monitor after 20 mins and suspends after 30mins of inactivity. I'm too lazy to make another pull request XD
> 
> ```shell
> swayidle -w \
>   timeout 1200 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
>   timeout 1800 'systemctl suspend'
> ```

I set this command but not working 

`exec-once = swayidle -w \
  timeout 60 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
  timeout 300 'swaylock' \
  timeout 1800 'systemctl suspend'`

**Comment by mahaveergurjar** [comment]
> oh also, can you replace this code with line 42 in the `hyprland.conf`? It turns off the monitor after 20 mins and suspends after 30mins of inactivity. I'm too lazy to make another pull request XD
> 
> ```shell
> swayidle -w \
>   timeout 1200 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
>   timeout 1800 'systemctl suspend'
> ```

Can you tell me how to disable the screen off when see YouTube videos and movies  any command to set it that automatically disable in video screen off feature

**Comment by stove-jeebs** [comment]
@mahaveergurjar set it to `exec-once = swayidle -w timeout 10 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 20 'systemctl suspend'`. For your second question, you'll need to implement the idle inhibitor for waybar

**Comment by Muhammad-Abubakr** [comment]
> @mahaveergurjar set it to `exec-once = swayidle -w timeout 10 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 20 'systemctl suspend'`. For your second question, you'll need to implement the idle inhibitor for waybar

This command didn't work for me very well. However, I found one from Arch Wiki intended for Sway but I have modified it for hyprland `swayidle -w timeout 300 'swaylock -f' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep 'swaylock -f'`, however I am still facing an issue of systemctl suspend asking for authentication. If someone uses this, they can also append `timeout 900 'systemctl suspend'` at the end.

**Comment by vampirepapi** [comment]
> Hi, Thanks for the update! can we keep `swayidle` in hyprland.conf commented out by default, so users can enable it if required. As `swayidle` cause some systems to crash (i've also faced few crashes) and does not resume the system :(

When I close the lid, the system automatically suspends and locks. However, after opening the lid, swaylock crashes. How can I change this behavior? I want the laptop display to turn off when I close the lid, but the monitor output to remain on.

**Pull request merged**
