### PR TITLE
Waybar added in Windowrules

### PR DESCRIPTION
**Pull request by mahaveergurjar**
# Pull Request

## Description
Add layerrule = blur,waybar in windowrules and remove from themes
Show its easy if make app for this config so 0 1 and used for on off the waybar blur 

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [x] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [x] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by dieBakterie** [comment]
You need to update the scripts too when you change the wallbash mode its in the file again.

**Comment by kRHYME7** [comment]
hey this is theme specific. some themes do need to have a solid look or just transparent. This one is forcing all to have a blurred effect.

**Comment by dieBakterie** [comment]
> hey this is theme specific. some themes do need to have a solid look or just transparent. This one is forcing all to have a blurred effect.

Actually it just blurs waybar nothing else, all other, like rofi, notifications etc are set in the windowrules.conf or do you meant the it needs to be changed in the .theme files?

**Comment by kRHYME7** [comment]
I mean It will blur the waybar globally  without respecting the theme. So if we set up a theme even if we make it xray or transparent the blur will ALWAYS be present. There's a reason why waybar blur is not there in the first place.

**Comment by dieBakterie** [comment]
> I mean It will blur the waybar globally without respecting the theme. So if we set up a theme even if we make it xray or transparent the blur will ALWAYS be present. There's a reason why waybar blur is not there in the first place.
> 
> Also this change is useless as theme.conf is dynamically changed according to the specific theme. So changing themes will bring it back. then setting it somewhere will just duplicate the blur setting forcing it across all themes.

Yeah i know but i don't like the blur for waybar cause it's from the left to the right and and an block while the bar has rounded corners... I've removed the layerrule from the hyde.theme files.

**Comment by mahaveergurjar** [comment]
> blurred

Yeah know some theme waybar blur or some theme waybar not blur but its easy for user that need waybar blur or not its easy to change from only when file

**Comment by dieBakterie** [comment]
Yeah i got it from the beginning

**Comment by mahaveergurjar** [comment]
And most of the user are ask me how to unblur the waybar one more @kRHYME7 Idea can  you make waybar are in hyde.conf waybar blur unblur extract from theme and set 0 1 for unblur blur???

**Comment by dieBakterie** [comment]
That's what `userprefs.conf` is for.

**Comment by kRHYME7** [comment]
you can just do it all in the ./userprefs.conf 

```
layerrule = unset,waybar
layerrule = blur,waybar
``
tbf we can just override it. Themes are static, so it won't be efficient to changed it in each theme. windowsrules.conf is dynamic in a sense that it can be overwritten across updates. 

But there are themes that look great with waybar blur som looks ugly. So if users want to override any setting, just do it on ./userprefs.conf.

**Comment by mahaveergurjar** [comment]
ok so i close this pr

**Comment by kRHYME7** [comment]
Yeah, 
This is the magic:  ` layerrule = unset,waybar `  then do any mods later this line. That's why hyprland is awesome! (never use any WM before though HAHAHA )

**Pull request closed without merging**
