### PR TITLE
fix: Fixed vs-code flags not applying

### PR DESCRIPTION
**Pull request by ryancelio**
# Pull Request

## Description

Removed spaces before the flags on "code-flags.conf" that made the flags not apply and open them as files

## Type of change

Please put an `x` in the boxes that apply:

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [X] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [X] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [X] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kRHYME7** [comment]
> Removed spaces before the flags on "code-flags.conf" that made the flags not apply and open them as files

Wow, for real? can you do this for the other flags too

**Comment by ryancelio** [comment]
> > Removed spaces before the flags on "code-flags.conf" that made the flags not apply and open them as files
> 
> Wow, for real? can you do this for the other flags too

Sure! Other than the vscode flags, I only found the Spotify one, would that be all?

**Review by rubiin — APPROVED** [review]

**Comment by rubiin** [comment]
spotify is covered here https://github.com/prasanthrangan/hyprdots/pull/1844

**Comment by rubiin** [comment]
@kRHYME7 these can be merged

**Review by kRHYME7 — APPROVED** [review]
Thank You!

**Pull request merged**
