### PR TITLE
Theme - Gruvbox Retro 

### PR DESCRIPTION
**Pull request by T-Crypt**
Added:

- GTK Theme - Gruvbox Retro
- Kitty theme - Gruvbox Themed 
- Gruvbox Retro Icons
- Gruvbox Cursor Pack -- Set gtk cursor-theme 'Gruvbox Retro' although the main cursor overrides unless hyprctl setcursor [theme] [size]
- VScode Gruvbox themes - Updated extensions json -- Repackaged 
- Kvantum Theme - Gruvbox Retro 
- Swww wallpapers added 
- Rofi Theme added 
- Waybar theme added 
- qt5ct colors added 
- Hypr Theme added -- added cursor-theme gnome setting 

Maybe a few tweaks needed that I overlooked? Although it seems more put together than my Frosted-Glass theme. Really liking this one 

231004_16h48m54s_screenshot

231004_16h48m13s_screenshot

231004_15h14m34s_screenshot

231003_16h45m12s_screenshot

### CODE REVIEW

**Comment by kRHYME7** [comment]
Wow!

**Comment by T-Crypt** [comment]
@kRHYME7 

Would you want to test this before we merge to Tittu's branch? Its updated in my main branch on my repo!

**Comment by kRHYME7** [comment]
Sure! But it's midnight here, maybe tomorrow. It looks really awesome 😎.

**Comment by T-Crypt** [comment]
Updated -- Corresponding waybar / rofi colors :)

231005_10h28m56s_screenshot

231005_10h28m35s_screenshot

231005_10h31m19s_screenshot

**Comment by kRHYME7** [comment]
Hello I have tried your main repo already @T-Crypt .
I want to say that the theme rocks! Might as well use this  theme at night. 
The icons, paddings,borders looks great!

Due to having hidpi monitor I get some scaling issues but can be easily managed(not related to Theme - Gruvbox).

231006_10h25m24s_screenshot
231006_10h26m29s_screenshot

Icons on some apps won't display

231006_17h33m40s_screenshot


Some issues on the cursor also maybe hyprland related

231006_17h31m33s_screenshot
231006_17h29m04s_screenshot
231006_17h29m18s_screenshot
231006_17h30m41s_screenshot
231006_17h31m00s_screenshot
231006_17h31m33s_screenshot



All in all I'll probably use this theme frequently. Thanks !

**Review by prasanthrangan — APPROVED** [review]
Alright, this looks sooo cool! Thanks for your time and effort!

**Comment by prasanthrangan** [comment]
Also thank you very much @kRHYME7, for taking your time to test this!

**Comment by T-Crypt** [comment]
I modified the extensions.json to include the Gruvbox-Retro and modified the package.json and the .json for gruvbox-medium-dark to rename to Gruvbox-Retro.

I would just verify and repackage the extensions on your system to ensure consistency on that end

**Comment by prasanthrangan** [comment]
> I modified the extensions.json to include the Gruvbox-Retro and modified the package.json and the .json for gruvbox-medium-dark to rename to Gruvbox-Retro.
> 
> I would just verify and repackage the extensions on your system to ensure consistency on that end

sure, no worries.. I'll check the Gruvbox-Retro extension!

**Comment by prasanthrangan** [comment]
> Due to having hidpi monitor I get some scaling issues

@kRHYME7, scaling for wlogout seems messed up, whats your monitor resolution and scale?

**Comment by kRHYME7** [comment]
@prasanthrangan  
Reso: 3000x2000
Scale: 2

#284 
We needed a way to read monitors resolution and maintains the configs' scaling the same.

These lines reads the resolution
```
# detect monitor y res
#x_mon=$( cat /sys/class/drm/*/modes | head -1  ) 
#y_mon=$( echo $x_mon | cut -d 'x' -f 2 )
#x_mon=$( echo $x_mon | cut -d 'x' -f 1 )
```
echo
```
echo $y_mon
echo $x_mon
2000
3000
````


I manage to modify this and  reads the active monitor (scaling and resolution) only
Works best for multi-monitor
```
active_monitor=$(hyprctl monitors | awk -v RS="" -v ORS="\n\n" '/focused: yes/'| awk '/ID/{print $2} ')
res_inf=$(hyprctl monitors | awk -v RS="" -v ORS="\n\n" '/focused: yes/'| awk -F "@" '/@/ && / at /{print $1} ')
x_mon=$(echo $res_inf | cut -d 'x' -f 1)
y_mon=$(echo $res_inf | cut -d 'x' -f 2)
scl_inf=$(hyprctl monitors | awk -v RS="" -v ORS="\n\n" '/focused: yes/'| awk -F ": " '/scale/ {print $2} ')
x_mon=$(echo "$x_mon / $scl_inf" | bc -l | awk -F "." '{print $1}' )
y_mon=$(echo "$y_mon / $scl_inf" | bc -l | awk -F "." '{print $1}' )
```
output
``` 
echo "xmon $x_mon"
echo "ymon $y_mon"
xmon 1500
ymon 1000
```

This solve all of the scaling issue, jut dividing the resolution by scale
Should I PR this? 

I really love this repo, thank  for the time and effort too!

**Comment by prasanthrangan** [comment]
> This solve all of the scaling issue, jut dividing the resolution by scale
> Should I PR this?

It was based on default scale `1`, so ya dividing it by scale factor should fix it...
Sure, please feel free to commit the fix!

**Pull request merged**
