### PR TITLE
[Hyprland v0.3.6] Syntax adjustments

### PR DESCRIPTION
**Pull request by kRHYME7**
Configuration Adjustments for next release.

### CODE REVIEW

**Comment by prasanthrangan** [comment]
cool, I'll merge this when hyprland is updated in arch repo.

**Review by psilvaricardo — APPROVED** [review]
This is working well on my PC

**Comment by kRHYME7** [comment]
LOL arch did not updated hyprland yet Haha

**Comment by legendboyAni** [comment]
> cool, I'll merge this when hyprland is updated in arch repo.

switch to git version of hyprland, this will make your script work in more distro

**Comment by kRHYME7** [comment]
> switch to git version of hyprland, this will make your script work in more distro

Some time ago -git always gives issues. So owner decided to follow the stable release. 

BTW we can merge this now https://archlinux.org/packages/extra/x86_64/hyprland/

**Review by prasanthrangan — APPROVED** [review]

**Pull request merged**
