### PR TITLE
Add selection for screenlock Like for shell

### PR DESCRIPTION
**Pull request by dieBakterie**
# Pull Request

## Description

- Added posibility to select screenlock like for shell

## Type of change

- [x] **New feature** (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] I have added necessary comments/documentation to my code.
- [x] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.

## Additional context

Adds the posibility to select the screenlock and Install the packages depending what selected like for the Shell, zsh and Fish and their dependencies/packages.

### CODE REVIEW

**Comment by rubiin** [comment]
screenshot maybe ?

**Comment by dieBakterie** [comment]
> screenshot maybe ?

From what do you want screenshots?

**Comment by rubiin** [comment]
Added posibility to select screenlock like for shell, this one. It would be nice to see how that would look

**Comment by dieBakterie** [comment]
grafik
Sorry for the late reply it looks like this. i should remove the timer i guess and i need to update the PR so that it works

**Comment by rubiin** [comment]
Hope this gets merged so I could try out

**Comment by dieBakterie** [comment]
> Hope this gets merged so I could try out

It works on my end, don't sure how to handle -git or non git package

**Pull request closed without merging**
