### PR TITLE
fix: Dolphin background won't follow theme

### PR DESCRIPTION
**Pull request by SushiByte-beep**
Made background transparent in KDEglobals so it does not interfere with theming.

ps: Doing a PR using Cli turned out a lot more challenging then i expected.  If i did anything wrong, i am truly sorry.

# Pull Request

## Description

Made background transparent in KDEglobals so it does not interfere with theming.

More specificaly added this to .config/KDEglobals:
 `[Colors:View]
BackgroundNormal=#00000000` 

## Type of change

Please put an `x` in the boxes that apply:

- [x ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kRHYME7** [comment]
Can you also add this here. and remove it from the dolphinrc so it also can fix the ark bug.

```
[UiSettings]
ColorScheme=*
```

**Comment by SushiByte-beep** [comment]
I may try to make a new PR. Am i supposed to do so on the fixes branch or on main? 

I don't understand where these 290 other commits come from when i try to push on fixes...

**Comment by kRHYME7** [comment]
Maybe it's better to make a new PR. No pressure at all.

**Comment by SushiByte-beep** [comment]
#2016 Dolphin/KDE fix for themes 

And closing this one. Got there in the end :D

**Pull request closed without merging**
