### PR TITLE
feat(fastfetch): rounded corners

### PR DESCRIPTION
**Pull request by nnyyxxxx**
## Type of change

- [x] **New feature** (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kRHYME7** [comment]
Requires preview

**Comment by nnyyxxxx** [comment]
image

**Comment by nnyyxxxx** [comment]
dont mind the missing fonts

**Comment by rishav12s** [comment]
isnt the default good 

looks little wierd ngl

**Comment by nnyyxxxx** [comment]
huh, looks better to me

**Comment by rishav12s** [comment]
lol comes down to preference

maybe im used to previous straight corners

**Comment by rubiin** [comment]
i also think the current is better

**Comment by YuanziX** [comment]
same, i like the current one more.

**Pull request closed without merging**
