### PR TITLE
[Ready]  Support .gif files

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

## Description

~This is buggy/. Transitions on swww glitches the GIF. Can be fixed with
``` swww kill && swww init ``` but that would remove capability to have fancy transitions
 For now we can check is file is .gif then  gives flags or something to kill and initialize swww again or
 do not give transitions for .gif images(kill and init is faster than this ).~
 
> There should be a better solutions so I need some eyes here :

Solution: Instead of setting a symlink for the wallpaper use the real path 

* Sorry for always having an MR entry, it might be annoying. 

## Type of change

Please put an `x` in the boxes that apply:

- [x] **New feature** (non-breaking change which adds functionality)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [x] I have tested my code locally and it works as expected.

## Preview:
https://github.com/prasanthrangan/hyprdots/assets/53417443/f65fa17f-b12e-49ac-9611-e0e702765ff6

## CPU usage: 

https://github.com/prasanthrangan/hyprdots/assets/53417443/ea46cf9e-35f5-4b61-a74a-6122d7da7264

## Additional context

 Instead of setting a symlink for the wallpaper use the real path

### CODE REVIEW

**Comment by kRHYME7** [comment]
Preview:

https://github.com/prasanthrangan/hyprdots/assets/53417443/40d26b3f-bafe-4ce1-81a1-ad866631d2ba

**Comment by prasanthrangan** [comment]
Cool thanks, I'll test this out!

**Comment by kRHYME7** [comment]
@prasanthrangan  That's that's a privilege! As I am daily driving this I get peace of mind solving some bugs that I know I might encounter in the future. 

Caveats: Basically based on the .gif file size and frames. Once it is loaded ( takes up to 5 - 60 seconds). I am thinking if we should embed a function to always limt and downscale the gifs or should we just let the user downscale it on their own.  


 I know you're very familiar with swww, I will post this as reference. 
image


Based on my test
Longer and more frames takes more time to be cached around 20 seconds also takes up to 1 Gb ram. But this are mp4 converted to gif 

But for some cute/kawaii/anime gifs with shorter and lesser frame it took about 2 - 5 seconds.

**Comment by prasanthrangan** [comment]
Yeah I've tried using gifs with swww when I started with the wallpaper script, but it was very cpu intensive, when you generate the thumbnail (for frame 1) and set it as wallpaper. Not sure if it has improved now.

**Comment by kRHYME7** [comment]
It improves now on caching as it acts the same as all the other image types.(Also imagemagick tends to extract  all the frames giving me ``` wallpaper_name.gif.jpg[1 ++ ]  ```  multiple outputs )
  The major problem now as stated with swww is the there caching time of swww which we can't control. 

BTW I have a question, Is it feasible to have a single folder for all wallpaper cache? is it even worth it? or have you tried it ?  
The only benefit is that it is easy to add custom wallpapers without always mapping into the current theme folder.  Maybe I can ask queries privately in Discord? You can reply in your free time.  My discord: ``` khing0v0 ``` (dummy)

**Review by prasanthrangan — APPROVED** [review]
just tested this, works great now... thank you so much!

**Pull request merged**
