### PR TITLE
Waybar - Backlight Module

### PR DESCRIPTION
**Pull request by T-Crypt**
Feel free to change the position in config.ctl

231012_08h30m51s_screenshot

231012_08h31m14s_screenshot

### CODE REVIEW

**Comment by prasanthrangan** [comment]
Hi, There is a script contributed already for this i think...

Here you go - [brightnesscontrol](https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/scripts/brightnesscontrol.sh) 

both are similar, so its better to combine it.

**Comment by T-Crypt** [comment]
Added -- Material-Sakura vscode theme -- packaged from mydots so its correct. 

Updated -- Keybinding for other PR switch keyboard layout

**Comment by prasanthrangan** [comment]
> Added -- Material-Sakura vscode theme -- packaged from mydots so its correct.

It is already there in existing vscode package, so any change in it?

image

**Comment by T-Crypt** [comment]
> > Added -- Material-Sakura vscode theme -- packaged from mydots so its correct.
> 
> 
> 
> It is already there in existing vscode package, so any change in it?
> 
> 
> 
> image
> 
> 

It wasn't present on my dots after the latest update so I didn't think there was a theme for it. I can adjust my PR to have the current Code_Ext from the main branch.

**Comment by T-Crypt** [comment]
Updated -- I removed and re-added Code_Extensions from the main branch -- ready to merge.

**Review by prasanthrangan — APPROVED** [review]
great, thank you!

**Pull request merged**
