### PR TITLE
timeshift backup before system update

### PR DESCRIPTION
**Pull request by sanjyay**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots
240628_12h06m44s_screenshot
240628_12h15m31s_screenshot

## Additional context
Sometimes system update could break the system so system backup right before updating the system could come in handy

### CODE REVIEW

**Review by kRHYME7 — APPROVED** [review]
I have btrfs and has a hook to take snapshots while using pacman.  This PR is best for ext4 users.  Approved 👍 as long as time shift is not a dependency.

**Comment by sanjyay** [comment]
what do you mean by as long as time shift is not a dependency?. The code checks if timeshift is installed and if it isn't then it would just proceed to update the system without back up.

**Comment by kRHYME7** [comment]
> what do you mean by as long as time shift is not a dependency?. The code checks if timeshift is installed and if it isn't then it would just proceed to update the system without back up.

Yeah, I did reiterated and point it out for future contributors 🥂.

**Comment by sanjyay** [comment]
> > what do you mean by as long as time shift is not a dependency?. The code checks if timeshift is installed and if it isn't then it would just proceed to update the system without back up.
> 
> Yeah, I did reiterated and point it out for future contributors 🥂.

ohhkay 👍

**Pull request closed without merging**
