### PR TITLE
Hyprdots-CLI

### PR DESCRIPTION
**Pull request by kRHYME7**
I'll just add this here.

### CODE REVIEW

**Comment by prasanthrangan** [comment]
Hey @kRHYME7 , is this ready for merge?

**Comment by kRHYME7** [comment]
yup

**Comment by prasanthrangan** [comment]
Nice! not sure if we need to maintain both `hyprdots` and `hyprdots-ctl`, so if there is a change its easier to maintain one script instead of updating it in 2 different places. And also it becomes redundant.
your [hyprdots-ctl](https://github.com/kRHYME7/Hyprdots-ctl) repo looks good, so installing the package directly from AUR should be sufficient i guess??

**Comment by kRHYME7** [comment]
I see, If so I will Use the ``` Hyprdots ```package.  And for your convenience I will host the wiki for this package on the Hyprdots-ctl repo. I'll be grateful if you support me with this. 🙏

**Comment by prasanthrangan** [comment]
> I see, If so I will Use the `Hyprdots` package. And for your convenience I will host the wiki for this package on the Hyprdots-ctl repo. I'll be grateful if you support me with this. 🙏

yup sure, feel free to maintain the package and wiki in your repo!

**Comment by kRHYME7** [comment]
Gonna close this for now.

**Pull request closed without merging**
