### PR TITLE
feat(vscode): update theme extensions to latest

### PR DESCRIPTION
**Pull request by devCKVargas**
Catppuccin ➡️ v3.4.0
Gruv Box ➡️ v1.11.0
Rosé Pine ➡️ v2.9.0
Tokyo Night ➡️ v1.0.5

All works when charging Hyprdots theme.

### CODE REVIEW

**Comment by T-Crypt** [comment]
@devCKVargas 

You have an issue with your extensions.json file. Can you make sure to add this to archive on the system itself? Won't be able to merge this for now.

Should like like this

```json
[{"identifier":{"id":"decaycs.decay","uuid":"9227b3cc-d448-4011-a1e0-f4ad45837394"},"version":"1.0.9","location":{"$mid":1,"path":"/home/tindall/.vscode/extensions/decaycs.decay-1.0.9","scheme":"file"},"relativeLocation":"decaycs.decay-1.0.9","metadata":{"id":"9227b3cc-d448-4011-a1e0-f4ad45837394","publisherId":"df2fdfc2-e7b3-4b6f-937e-0d924c235bb8","publisherDisplayName":"decaycs","targetPlatform":"undefined","updated":false,"isPreReleaseVersion":false,"installedTimestamp":1688838491422,"preRelease":false}},{"identifier":{"id":"stepanvanzuriak.mono","uuid":"4df463a2-e3b5-4cc3-af8a-244691e54fdf"},"version":"0.0.1","location":{"$mid":1,"path":"/home/tindall/.vscode/extensions/stepanvanzuriak.mono-0.0.1","scheme":"file"},"relativeLocation":"stepanvanzuriak.mono-0.0.1","metadata":{"id":"4df463a2-e3b5-4cc3-af8a-244691e54fdf","publisherId":"8427be75-78e0-46bd-90b6-60d1cb476a01","publisherDisplayName":"Stepan Vanzuriak","targetPlatform":"undefined","updated":false,"isPreReleaseVersion":false,"installedTimestamp":1692377279247,"preRelease":false}},{"identifier":{"id":"jwsandeman.cyberpunk2077-theme","uuid":"0874834b-6b77-4319-952d-a6b3b8daeaf0"},"version":"1.4.3","location":{"$mid":1,"path":"/home/tindall/.vscode/extensions/jwsandeman.cyberpunk2077-theme-1.4.3","scheme":"file"},"relativeLocation":"jwsandeman.cyberpunk2077-theme-1.4.3","metadata":{"id":"0874834b-6b77-4319-952d-a6b3b8daeaf0","publisherId":"20e2fe8c-cb55-4500-8e21-a05f828f4937","publisherDisplayName":"JW Sandeman","targetPlatform":"undefined","updated":false,"isPreReleaseVersion":false,"installedTimestamp":1692443635992,"preRelease":false}},{"identifier":{"id":"msnilshartmann.blue-light","uuid":"3df7a5c3-e986-42b1-b9bd-11c19037a174"},"version":"0.6.4","location":{"$mid":1,"path":"/home/tindall/.vscode/extensions/msnilshartmann.blue-light-0.6.4","scheme":"file"},"relativeLocation":"msnilshartmann.blue-light-0.6.4","metadata":{"id":"3df7a5c3-e986-42b1-b9bd-11c19037a174","publisherId":"4d65f61a-f7c1-45e2-b943-b03dd22d5be1","publisherDisplayName":"Nils Hartmann","targetPlatform":"undefined","updated":false,"isPreReleaseVersion":false,"installedTimestamp":1693371572697,"preRelease":false}},{"identifier":{"id":"enkia.tokyo-night","uuid":"1cac7443-911e-48b9-8341-49f3880c288a"},"version":"1.0.3","location":{"$mid":1,"path":"/home/tindall/.vscode/extensions/enkia.tokyo-night-1.0.3","scheme":"file"},"relativeLocation":"enkia.tokyo-night-1.0.3","metadata":{"id":"1cac7443-911e-48b9-8341-49f3880c288a","publisherId":"745c7670-02e7-4a27-b662-e1b5719f2ba7","publisherDisplayName":"enkia","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1696434150318,"preRelease":false}},{"identifier":{"id":"mvllow.rose-pine","uuid":"6ef63bba-e6b8-4209-b562-9a927f36ae8f"},"version":"2.9.0","location":{"$mid":1,"path":"/home/tindall/.vscode/extensions/mvllow.rose-pine-2.9.0","scheme":"file"},"relativeLocation":"mvllow.rose-pine-2.9.0","metadata":{"id":"6ef63bba-e6b8-4209-b562-9a927f36ae8f","publisherId":"dbc69b63-e1da-4022-a0a6-25eee990a29c","publisherDisplayName":"Rosé Pine","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1696434151190,"preRelease":false}},{"identifier":{"id":"catppuccin.catppuccin-vsc","uuid":"69264e4d-cd3b-468a-8f2b-e69673c7d864"},"version":"3.3.0","location":{"$mid":1,"path":"/home/tindall/.vscode/extensions/catppuccin.catppuccin-vsc-3.3.0","scheme":"file"},"relativeLocation":"catppuccin.catppuccin-vsc-3.3.0","metadata":{"id":"69264e4d-cd3b-468a-8f2b-e69673c7d864","publisherId":"e7d2ed61-53e0-4dd4-afbe-f536c3bb4316","publisherDisplayName":"Catppuccin","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1696434152248,"preRelease":false}},{"identifier":{"id":"jdinhlife.gruvbox","uuid":"c6d564c4-ca8c-45ba-abf6-c85f2d1468d8"},"version":"1.8.0","location":{"$mid":1,"fsPath":"/home/tindall/.vscode/extensions/jdinhlife.gruvbox-1.8.0","external":"file:///home/tindall/.vscode/extensions/jdinhlife.gruvbox-1.8.0","path":"/home/tindall/.vscode/extensions/jdinhlife.gruvbox-1.8.0","scheme":"file"},"relativeLocation":"jdinhlife.gruvbox-1.8.0","metadata":{"id":"c6d564c4-ca8c-45ba-abf6-c85f2d1468d8","publisherId":"571210a8-f372-43c2-8b5a-018868d4ac96","publisherDisplayName":"jdinhlife","targetPlatform":"undefined","updated":false,"isPreReleaseVersion":false,"installedTimestamp":1696602656324,"preRelease":false}}]
```

**Comment by T-Crypt** [comment]
Also looks like the package.json is corrupted for the themes itself? Not sure what is causing this but they are unable to import 

image

Screenshot 2023-10-25 082445

**Comment by T-Crypt** [comment]
Should open and look like this for each theme parent package.json

```json 
{
	"name": "cyberpunk2077-theme",
	"displayName": "Cyberpunk 2077",
	"description": "A theme inspired by CD Projekt RED's Cyberpunk 2077",
	"version": "1.4.3",
	"publisher": "JWSandeman",
	"repository": {
		"type": "git",
		"url": "https://github.com/jwsandeman/cyberpunk2077-theme"
	},
	"keywords": [
		"theme",
		"dark theme",
		"jwsandeman",
		"cyberpunk2077",
		"cyberpunk2077-theme",
		"cyberpunk",
		"dracula",
		"abyss",
		"atlantic night",
		"moonlight",
		"palenight",
		"night owl",
		"lucy"
	],
	"engines": {
		"vscode": "^1.67.0"
	},
	"categories": [
		"Themes"
	],
	"contributes": {
		"themes": [
			{
				"label": "Cyberpunk-Edge",
				"uiTheme": "vs-dark",
				"path": "./themes/cyberpunk2077-color-theme.json"
			}
		]
	},
	"__metadata": {
		"id": "0874834b-6b77-4319-952d-a6b3b8daeaf0",
		"publisherId": "20e2fe8c-cb55-4500-8e21-a05f828f4937",
		"publisherDisplayName": "JW Sandeman",
		"targetPlatform": "undefined",
		"updated": false,
		"isPreReleaseVersion": false,
		"installedTimestamp": 1692443635992,
		"preRelease": false
	}
}
```

**Comment by devCKVargas** [comment]
@T-Crypt thank you! I'm not sure what caused this, but it should now work as intended.

**Review by prasanthrangan — APPROVED** [review]
Hi, thanks for updating and fixing it!

**Pull request merged**
