### PR TITLE
Theme Patch Script

### PR DESCRIPTION
**Pull request by kRHYME7**
#468 
Kudus to @prasanthrangan  and @T-Crypt  for their amazing Repos and Big Brainz.
envied the themes in #452 and decided to commit on making this. 

```
Usage:

./themepatcher.sh "Theme-Name" "/Path/to/Configs"
./themepatcher.sh "Theme-Name" "https://github.com/User/Repository"
./themepatcher.sh "Theme-Name" "https://github.com/User/Repository/tree/branch"
```

./themepatcher.sh needs 2 parameters. 
1: Theme_Name
2: /Path/to/Configs or https://github.com/User/Repository or https://github.com/User/Repository/tree/branch
(Cloned Repo will be added to $HOME/Clone-Hyprdots/$USER-repo-Branch)

The Script Searches for ``` Theme-Name ``` related files inside the  ``` /Path/to/Configs. ```
```
  "Configs/.config/hypr/themes/$Theme_Name.conf"
  "Configs/.config/kitty/themes/$Theme_Name.conf"
  "Configs/.config/Kvantum/$Fav_Theme/$Theme_Name.kvconfig"
  "Configs/.config/Kvantum/$Fav_Theme/$Theme_Name.svg"
  "Configs/.config/qt5ct/colors/$Theme_Name.conf"
  "Configs/.config/rofi/themes/$Theme_Name.rasi"
  "Configs/.config/swww/$Fav_Theme/"
  "Configs/.config/waybar/themes/$Theme_Name.css"

```

~~Themectl is  parsed to obtain "Theme_Name" and get the Theme and Wallpaper We could add a function if  this file is not available and make own Control file.
  "Configs/.config/swww/wall.ctl"~~

This file is modified if the repo uses specific compressed  Theme_Name.tar.xz or  Theme_Name.tar.xz It should be 
metioned on the   "Scripts/restore_fnt.lst"  so that it can be parsed.  example ``` Icon_Them_Name|/Path/to/uncompress ```
```
  "Scripts/restore_fnt.lst" 
```

After everything is restore 
append a line with this format``` 0|$Fav_Theme|$wallpaper ```  to $ThemeCTL

image
231111_20h30m41s_screenshot
231111_20h31m53s_screenshot

Thank you for being amazing!
 @prasanthrangan  @T-Crypt 

Need: 
 Review

### CODE REVIEW

**Comment by prasanthrangan** [comment]
Hey @kRHYME7 , I dont have access to my PC to test this, as I'm travelling this week.

But had a look at the script, and it depends on the scripts available in the user theme repo and restore_fnt.sh... we just need the theme files and the script should not have any external dependency as seen here -

```
grep "$Fav_Theme|" "$Theme_Dir/Scripts/restore_fnt.lst" > temp && mv temp "$Theme_Dir/Scripts/restore_fnt.lst" && [ -s "$Theme_Dir/Scripts/restore_fnt.lst" ] || > $Theme_Dir/Scripts/restore_fnt.lst

./restore_fnt.sh "$Theme_Dir/Scripts/" "$Theme_Dir"
./restore_cfg.sh "$Theme_Dir/Scripts/" "$Theme_Dir"/Configs
```

so i've made some adjustment to your script here - [themepatcher.sh.txt](https://github.com/prasanthrangan/hyprdots/files/13327879/themepatcher.sh.txt)
so please try if this version works.. i'll test this once i'm back next week!

**Comment by kRHYME7** [comment]
@prasanthrangan Adapted to your script And I saw some manageable errors. The latest commit should follow your goal of implementing the Archives, I added also the capability to extract tar.xz because the test repo I used has one(from @T-Crypt  thanks ). 
Also, you remove the sourcing of globalcontrol.sh is it intentional? 

BTW, have a Safe Trip !

**Comment by T-Crypt** [comment]
I'll test this today!! I'll make a quick theme and try with this. 

I've been wanting a PwnBox or a Hackthebox theme so I'm going to do that today

**Comment by T-Crypt** [comment]
@kRHYME7 -- This is pretty close to being ready.

Looks like my config file for Hypr got messed up with the import -- It didn't grab all my settings and didn't necessarily cp the whole "Hackthebox.conf" theme file over. 

Let me look at the code and ill provide some feedback shortly -- got a busy work day as well!

**Comment by kRHYME7** [comment]
@T-Crypt  I guess you missed the rgba on the hypr/theme. Everything looks good on my end for now.
I renamed the hackcursor too I don't know if is related to the Hackthebox theme though. Aright Thanks!

image
image

**Comment by T-Crypt** [comment]
@kRHYME7 

Yeah I meant to update that it was actually my hypr theme file and I tested and it actually works great

**Comment by kRHYME7** [comment]
Updated the script to pull the latest commit on the particular repo.  I used 
    git stash
    git pull
    git stash pop
    
    What can be the errors we may encounter

**Comment by devCKVargas** [comment]
A great addition! 🔥
I would suggest squashing the commits when ready to have a clean git history 😃

**Comment by kRHYME7** [comment]
Sorry, Yeah I guess I tried to have a cleaner commit but I couldn't help it. Is it possible to squash it upon merge? or I will issue a different PR?  Or do I have an option to squash it here in my PR ?

**Comment by T-Crypt** [comment]
@kRHYME7 

While testing for my Nordic-Blue theme -- I noticed it doesn't find the proper files based on the theme name for the arc assets.

If we go with the current format of Gtk_FrostedGlass or Gtk_GruvboxRetro then the '-' is removed when doing the arc files. I was thinking we should add this for the arcs.

```bash
# Remove hyphen from the theme name
clean_theme_name=$(echo "$Fav_Theme" | tr -d '-')

# Loop over the themes and extensions
for theme in "${themes[@]}"; do 
    for ext in "${extensions[@]}"; do
        file="${Theme_Dir}/Source/arcs/${theme}_${clean_theme_name}.${ext}"
        
        if [ -f "$file" ]; then 
            sudo tar -xf "$file" -C "${themes_dirs[$theme]}"
            echo "Uncompressing ${file##*/} --> ${themes_dirs[$theme]}... Success"
            gtk_exist=true
            break
        else
            if [[ "$theme" == "Gtk" ]]; then 
                gtk_exist=false 
            fi
            continue
        fi
    done
    
    if [[ $gtk_exist == false ]]; then 
        echo "Required: Gtk_${clean_theme_name} Archive not found." 
        exit 1
    fi
done

fc-cache -f
```

**Comment by kRHYME7** [comment]
Yep, I was waiting for Tittu's implementation for  the archives on handling the '-' If we should follow the old naming (without "-") or for the future themes to have "-" for now here is my take for the given goal of handling "-"

```for theme in "${themes[@]}"; do 
 for ext in "${extensions[@]}"; do
   file="${Theme_Dir}/Source/arcs/${theme}_${Fav_Theme}.${ext}"
   clean="${Theme_Dir}/Source/arcs/${theme}_"$(echo "$Fav_Theme" | tr -d '-')".${ext}"
   if [ -f "$file" ] || [ -f "$clean" ]; then 
       if [ -f "$clean" ]; then 
           file=$clean 
       fi
       sudo tar -xf "$file" -C "${themes_dirs[$theme]}" 
       echo "Uncompressing ${file##*/} --> ${themes_dirs[$theme]}... Success" 
       gtk_exist=true 
       break
   else
       if [[ "$theme" == "Gtk" ]]; then 
           gtk_exist=false 
       fi 
       continue
   fi 
 done 
 if [[ $gtk_exist == false ]]; then 
   echo "Required: Gtk_${Fav_Theme} Archive not found." 
   exit 1 
 fi
done
fc-cache -f

```

**Comment by prasanthrangan** [comment]
Whoaa @kRHYME7 ... amazing progress!
I'll try to test this tomorrow and create an add-on theme if possible!

**Comment by kRHYME7** [comment]
I have this issue that On my first patch of a theme It will not cached the new theme then I will run the patch again and this time it will cache. It is aso not effecient to rerun createcache.sh. to replicate I deleted the cached  folder of the theme and removing its line on wall.ctl

**Comment by kRHYME7** [comment]
Updates: 
Change the uncompress directory inside  ``` themes_dirs["Code"]="$HOME/.vscode/extensions" ```
effectively installing the extensions without overriding other extensions.

Requirements: 
+ The compressed Code_Fav-Theme should be in the folder of the extension
example :
image
+ Modifying the extensions package label into Fav-Theme.  
Example: from Hack The Box to Hackthebox
 On Json it should be at ``` contributes:themes: label "Fav-Theme" ```
image
Warning: updating of ext requires re-compiling.

**Comment by kRHYME7** [comment]
Implemented installation of extension per $Theme, Discussed at #526 .

**Comment by prasanthrangan** [comment]
Hi @kRHYME7, I've merged the themepatcher into main now.. so I'll close this!

**Pull request closed without merging**
