### PR TITLE
[performance] reload on exit

### LINKED ISSUE #2000: [Bug]: Multiple processes of Cava
### Description

When switching from a waybar style that uses Cava to one that doesn't and then back again to one that does, it doesn't kill the previous Cava process and creates a new one again which results in multiple useless Cava processes running in background.

### Steps to Reproduce

1. switch Waybar style to one that uses Cava
2. change it again to one that doesn't use Cava
3. switch it again to the Waybar style that uses Cava
4. See that there are multiple instances of Cava running in the background

### Expected Behavior

It should kill the Cava process when it is no longer needed like when switching to a Waybar style that doesn't have Cava module.

or

It should check if a Cava process is already running and use that process instead of making a new one again.

### Actual Behavior

There's multiple useless processes of Cava running in the background each using around 9-10 MBs of RAM.

### Environment

- Linux Distro: Arch Linux
- Linux Version: 6.11.7.arch1-1
- Hyprland Version: 0.45.0-1
- Installation Environment: Laptop (not vm)

### PR DESCRIPTION
**Pull request by keth-real**
# Pull Request

@kRHYME7  

- [X] Fixes during theme/wallpaper change.  
- [X] Reloads after all files are set first

closes #2000

### CODE REVIEW

**Comment by kRHYME7** [comment]
@rishav12s  @rubiin  @mahaveergurjar  Can you guys test this. But maybe there's no effect for high end PC but this one fixes issues for me. 

Some scripts is using ` hyprctl` command and when the compositor lags due to too much R/W of the hyprland related files, ` hyprctl` fails. This fixes that by reloading just once.

**Review by kRHYME7 — APPROVED** [review]
Tanks

**Comment by rishav12s** [comment]
could you tell me more about this like what is it fixes/optimizes the theme changing and wallpaper changing scripts ?

tried it and works fine no problems faced after reloading the config

**Review by rishav12s — APPROVED** [review]

**Review by rubiin — APPROVED** [review]

**Comment by kRHYME7** [comment]
The script populates the files, sometimes causing race conditions when it tries to touch Hyprland files. Reloading Hyprland once and after the files are set should be better for performance and predictability

**Review by mahaveergurjar — APPROVED** [review]

**Pull request merged**
