### PR TITLE
Update gpuinfo.sh

### PR DESCRIPTION
**Pull request by T-Crypt**
-- looks like the "VGA Controller" was causing issues as lspci lists the devices as "VGA controller"

### CODE REVIEW

**Comment by prasanthrangan** [comment]
strange, i don't see the files changed here...

**Comment by T-Crypt** [comment]
This is odd... 

On my fork -- 

for gpu in $all_gpus; do
  gpu_info=$(lspci -v | grep -A 12 "VGA controller" | grep -B 1 "$gpu")

"VGA controller" was "VGA Controller" and wasn't returning any results with the capital C -- but now im not seeing that.. This is weird..

**Comment by T-Crypt** [comment]
Closing -- Not sure what is going on

**Comment by prasanthrangan** [comment]
cool, no worries...

**Pull request closed without merging**
