### PR TITLE
fix: add swappy config

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

Adds swappy default config  

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
It will be generated by the screenshot tool. Is  swappy not working?

**Comment by rubiin** [comment]
Oh yeah the generated ones dont include these defaults
image

**Comment by kRHYME7** [comment]
What change if we add those configs for swappy?

**Comment by rubiin** [comment]
> What change if we add those configs for swappy? IMO it's better to leave it as if those configs are the default.
> 
> My main concern actually is adding another entry in the restore.cfg.lst if the config is not needed.

These are the defaults swappy suggests on their readme. Having the config file will make sure these defaults remain the same in future versions of swappy.
Also the save folder is changed from `Desktop` to `Pictures` as thats what most tools save in

**Comment by rubiin** [comment]
This also has swappy config https://gitlab.com/stephan-raabe/dotfiles

**Pull request closed without merging**
