### PR TITLE
fix: VSCode colors now sync with changing theme.

### PR DESCRIPTION
**Pull request by aryan-212**
# Pull Request

## Description

- Code now change colors in sync with theme changes + additional files are not created
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Issues and Mentions :- #1370 and #1315 

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests .

### CODE REVIEW

**Comment by mahaveergurjar** [comment]
Don't add this type because everyone does not use the ext Dev mod option because this option enables to use single windows not open multiple windows so that's why don't added this type

**Review by mahaveergurjar — CHANGES_REQUESTED** [review]
Don't add this type because everyone does not use the ext Dev mod option because this option enables to use single windows not open multiple windows so that's why don't added this type

**Review by celikj — APPROVED** [review]

**Review by rubiin — APPROVED** [review]

**Comment by kRHYME7** [comment]
Everyone approving this, Did you guys tried multi window vscode with this?

**Comment by aryan-212** [comment]
Hey so I found out that if I modify the **code** binary file to:
```bash
#!/bin/bash

set -euo pipefail

flags_file="${XDG_CONFIG_HOME:-$HOME/.config}/code-flags.conf"

declare -a codeflags

if [[ -f "${flags_file}" ]]; then
    mapfile -t < "${flags_file}" CODEMAPFILE
fi

for line in "${CODEMAPFILE[@]}"; do
    if [[ ! "${line}" =~ ^[[:space:]]*#.* ]]; then
        codeflags+=("${line}")
    fi
done

name=electron29 
flags_file="${XDG_CONFIG_HOME:-$HOME/.config}/${name}-flags.conf"

declare -a electronflags

if [[ -f "${flags_file}" ]]; then
    mapfile -t < "${flags_file}" ELECTRONMAPFILE
fi

for line in "${ELECTRONMAPFILE[@]}"; do
    if [[ ! "${line}" =~ ^[[:space:]]*#.* ]]; then
        electronflags+=("${line}")
    fi
done

if pgrep -f "/usr/lib/${name}/electron" > /dev/null; then
    ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js /usr/lib/code/code.js "$@"
else
    ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js "${electronflags[@]}" /usr/lib/code/code.js ${codeflags[@]} "$@"
fi
```
Multiwindow works


> Everyone approving this, Did you guys tried multi window vscode with this?

**Comment by aryan-212** [comment]
@kRHYME7 the above comment

**Review by keth-real — APPROVED** [review]

**Review by kRHYME7 — APPROVED** [review]
Thanks!

**Pull request merged**
