### PR TITLE
fix: fixed bugs in waybar brightness and window module 

### PR DESCRIPTION
**Pull request by Anshul-007**
# Pull Request

## Description

- For backlight i have used the previous backlightcontrol.sh script and slightly modified for quiet mode
- For window there were several bug fixes `${USER@${set_sysname}:(.*)` was designed to display a terminal but for the arch logo waybar design it was failing solved by adding `(.*)${USER}@${set_sysname}:(.*)`

- others were fixed for User Experience, for example new tab in firefox would say "Firefox 󰈹" which breaks the UX slightly by removing the arch logo

- added discord logo for discord support
- changes in backlight control script adding quiet mode in flag in script alongwith redesigning the script and adding more testcases

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

previous brightness keys working as intended
image

test-cases
image

### CODE REVIEW

**Comment by rishav12s** [comment]
> @kRHYME7 @rishav12s do you think i changed too much in brightnesscontrol.sh script?

if the pr is waybar related why are you changing brightness script stuff 

i haven't gone through your previous pr of this so i'm out of context 

like what are you trying to fix

**Comment by kRHYME7** [comment]
Yup, if the PR is just to add Feature e.g the "quiet" flag then please abide by the format. If you wish to add something extra or refactor the script that should deserve another PR.

 I scanned through this script and it looks good at glance but you delayed the merging of the actual goal of the original PR by adding more stuff. 

tltr, I hope you understand this.

**Comment by kRHYME7** [comment]
Lemme know if this is ready

**Comment by Anshul-007** [comment]
Yes will add the quiet mode in another pr

**Review by Anshul-007 — COMMENTED** [review]
I did testing of final submitted pr with modified changes

**Comment by Anshul-007** [comment]
Now I don't have to do anything right?

**Comment by kRHYME7** [comment]
@rishav12s @rubiin @abenezerw No objections from gou guys?

**Review by kRHYME7 — APPROVED** [review]

**Review by boulder-roller — APPROVED** [review]
lgtm

**Pull request merged**
