### PR TITLE
Refactor Waybar Configuration and Add Switch Menubar Module

### PR DESCRIPTION
**Pull request by amedeo**
**Introduction:**
This pull request refactors the waybar configuration and themes to provide an easier way to reconfigure the position of the waybar and the disposition of its contained modules. Additionally, I have added a new module that allows for iterative switching between all available waybar configurations. Although I am uncertain if this feature is necessary, I developed it to accommodate my personal preference for a top menubar with a different module disposition. Taking this need into consideration, I decided to implement it as a feature rather than a local configuration.

**Detailed Explanation:**
The changes in this pull request offer the following improvements:

- Refactored the waybar configuration and themes to provide enhanced flexibility in reconfiguring the position and layout of the waybar and its modules.
- Added a new module that allows users to iteratively switch between all available waybar configurations, providing a convenient way to experiment with different setups.
- Although I acknowledge that having the Switch Menubar functionality directly in the menu may not be necessary, it can easily be bound to a key or determined during the initial installation process, allowing for a personalized experience.

**Testing:**
I have conducted thorough testing to ensure the functionality and stability of these changes. The refactored waybar configuration and themes have been tested across various configurations, and the Switch Menubar module has been verified to switch seamlessly between different configurations.

**Documentation:**
If this pull request is approved, it will require updates to the project's documentation to reflect the changes introduced. Specifically, the documentation should be updated to explain the new configuration options for repositioning the waybar and adjusting the module disposition.  I am willing to contribute to the documentation updates as needed to ensure clarity and completeness.

**Closing Remarks:**
I am open to any feedback, suggestions, or improvements regarding this pull request. I understand that my expertise lies outside of bash scripting, but I have done my best to ensure the quality and functionality of these changes.

### CODE REVIEW

**Review by prasanthrangan — APPROVED** [review]
Thank you so much for this cool feature, I'll merge this and try it out!

**Comment by prasanthrangan** [comment]
Thanks again, your wbarswitch script works incredibly well!
The waybar config symlink was broken and the install script didn't fix it, so I've updated it to be compatible with the install script.

Please feel free to update the [theming.md](https://github.com/prasanthrangan/hyprdots/blob/main/theming.md) to document this feature/script.

This also gives me an idea to develop a waybar config generator script, which can dynamically generate these `config.json` and `style.css` files which can be cycled through `wbarswitch.sh` script!

**Comment by amedeo** [comment]
I have seen a lot of progress and significant improvements in the waybar area; great! Your idea for the generator is excellent. I wonder if the fixed height is needed as in my pull, I removed it trying to maintain the same shape via CSS but leaving the door open for something I was working on. I will be back on this hopefully soon.

**Comment by prasanthrangan** [comment]
> I have seen a lot of progress and significant improvements in the waybar area; great! Your idea for the generator is excellent. I wonder if the fixed height is needed as in my pull, I removed it trying to maintain the same shape via CSS but leaving the door open for something I was working on. I will be back on this hopefully soon.

Thank you! I think we can use `0` in the `config.ctl` file (col 2) to remove the height set in main `config.jsonc` file, so that it can scale based on the `style.css` file.
This should be an easy update.

**Pull request merged**
