### PR TITLE
config: Adding ArmCord to windowsrules config

### PR DESCRIPTION
**Pull request by Pr0gGenie**
# Pull Request

## Description
This windowrules config change should make ArmCord look better and close to the themes of hyprdots.

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Screenshots
image

### CODE REVIEW

**Comment by kRHYME7** [comment]
Hello 👋 @Pr0gGenie  what is armcord?

In case you want to add some custom windowsrules you can still add it in the ./userpref.conf 🍻

**Comment by Pr0gGenie** [comment]
Hello @kRHYME7, armcord is basically like webcord, but with some extra features. 

Yes, I did add it to userpref, and because I saw the webcord in the windowsrules, I thought armcord could go there too.

**Comment by kRHYME7** [comment]
I see, Thanks! 🎉

**Review by prasanthrangan — APPROVED** [review]
oh cool, thanks!

**Pull request merged**
