### PR TITLE
feat(keybinds): add keybinds to move between windows in a group

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

## Description

Adds keys to move between the stacked windows in a group activated with MOD+G

more context [wiki.hyprland.org/Configuring/Dispatchers/#grouped-tabbed-windows](https://wiki.hyprland.org/Configuring/Dispatchers/#grouped-tabbed-windows)

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

## Additional context

We have the key combo to activate group but not to move between them. This was only possible with mouse click. This eliminates the need for mouse

### CODE REVIEW

**Comment by rubiin** [comment]
@kRHYME7 this is non breaking so can be merged i guess

**Comment by rubiin** [comment]
@kRHYME7 lets merge this too

**Review by kRHYME7 — APPROVED** [review]
I will just think that this will be a laying ground for some group bar configuration soon.

**Comment by rubiin** [comment]
> I will just think that this will be a laying ground for some group bar configuration soon.

currently I am using this. groups are a nice way to organize your workspaces opened application unlike tiling where you get only a portion of the screen and fullscreen mode which hides the bars. Its like best of both words

**Comment by kRHYME7** [comment]
me too 😬 
image

**Comment by rubiin** [comment]
MOD+ctrl+[H-L]   is a few key strokes  more . The reasonable will be MOD+left arrow and right arrow if they are not mapped to anything

**Pull request merged**
