### PR TITLE
fix: compress display images

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

## Description

This compresses images that are shown on readme and thus reduces the repo size . The quality is closer
This will makie cloning the repo faster as well 

image

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [x] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by rubiin** [comment]
Nah. I manually did these keeping sure the quality was close

**Review by kRHYME7 — APPROVED** [review]
Thank you and I hope nothing breaks haha. already reviewed your branch and looks good

**Comment by rubiin** [comment]
Yeah . The imagez look fine here , https://github.com/prasanthrangan/hyprdots

**Comment by kRHYME7** [comment]
image
Wow

**Comment by rubiin** [comment]
This will also make Hyde-install faster. Most time was spent on these huge files

**Comment by rubiin** [comment]
we can also do the same for hyde-themes, the wallpapers some are like 9MB :D

**Comment by kRHYME7** [comment]
Now I can't do anything on his theme repo. you can add PR there though

**Comment by rubiin** [comment]
I am looking at something like this. Maybe we can implement on hide 
https://stackoverflow.com/questions/33104475/git-clone-and-pull-omitting-large-files#:~:text=git%20clone%20--no-checkout,files%20but%20the%20big%20ones.

**Comment by kRHYME7** [comment]
For now Hyde-CLI has a way to cherry-pick wallpapers when installed individually

**Pull request merged**
