### PR TITLE
Vs codium support

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

## Description

Support wallbash for Vscodium 

Here's the explanation why I remove the nesting when applying and installing the ext. 
https://github.com/VSCodium/vscodium/issues/114#issuecomment-482571448

vscodium and code-oss shares the ` ~/.vscode-oss `

This might also help in skipping some errors.

### CODE REVIEW

**Review by rubiin — APPROVED** [review]

**Review by rubiin — APPROVED** [review]

**Comment by rubiin** [comment]
maybe we can also add support for vscode-insiders. That would complete the whole vscode app group

**Comment by kRHYME7** [comment]
insiders is the test build of vscode right?

**Comment by rubiin** [comment]
> insiders is the test build of vscode right?

yeah . Its a rolling release of latest push

**Comment by rubiin** [comment]
I use this as my daily driver https://code.visualstudio.com/insiders/

**Comment by kRHYME7** [comment]
I guess it works out of the box. You also want to add defaults for this in setting.json?

**Comment by rubiin** [comment]
> I guess it works out of the box. So we should also add hyde default settings.json?

yea

**Comment by rubiin** [comment]
@kRHYME7 this can be closed I guess . We merged similar kind of thing

**Comment by rubiin** [comment]
https://github.com/prasanthrangan/hyprdots/pull/1849

**Comment by kRHYME7** [comment]
Yups. But for the default config it's for the USER to figure out. But Should be fine as we are not "Officially" shipping those

**Pull request closed without merging**
