### PR TITLE
feat: Add wallbash Theme support for Cursor(IDE)

### PR DESCRIPTION
**Pull request by KitsuneKode**
# Pull Request

## Description

Added support for wallbash theming on Cursor IDE for now with manual intervention of installing the theme https://www.cursor.com/how-to-install-extension

@kRHYME7 

## Type of change

- [x] **New feature** (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).

## Screenshots

image

image

### CODE REVIEW

**Review by rubiin — APPROVED** [review]
I think you also have to update the restore_config files

**Comment by kRHYME7** [comment]
> I think you also have to update the restore_config files

This script should work out of the box. Except the manual installation of wallbash extension. 

BTW does this script work with insiders too @rubiin  ?

**Comment by rubiin** [comment]
No it doesnt. Code is themed , insiders is not

**Comment by kRHYME7** [comment]
Got it! we required to ship setting.json right. 

Will try to support codium,cursor and insiders I guess?

**Comment by kRHYME7** [comment]
@rubiin  Can you please try it. Should work now for 

vscode
vscode-insiders
code-oss
vscodium
cursors

As long as the setting.json is present

**Comment by rubiin** [comment]
let me check

**Comment by rubiin** [comment]
works well

**Comment by kRHYME7** [comment]
Will merge this one now.

**Review by kRHYME7 — APPROVED** [review]

**Review by rubiin — APPROVED** [review]

**Pull request merged**
