### PR TITLE
transparency effect for thunar

### PR DESCRIPTION
**Pull request by JoeArchV**
Thunar is a file explorer and Dolphin alternative and is used by many users

### CODE REVIEW

**Comment by boulder-roller** [comment]
if you're going to add a ton of apps pls just do it in one pr :sob:

otherwise go for it

**Comment by JoeArchV** [comment]
Would you like to not add any application like crazy?

**Comment by JoeArchV** [comment]
What I want to achieve is that when new people install hyde they don't have those problems

**Comment by Anshul-007** [comment]
If you think you want to add more apps that are essestial then add in this pr. And then say it is ready to merge

**Comment by JoeArchV** [comment]
pr?

**Comment by Anshul-007** [comment]
pull request

**Comment by JoeArchV** [comment]
Excuse me, I will try to collect more applications and add them, I know they will become essential as you say

**Comment by Anshul-007** [comment]
> Excuse me, I will try to collect more applications and add them, I know they will become essential as you say

Yeah only essentials.

**Comment by boulder-roller** [comment]
@kRHYME7 they grow up so fast :smiling_face_with_tear:

**Comment by kRHYME7** [comment]
Please stop adding windowrulev just for the opacity.

FYI if you all add this to your windowrules.conf


https://github.com/HyDE-Project/HyDE/blob/master/Configs%2F.local%2Fshare%2Fhyde%2Fhyprland.conf#L147-L149

decorations{
    active_opacity = 0.95
    inactive_opacity = 0.80
    fullscreen_opacity = 1
}

all Windows will follow this. and the windowrule for opacity will just act as a multiplier for the values.

**Review by T-Crypt — DISMISSED** [review]

**Comment by T-Crypt** [comment]
Im back. I can start maintaining this and merging where needed.

**Comment by kRHYME7** [comment]
Welcome back @T-Crypt

**Comment by T-Crypt** [comment]
@kRHYME7 -- not looking forward to reviewing these PR's.

**Comment by kRHYME7** [comment]
TBH, some MRs are just a maintenance burden as long as I'm the only present collaborator. 
I'm trying to have a fork and an organization named Hyde-project, to at least maintain it effectively, based on my current position. Would you care if I invite you to the Org?

**Comment by T-Crypt** [comment]
Go ahead and send the invite

**Comment by T-Crypt** [comment]
This is a user preference that needs to be added to your userpref.conf  file and not the repo

**Pull request closed without merging**
