### PR TITLE
Add window blur toggle control

### PR DESCRIPTION
**Pull request by Patriot-06**
* for ease of use as some users don't like blur or either it impacts their overall graphical performance.

# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ ] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
Hi @Patriot-06 , I wrote a utility for this 

Running ``` Hyprdots power save --opacity ``` will disable all blur effect declared on the Windows rules file


```
❯ Hyprdots power save
Usage: Hyprdots power save [options]
Options:
[-a] [--animations]             Disable Animations
[-ba] [--borderangle]           Disable border angle Animation.
[-b] [--blur]                   Disable Blur
[-o] [--opacity]                Disable Tranparency
❯ Hyprdots power save --opacity
DISABLE Transparent opacity

```

**Comment by Patriot-06** [comment]
well i had no idea that you've already wrote a utility for this, anyways you're doing a great job

**Comment by Patriot-06** [comment]
well i had no idea that you've already wrote a utility for this, anyways you're doing a great job btw aren't float rules defined in windowrules.conf

**Comment by kRHYME7** [comment]
> well i had no idea that you've already wrote a utility for this, anyways you're doing a great job btw aren't float rules defined in windowrules.conf ?

Yep that's why unsourcing the windowsrules might not be a good idea. 

Here is the [repo](https://github.com/kRHYME7/Hyprdots-ctl) for the CTL of this. I wrote this so that some common commands are easier to remember.

BTW I updated it to unset changes might as well try it ( You can update in the AUR, the  package name is hyprdots-ctl )
Did not add a toggle feature yet as I do not know if it is necessary always to toggle this feature. 

image



The power options were created due to some hyprland features being expensive for the CPU. Like animations, blur, and especially the borderangle animation #641 .

**Comment by Patriot-06** [comment]
great

**Comment by prasanthrangan** [comment]
Thank you @Patriot-06 , for your contribution!
As @kRHYME7 mentioned, its not a good idea to remove window rules, so the easier option would be to use `hyprdots-cli` or `hyprctl` (refer hypr wiki or [gamemode.sh](https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/scripts/gamemode.sh)) to toggle blur.

**Pull request closed without merging**
