### PR TITLE
chore: switch swww to the stable version  (close #1204)

### LINKED ISSUE #1204: [Bug]: SWWW Grayed wallpapers & no wallpaper @ login
## Bug Report

Let me compile the issue to avoid dupes. 

#### ISSUES

Please scan this issues before you open another duplicates😁

+  https://github.com/prasanthrangan/hyprdots/issues/1165
+ https://github.com/prasanthrangan/hyprdots/issues/1180

+ https://github.com/LGFae/swww/issues/233  << [UPSTREAM ISSUE]

#### WORKAROUNDS

Here are the ways to fix it. 
basically, we just need to remove the old socket

**Fix Grayed wallpaper** 
https://github.com/LGFae/swww/issues/248#issuecomment-2022795829

``` swww-daemon --format xrgb ``` should be enough

> [!Note]
> clearing cache is useless according to the dev

If you happen to have the error below when you run the above command, it's possible you did not read the thread above.
``` Error: "couldn't bind socket: Address already in use (os error 98)" ```
Basically we need to remove the existing socket  ```  rm  $XDG_RUNTIME_DIR/swww.socket ``` then rerun again. It should work. 
Now, how can you fix it across reboots? Do the workarounds below.

**Wallpaper not loading** 

+  Install the upstream package ``` yay -Sy swww-git ``` 

+   If you don't want to install the devel package,  use this part https://github.com/prasanthrangan/hyprdots/blob/537594a49db2bf9a6e64394e2c685d4d7c9dd4fd/Configs/.config/hyprdots/scripts/swwwallpaper.sh#L140C1-L160C1 to your  ``` ~/.config/hyprdots/scripts/swwwallpaper.sh ``` 

+ This should work too 
```
swww query
if [ $? -ne 0 ] ; then
[ -e $XDG_RUNTIME_DIR/swww.socket ] && rm  $XDG_RUNTIME_DIR/swww.socket
    swww-daemon --format xrgb &
fi
```

### PR DESCRIPTION
**Pull request by hdm9527**
# Pull Request

## Description

[swww v0.9.2](https://github.com/LGFae/swww/releases/tag/v0.9.2) fix  no wallpaper problem #1204

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by hdm9527** [comment]
I tested it and it works fine.

**Comment by kRHYME7** [comment]
https://aur.archlinux.org/packages/swww 

is it available now on the AUR?

**Comment by hdm9527** [comment]
> https://aur.archlinux.org/packages/swww
> 
> is it available now from the AUR?

I use this [mirror](https://mirrors.ustc.edu.cn/archlinuxcn/x86_64/), and aur synchronization is slow.

**Comment by prasanthrangan** [comment]
oh.. is it fixed in upstream?

**Comment by hdm9527** [comment]
> oh.. is it fixed in upstream?

yep. You can use this [package](https://mirrors.ustc.edu.cn/archlinuxcn/x86_64/swww-0.9.2-1-x86_64.pkg.tar.zst) for testing.

**Comment by kRHYME7** [comment]
Upstream  v0.9.2  fixes this part (it does this part)
image
 
But not yet for graying wallpapers

Also I think my mirrors are late? swww 0.9.1  
image

**Comment by hdm9527** [comment]
> Upstream v0.9.2 fixes this part (it does this part) image
> 
> But not yet for graying wallpapers
> 
> Also I think my mirrors are late? swww 0.9.1 image



> Upstream v0.9.2 fixes this part (it does this part) image
> 
> But not yet for graying wallpapers
> 
> Also I think my mirrors are late? swww 0.9.1 image

Aur is updated manually. This mirror is synchronized from [archlinuxcn](https://github.com/archlinuxcn/repo), which is automatically packaged through bot.

**Review by prasanthrangan — APPROVED** [review]
looks good, thanks!

**Pull request merged**
