### PR TITLE
feat: use shuffle for faster

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

Replaces sort and head with shuffle . 

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [x] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by rubiin** [comment]
@kRHYME7 LGTM

**Review by abenezerw — APPROVED** [review]
I guess this is efficient and faster. @kRHYME7

**Comment by abenezerw** [comment]
> I guess this is efficient and faster. @kRHYME7

Can we also upload some new images in there. There’s only 5 and 2 are Hyde. Maybe get the hyprchan one too

**Comment by rubiin** [comment]
@abenezerw here are few https://github.com/rubiin/dotfiles/tree/master/private_dot_config/fastfetch/pngs
I will make a PR with the wave icon and 4-5 others

**Comment by rubiin** [comment]
> I guess this is efficient and faster. @kRHYME7

yeah . This way we dont have to pipe the output to two different commands. Also sort is expensive when there are 100s of entries

**Comment by abenezerw** [comment]
> @abenezerw here are few https://github.com/rubiin/dotfiles/tree/master/private_dot_config/fastfetch/pngs I will make a PR with the wave icon and 4-5 others

Yeah I saw your list from your discord link. Maybe hand pick not as many but just a few to add to main repo for everyone.

**Comment by rubiin** [comment]
I think this looks cool. https://github.com/rubiin/dotfiles/blob/master/private_dot_config/fastfetch/pngs/great-wave-transparent-2.png
I will handpick few others . We also have to take in account the size so will pick ones that are less than 1 mb

**Comment by rubiin** [comment]
Here https://github.com/prasanthrangan/hyprdots/pull/1856

**Comment by rubiin** [comment]
I even updated the local find command with fd which is way faster compared to find. Ofcourse fd is not available preinstalled so have to install it manually so havent added that portion here to avoid adding a dep

**Review by kRHYME7 — APPROVED** [review]

**Pull request merged**
