### PR TITLE
Add `downgrade` to initial install

### PR DESCRIPTION
**Pull request by devCKVargas**
At first I thought it should be an optional pkg, but changed it to be included as part of the first install.
Since we're rolling & new people are coming, KSK Royal made a video about the project.
And with an issue like #496, it's useful to have this.

### CODE REVIEW

**Comment by kRHYME7** [comment]
Oh, the video might be the reason for the recent flood of issues haha. Wow!

**Comment by devCKVargas** [comment]
> Oh, the video might be the reason for the recent flood of issues haha. Wow!

I think the showcase was over a week ago, and @prasanthrangan is on a trip.
Lots of new commers means more issues, bugs to fix, maybe new features, and more support in general.
Perhaps OC could finally open a BuyMeACoffee or a Ko-fi account for support.

**Comment by prasanthrangan** [comment]
> At first I thought it should be an optional pkg, but changed it to be included as part of the first install.
> Since we're rolling & new people are coming, KSK Royal made a video about the project.
> And with an issue like #496, it's useful to have this.

ohhhhh.... so that's why!
Think I'll link that video in the installation guide :)
Lots of documentation to update and maintain :(

**Review by prasanthrangan — APPROVED** [review]
looks good, thanks!

**Pull request merged**
