### PR TITLE
fix(xdg): add xdg paths for zsh

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

sets XDG base directories as suggested in arch wiki
https://wiki.archlinux.org/title/XDG_Base_Directory

Laying grounds for https://github.com/prasanthrangan/hyprdots/issues/383

The problem: a home folder littered with files and folders from apps long since uninstalled and forgotten.

The solution: XDG

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by Skerse** [comment]
Can you add this for fish as well if we do merge this? That's another supported option by us.

**Comment by rubiin** [comment]
will do . Fish doesnt support export keyword and I dont use fish much , so I will have to look

**Comment by rubiin** [comment]
@Skerse done

**Comment by kRHYME7** [comment]
I got some input for this too. 

Setting ENVS in .*rc  is not effective to the whole session, so I do not know if this is beneficial or might lead to confusion. 

Examples:
 _Launching from ` terminal `  vs  launching from ` dumb ` (no UI )._ 
 * Both outputs will use different ENVs which is bad IG? 

Another issue I remembered is multiple languages support. If we hard-code this env in English, this might conflict with non-english locale users. (did not dig deeper. ) maybe it's okay, maybe not.

**Comment by rubiin** [comment]
we can do on .env file which is set per terminal session. Regarding the convention , it is loacle independent

**Comment by rubiin** [comment]
closing in favor of https://wiki.archlinux.org/title/XDG_user_directories. Its preinstalled on linux

**Pull request closed without merging**
