### PR TITLE
Disabling the annoying bell sound

### PR DESCRIPTION
**Pull request by aryan-212**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ ] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Review by rubiin — APPROVED** [review]

**Comment by kRHYME7** [comment]
This is fine to me, but this is obviously more of a preference and we might override the Owners prefs. 

How about we include a ./custom.conf for kitty so that user can add customization here? Instead of conflicting preferences 

image


So either we ship a black (the whole kitty conf) as ~/.config/kitty/custom.conf file with N|Y flags or ignore errors and just let user create the file  
image

@rubiin  @aryan-212  WDYT

**Comment by aryan-212** [comment]
I do not mean to come across as combative, but come on, how many people do you know who want sounds coming from their terminal emulators?

**Comment by kRHYME7** [comment]
> @kRHYME7 , I do not mean to come across as combative, but come on, how many people do you know who want sounds coming from their terminal emulators?


I understand, but my intention is not about the MR changes. I'm trying to open up possibilities for users to update from this repo without overwriting their custom stuff.

**Comment by rubiin** [comment]
I have mixed opinions . Lets put this on hold . If a viable number of users request, then we can merge this

**Review by kRHYME7 — APPROVED** [review]

**Comment by RookiexCookie** [comment]
Its an OK from me
we can go through with this

**Comment by rubiin** [comment]
Those in favor can :+1:  the PR

**Comment by aryan-212** [comment]
So, what are your thoughts?

**Pull request merged**
