### PR TITLE
Nightlight-hyprshade

### PR DESCRIPTION
**Pull request by sanjyay**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [x] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots
-

### CODE REVIEW

**Review by rubiin — APPROVED** [review]

**Review by dieBakterie — CHANGES_REQUESTED** [review]
We should let the the user decide to install/use hyprshade or not! We can add the possibility to choose if hyprshade or another one wl-gammarelay-rs in this case gets installed or not. To achieve this just add the following in the `install.sh` script in the **get userprefs** section:
```
    if ! chk_list "myShader" "${shdList[@]}"; then
        echo -e "Select shader:\n[1] hyprshade\n[2] wl-gammarelay-rs\n[3] none"
        prompt_timer 120 "Enter option number"

        case "${promptIn}" in
            1) export myShader="hyprshade" ;;
            2) export myShader="wl-gammarelay-rs" ;;
            3) export myShader="none" ;;
            *) echo -e "...Invalid option selected..." ; exit 1 ;;
        esac
        if ${myShader} != "none"; then
            echo -e "\n\033[0;32m[userprefs]\033[0m Shader: ${myShader}"
            echo "${myShader}" >> "${scrDir}/install_pkg.lst"
        else
            echo -e "\n\033[0;32m[userprefs]\033[0m Shader: ${myShader} selected, skipping!"
            exit 0
        fi
    fi
```

and in `global_fn.sh` just add:
```
shdList=(hyprshade wl-gammarelay-rs none)
```
and lastly **you need to remove hyprshade from the `custom_hypr.lst` for this to work properly!** This isn't tested, therefore check for typos and syntax errors etc.

**Comment by celikj** [comment]
did you managed to night light mouse cursor also? mine is still same white

**Comment by sanjyay** [comment]
> did you managed to night light mouse cursor also? mine is still same white

yea even mine is still white but is that possible ?

**Review by rubiin — CHANGES_REQUESTED** [review]
This file is no longer required. You can now control the temperature via the config file

**Pull request closed without merging**
