### PR TITLE
fix(swww): Wallpaper show distorted and in grayscale

### PR DESCRIPTION
**Pull request by hdm9527**
# Pull Request

## Description

After swww was updated to v0.9.0, `swww init` was deprecated. Use `swww-daemon` instead. Use `swww-daemon --format xrgb` to fix wallpaper display distortion issue.  https://github.com/LGFae/swww/releases/tag/v0.9.1 https://github.com/LGFae/swww/issues/233

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

image

### CODE REVIEW

**Comment by prasanthrangan** [comment]
oohh does this `swww-daemon` work with non-git version as well?

**Comment by hdm9527** [comment]
> oohh does this `swww-daemon` work with non-git version as well?

Non-git versions can also be used. swww-daemon can run normally under version v0.8.2. I updated swww to the latest stable version v0.9.1.

**Review by prasanthrangan — APPROVED** [review]
thanks for confirming, its working!

**Comment by mrspedd** [comment]
I have a question, I am new to linux. But, the wallpaper worked for me when I changed it to "swww init" rather than "swww daemon". My version for swww is v0.8.2, does that mean it doesnt work for this version?

**Comment by hdm9527** [comment]
> I have a question, I am new to linux. But, the wallpaper worked for me when I changed it to "swww init" rather than "swww daemon". My version for swww is v0.8.2, does that mean it doesnt work for this version?

swww v0.8.2 version works fine. Wallpaper switching problem has been fixed. #1163

**Comment by kRHYME7** [comment]
> I have a question, I am new to linux. But, the wallpaper worked for me when I changed it to "swww init" rather than "swww daemon". My version for swww is v0.8.2, does that mean it doesnt work for this version?

image

I still have the older version and it should still work. the swww init seems like redundant if swww-daemon  can be started manually. The update should fix it.  It lacks "&" and is now fixed in #1163

**Comment by mrspedd** [comment]
Yep, Thanks it works perfectly now :)

**Comment by L4FeeR** [comment]
Hey how to make it work, am very noob, pls tell me

**Comment by L4FeeR** [comment]
I have also same distorted wallpaper, I tried 16 time installing arch again nd again with hyprland, still not resolved. Kindly someone help me, am very new to arch .

**Comment by mrspedd** [comment]
> I have also same distorted wallpaper, I tried 16 time installing arch again nd again with hyprland, still not resolved. Kindly someone help me, am very new to arch . 

Can you send a screenshot of the last few lines of ur swwwallpaper.sh script?

**Comment by L4FeeR** [comment]
Where to find that script

**Comment by mrspedd** [comment]
in your terminal type:
cd .config/hyprdots/scripts, it will be in there

**Comment by mrspedd** [comment]
> 
> 
> 

I cant seem to see the file, are you able to fond the part where it says swww-daemon

**Comment by mrspedd** [comment]
> 
> 
> 

Lmao are you able to copy and paste tht line into here

**Comment by L4FeeR** [comment]
Do you have telegram?, if so I may give you ssh.

**Comment by mrspedd** [comment]
> Do you have telegram?, if so I may give you ssh.

Type 
```
grep "swww-daemon" swwwallpaper.sh
```

**Comment by L4FeeR** [comment]
Or downgrading the swww will work? If so how to downgrade?

**Comment by hdm9527** [comment]
> Or downgrading the swww will work? If so how to downgrade?

Please update hyprdots. Enter the Scripts Directory to run `./install.sh -r`. #1204

**Comment by L4FeeR** [comment]
Lemme reinstall arch  and follow this vid, could you pls tell me the fix?

https://youtu.be/n6Yg232bCOU?si=Mi8R7xJX4fl-GO4c

**Comment by kRHYME7** [comment]
@L4FeeR  Please use the ``` swww-git ```  for now follow the instructions on the link below. 

Follow this issue. I recently ask about this issue from swww dev himself. 
https://github.com/prasanthrangan/hyprdots/issues/1204

**Pull request merged**
