### PR TITLE
[Feature]Display Bluetooth Battery

### PR DESCRIPTION
**Pull request by kRHYME7**
# Pull Request

## Description

Discussion here
#757 
Added battery percentage for Bluetooth devices with battery.  
See the file and uncomment this part if the user prefers a certain device 
```
     "format-device-preference": [ "device1", "device2" ], // preference list deciding the displayed device If this config option is not defined or none of the devices in the list are connected, it will fall back to showing the last connected device.
```

#### Waybar says: 
format-device-preference:
typeof: array
A ranking of bluetooth devices, addressed by their alias. The order is from first displayed to last displayed.
If this config option is not defined or none of the devices in the list are connected, it will fall back to showing the last connected device.

## Type of change

Please put an `x` in the boxes that apply:

- [x] **New feature** (non-breaking change which adds functionality)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Screenshots

image
image
image

### CODE REVIEW

**Comment by prasanthrangan** [comment]
Hey @kRHYME7 , thanks bro!
This looks good, but this format is taking a lot of space as it shows the device name.
So we add this as alt-format, so that we have the minimal icon that just shows the number or devices and this alt-format to show the device name and batt%.

**Comment by kRHYME7** [comment]
Sure sure!

**Comment by kRHYME7** [comment]
@prasanthrangan, Hey Bro, I Can't read a configuration for an alternative format for the connected-battery option for now. I will hand this over to whoever might do it. For now, do you think this is alright? 

With battery
image
Without Battery 
image


My only ref is this 
https://www.mankier.com/5/waybar-bluetooth

**Review by prasanthrangan — APPROVED** [review]
Looks great, thanks!
Don't worry about alternate format, this works just fine as it gives the device count and the icon indicates the batt%. The tooltip gives the details.

**Pull request merged**
