### PR TITLE
remove: bluetooth waybar module from config.ctl & config.jsonc

### PR DESCRIPTION
**Pull request by Skerse**
# Pull Request

## Description

Remove the bluetooth waybar module, since blueman-applet (which we autostart) gives bluetooth information and battery percentage as of this release 3 weeks ago: https://github.com/blueman-project/blueman/releases/tag/2.4

image

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [x] **Other** (provide details below)

Remove a feature.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

Blueman-applet: 
image

Bluetooth waybar module: 
image

### CODE REVIEW

**Review by rubiin — APPROVED** [review]

**Review by hdm9527 — APPROVED** [review]

**Review by kRHYME7 — APPROVED** [review]
okie 🛞

**Comment by Skerse** [comment]
> But I will be sad if the Bluetooth module is removed. (Will use this for future reference hihi)

I guess we can keep it, but it'll just be unused.. i'm thinking, if we keep it maybe we can have in `.../modules/.old` directory where it can be ignored by `wbarconfgen.sh`?

**Comment by kRHYME7** [comment]
Will just read the commit history or waybar manpage. Should be fine. Also this is tagged ate version 0.1.0

**Comment by prasanthrangan** [comment]
Please don't remove the `bluetooth.jsonc` module itself as some users might want it (it does show battery level icon)... so just remove it from `config.ctl`

**Comment by Skerse** [comment]
I believe that's good now?

**Comment by prasanthrangan** [comment]
> So does blueman-applet now, but alright, i'll add it back.

oh.. does it?? any idea how to display it as the bluetooth module here -

image

**Review by prasanthrangan — APPROVED** [review]

**Comment by Skerse** [comment]
> any idea how to display it as the bluetooth module here -

It only shows if you have bluetooth devices connected.

**Comment by Skerse** [comment]
> > It only shows if you have bluetooth devices connected.
> 
> hmm... but I have earphones connected, the battery % does show up in the tooltip but not in the bar itself.

Strange, that should be working.. i don't really know why it wouldn't and it doesn't seem like you're using one of the waybar configs that didn't use the bluetooth module..

Does your `config.jsonc` have the bluetooth waybar module in there?

**Pull request merged**
