### PR TITLE
Forces VSCode to run in Wayland rather than Xwayland

### PR DESCRIPTION
**Pull request by hchasens**
# Pull Request
Forces VSCode to run in Wayland rather than Xwayland

## Description

Due to a current bug in electron, some electron apps don't respect Ozone environment variables. This change forces VSCode to run in Wayalnd when using the keybinding rather than xwayland.
This will also resolve issues with blurriness when scaling vscode, such as when using hidpi monitors.

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
Thanks @hchasens! Can you confirm if the flags ``` --ozone-platform-hint=wayland ``` is effective? 

In my end here's an SS 
image
Vscode warns that they do not know the flags passed. 
Looks the same
image


To fix some blur issues if an app is running on xwayland is this: 

```
env = GDK_SCALE,1
xwayland {
    force_zero_scaling = true
    }
```
but this will make all xwayland apps small for hidpi monitors.

force_zero_scaling enabled:
image

**Comment by hchasens** [comment]
There are some unusual quirks with it. First is that all instances of the application must be closed for the change in electron to take effect. For example, if you have an instance of VSCode open without the arguments, then launch it with the argument, it'll continue on X11. All instances need to be closed for it to take effect. I suspect this is because it uses the already launched electron instance if it's already running rather than spawning another instance. 

The warning that it's not an known option is a [known one](https://github.com/NixOS/nixpkgs/issues/271461) and has to do with it not being a default option. It is working however. 

Below are two screenshots. One without the argument and one with it. If you open the images and zoom in you can clearly see the version with the wayland arguments is much crisper. 

### Default X11
codeXwayland

### Wayland
codeWayland

**Comment by kRHYME7** [comment]
Thanks for confirming this.  Dunno yet why it still looks the same on my end.

**Comment by hchasens** [comment]
I'm assuming the framed window on your right is an invisible VSCode? I'm not sure what could be causing that. It does look like you're using a different set of arguments than those in the PR though. Try using `code --ozone-platform-hint=wayland --disable-gpu`. The `-disable-gpu` was already in the config to start with as rendering electron applications with wlroots can have issues on some GPUs (that's my understanding anyway). Since the compositor doesn't look to be compositing that might be your issue.

**Comment by kRHYME7** [comment]
Thanks again!

**Comment by hchasens** [comment]
No problem! Happy to help. Did that fix work for you?

**Comment by kRHYME7** [comment]
Yes!  ``` code --ozone-platform-hint=wayland --disable-gpu  ``` is the right combo for my system.

**Review by prasanthrangan — APPROVED** [review]
great, thank you! I think the code launch option is also set in zshrc as well, I'll update it.

**Pull request merged**
