### PR TITLE
feat: common operations float windowrules

### PR DESCRIPTION
**Pull request by rubiin**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
Works with? Details please. 
eg. all desktop portal

**Comment by rubiin** [comment]
> Works with? Details please. eg. all desktop portal

works with some applications windows with given title.
For example, jetbrains Ides, browsers

**Comment by zeerayne** [comment]
I want to suggest add rule for `xdg-desktop-portal-gtk`. It is also related to open file dialog in some apps which use it.
```
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$
```

My full config for it is:
```
windowrulev2 = float,        class:^(xdg-desktop-portal-gtk)$
windowrulev2 = center (1),   class:^(xdg-desktop-portal-gtk)$
windowrulev2 = size 50% 90%, class:^(xdg-desktop-portal-gtk)$
```
Because w/o centring and size definition window overflows with waybar on top or bottom

**Comment by rubiin** [comment]
> I want to suggest add rule for `xdg-desktop-portal-gtk`. It is also related to open file dialog in some apps which use it.
> 
> ```
> windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$
> ```
> 
> My full config for it is:
> 
> ```
> windowrulev2 = float,        class:^(xdg-desktop-portal-gtk)$
> windowrulev2 = center (1),   class:^(xdg-desktop-portal-gtk)$
> windowrulev2 = size 50% 90%, class:^(xdg-desktop-portal-gtk)$
> ```
> 
> Because w/o centring and size definition window overflows with waybar on top or bottom

added for xdg . Omitted the centering and dimensions for now

**Comment by AbrarAbe** [comment]
i combined it with dimaround to prevent overlapping
My config :
`# F L O A T I N G
windowrulev2 = float,class:^(nemo)$,title:^(.*Properties.*)$
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(floorp)$,title:^(.*Sign.*)$
#windowrulev2 = float,class:^(code-oss)$
windowrulev2 = float,class:(wayfarer)$
windowrulev2 = float,class:(smile)$
windowrulev2 = float,class:^(mpv)$
windowrulev2 = float,class:(weylus)$
windowrulev2 = float,class:(swayimg)$
windowrulev2 = float,class:^(org.gnome.FileRoller)$
windowrulev2 = float,class:^(zenity)$
windowrulev2 = float,class:^(blender)$,title:^(Blender Preferences)$
windowrulev2 = float,class:^(com.github.unrud.VideoDownloader)$ # VideoDownloader-Gtk
windowrulev2 = float,class:^(Electron)$,title:^(.*Open.*)$
windowrulev2 = float,class:^(Electron)$,title:^(.*Select.*)$
windowrulev2 = float,class:^(Electron)$,title:^(.*Save.*)$
windowrulev2 = float,class:^(Electron)$,title:^(.*Add.*)$
windowrulev2 = float,class:^(Electron)$,title:^(.*Install.*)$
windowrulev2 = float,class:^(lutris)$,title:^(.*Log.*)$
windowrulev2 = float,class:^(Genymotion Player)$,title:^(.*Google Pixel.*)$
windowrulev2 = float,class:^(hyprland-share-picker)$,title:^(MainPicker)$
windowrulev2 = float,class:^(steam)$,title:^(.*List.*)$
windowrulev2 = float,class:^(Cemu)$,title:^(.*Edit.*)$
windowrulev2 = float,class:^(.*silo.*)$,title:^(Download)$
windowrulev2 = float,class:^(com.github.Aylur.ags)$,title:^(Settings)$
windowrulev2 = float,class:^(com.github.Aylur.ags)$,title:^(.*Save.*)$
windowrulev2 = float,class:^(com.github.Aylur.ags)$,title:^(.*Import.*)$

# C U S T O M  S I Z E
#windowrulev2 = size 948 558,class:^(code-oss)$
windowrulev2 = size 759 490,class:^(Electron)$,title:^(.*Open.*)$
windowrulev2 = size 759 490,class:^(Electron)$,title:^(.*Select.*)$
windowrulev2 = size 759 490,class:^(Electron)$,title:^(.*Save.*)$
windowrulev2 = size 759 490,class:^(Electron)$,title:^(.*Add.*)$
windowrulev2 = size 759 490,class:^(Electron)$,title:^(.*Install.*)$
windowrulev2 = size 759 490,class:^(floorp)$,title:^(.*Enter.*)$
windowrulev2 = size 759 490,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 381 738,class:^(Genymotion Player)$,title:^(.*Google Pixel.*)$
windowrulev2 = keepaspectratio,class:^(Genymotion Player)$,title:^(.*Google Pixel.*)$
windowrulev2 = size 463 560,class:^(steam)$,title:^(.*List.*)$
windowrulev2 = size 877 490,class:^(org.gnome.FileRoller)$
windowrulev2 = size 877 490,class:^(file-roller)$
windowrulev2 = size 947 534,class:^(mpv)$
windowrulev2 = size 947 534,class:^(vlc)$
windowrulev2 = size 762 613,class:^(nemo)$,title:^(.*Properties.*)$
windowrulev2 = size 525 414,class:^(Cemu)$,title:^(.*Edit.*)$
windowrulev2 = size 857 595,class:^(zenity)$
windowrulev2 = size 413 92,class:^(.*silo.*)$,title:^(Download)$
windowrulev2 = size 726 468,class:^(com.github.Aylur.ags)$,title:^(.*Save.*)$
windowrulev2 = size 1000 696,class:^(com.github.Aylur.ags)$,title:^(Settings)$
windowrulev2 = size 726 468,class:^(com.github.Aylur.ags)$,title:^(.*Import.*)$

# C E N T E R  F L O A T I N G  W I N D O W
windowrulev2 = center 1,class:^(Electron)$,title:^(.*Open.*)$
windowrulev2 = center 1,class:^(Electron)$,title:^(.*Select.*)$
windowrulev2 = center 1,class:^(Electron)$,title:^(.*Save.*)$
windowrulev2 = center 1,class:^(Electron)$,title:^(.*Add.*)$
windowrulev2 = center 1,class:^(Electron)$,title:^(.*Install.*)$
windowrulev2 = center 1,class:^(floorp)$,title:^(.*Enter.*)$
windowrulev2 = center 1,class:^(lutris)$,title:^(.*Configure.*)$
windowrulev2 = center 1,class:^(lutris)$,title:^(.*Add.*)$
windowrulev2 = center 1,class:^(nemo)$,title:^(.*Properties.*)$
windowrulev2 = center 1.class:^(file-roller)$
windowrulev2 = center 1,class:^(qt5ct)$
windowrulev2 = center 1,class:^(qt6ct)$
windowrulev2 = center 1,class:^(nwg-look)$
windowrulev2 = center 1,class:^(vlc)$
windowrulev2 = center 1,class:^(zenity)$

# D I M
windowrulev2 = dimaround,class:^(Electron)$,title:^(.*Open.*)$
windowrulev2 = dimaround,class:^(Electron)$,title:^(.*Select.*)$
windowrulev2 = dimaround,class:^(Electron)$,title:^(.*Save.*)$
windowrulev2 = dimaround,class:^(Electron)$,title:^(.*Add.*)$
windowrulev2 = dimaround,class:^(floorp)$,title:^(.*Sign.*)$
windowrulev2 = dimaround,class:^(floorp)$,title:^(.*Enter.*)$
windowrulev2 = dimaround,class:^(blender)$,title:^(Blender Preferences)$
windowrulev2 = dimaround,class:^(com.github.unrud.VideoDownloader)$ # VideoDownloader-Gtk
windowrulev2 = dimaround,class:(smile)$
windowrulev2 = dimaround,class:^(qt5ct)$
windowrulev2 = dimaround,class:^(qt6ct)$
windowrulev2 = dimaround,class:^(nwg-look)$
windowrulev2 = dimaround,class:^(blueman-manager)$
windowrulev2 = dimaround,class:^(nm-applet)$
windowrulev2 = dimaround,class:^(nm-connection-editor)$
windowrulev2 = dimaround,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = dimaround,class:^(polkit-gnome-authentication-agent-1)$
windowrulev2 = dimaround,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = dimaround,class:^(org.kde.dolphin)$,title:^(Progress Dialog — Dolphin)$
windowrulev2 = dimaround,class:^(org.kde.dolphin)$,title:^(Copying — Dolphin)$
windowrulev2 = dimaround,class:^(lutris)$,title:^(.*Log.*)$
windowrulev2 = dimaround,class:^(lutris)$,title:^(.*Configure.*)$
windowrulev2 = dimaround,class:^(lutris)$,title:^(.*Add.*)$
windowrulev2 = dimaround,class:^(lutris)$,title:^(.*Select.*)$
windowrulev2 = dimaround,class:^(lutris)$,title:^(.*Please.*)$
windowrulev2 = dimaround,class:^(lutris)$,title:^(.*Confirm.*)$
windowrulev2 = dimaround,class:^(hyprland-share-picker)$,title:^(MainPicker)$
windowrulev2 = dimaround,class:^(org.gnome.FileRoller)$
windowrulev2 = dimaround,class:^(file-roller)$
windowrulev2 = dimaround,class:^(swappy)$
windowrulev2 = dimaround,class:^(nemo)$,title:^(.*Properties.*)$
windowrulev2 = dimaround,class:^(com.github.Aylur.ags)$,title:^(.*Save.*)$
windowrulev2 = dimaround,class:^(com.github.Aylur.ags)$,title:^(.*Import.*)$
windowrulev2 = dimaround,class:^(gestures)$,title:^(Preferences)$`

**Review by kRHYME7 — APPROVED** [review]
Great

**Pull request merged**
