### PR TITLE
Hyprland Group Catergory

### PR DESCRIPTION
**Pull request by kRHYME7**
Addressing issues for #311  due to recent Hyprland update

https://wiki.hyprland.org/Configuring/Variables/#group
https://github.com/hyprwm/Hyprland/commit/d537815d43c74a4e9214c4e7480c20047d297307

image

### CODE REVIEW

**Comment by kRHYME7** [comment]
@prasanthrangan  @T-Crypt  Did I miss something?

**Comment by T-Crypt** [comment]
I'm reviewing this now.  I checked this out and making sure we aren't missing anything.

Thank you for the PR! This is helpful for @prasanthrangan to focus on development rather than maintenance.

**Review by T-Crypt — APPROVED** [review]
Aprroved -- Tested -- Verified 

had to update hyprland-nvidia-git since it isn't maintained by Hypr Dev

**Review by prasanthrangan — APPROVED** [review]
They changed the variables again didn't they... We can basically expect the hyprland config to break every 2-3 weeks :)
But thank you so much for fixing this so quickly!!

**Comment by kRHYME7** [comment]
> They changed the variables again didn't they... We can basically expect the hyprland config to break every 2-3 weeks :) But thank you so much for fixing this so quickly!!

This is the reason I followed their discord, :) It always confuses me why I always get errors lol.

**Comment by TheyCallMeSecond** [comment]
231012_03h03m02s_screenshot
im on the last version of hyprland-git

**Pull request merged**
