### PR TITLE
swwwallpaper.sh draft - PR -- Dominant Color selection

### PR DESCRIPTION
**Pull request by T-Crypt**
Drafted this up as I thought this might be helpful for your current in-progress work in "Projects"

### CODE REVIEW

**Comment by T-Crypt** [comment]
Part I'm struggling with is the wlogout config / styles -- incorporating the dominant color from the config file -- needs some work.

**Comment by T-Crypt** [comment]
also need to add a function for the variable $dominant_color

**Comment by T-Crypt** [comment]
1. Need to replace "use_style1" and "use_style2" with an actual condition logic for selecting the wlogout style based on set requirements.

2. Functions are defined at the beginning of the script for better organization and readability.

**Comment by prasanthrangan** [comment]
> Drafted this up as I thought this might be helpful for your current in-progress work in "Projects"

Yup i updated swwwallpaper to export wall dominant color...

The idea was to create template configs for rofi and waybar (wlogout use the same config as waybar)
Then a new script to convert the colors from extracted `wall.dcol` to apply it on the templates to generate corresponding `dcol.conf`

**Comment by prasanthrangan** [comment]
> * Need to replace "use_style1" and "use_style2" with an actual condition logic for selecting the wlogout style based on set requirements.
> 
> * Functions are defined at the beginning of the script for better organization and readability.
> 
> * Still a work in progress but feel free to steal any of this for the project before the merge -- Not sure if we will decide to merge via this draft PR

I didn't get a chance to work on this, but better to keep the converter script (`wallbash.sh`) separate from `swwwallaper.sh` so that current theming system works as is, and it only creates and additional dcol.conf based on wall color. so users have options to use theme based or wall based!

**Comment by T-Crypt** [comment]
Im in agreeance there!! I was about to disregard this PR now that I was able to get your input on how you wanted this done!! Is there anything you wanted me to help work on or assist?

**Comment by prasanthrangan** [comment]
just got the waybar colors working, so i'll try to commit it in a new branch, so if you have some time to test, feel free to test it!

https://github.com/prasanthrangan/hyprdots/assets/106020512/19ab76ef-658b-47ef-a5c3-24c4e9262289

**Comment by T-Crypt** [comment]
dude this is mint. Ill definitely test this out -- Ill look for the branch now!

**Comment by prasanthrangan** [comment]
I've created `wallbash` branch, and everything (rofi/waybar/wlogout) seems to work now!
Main issue is that, for wallpapers with low contrast the text is not very readable :(

**Pull request closed without merging**
