### PR TITLE
Add Animation Selector using rofi menu

### PR DESCRIPTION
**Pull request by rishav12s**
# Pull Request

## Description

- Animation Selector using rofi menu
- hypr.conf sources the animations.conf which in turn sources the animation to be used from animations directory
- disabled animation on hyprpicker and selection (used for screenshot etc) as it has a wierd bouncy effect

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots
image

### CODE REVIEW

**Comment by kRHYME7** [comment]
Can I steal this one? Gotta add this to the main. Or maybe do a PR please 🥺

**Comment by rishav12s** [comment]
@kRHYME7 merge conflict resolved also updated according to the special workspace animation pr

**Comment by kRHYME7** [comment]
@rishav12s  Sorry man I don't know if I will this feature here.

**Comment by rishav12s** [comment]
> @rishav12s Sorry man I don't know if I will this feature here.

sad dont think its breaking anything atleast maybe we can do a poll or take opinion from other contributors ?

**Comment by kRHYME7** [comment]
yup, it's not breaking but it's another thing to be maintained.

Maybe 5 approves? is that too much?

**Comment by rishav12s** [comment]
> yup, it's not breaking but it's another thing to be maintained.
> 
> Maybe 5 approves? is that too much?

lol tag the ones that are most active here ig

**Review by kRHYME7 — APPROVED** [review]

**Review by mahaveergurjar — APPROVED** [review]

**Review by rubiin — APPROVED** [review]
Much awaited feat

**Comment by zeerayne** [comment]
My only thought is hotkey - all other "visual" hotkeys are binded to `$mainMod+Shift+key` (like rofi style/theme/wallpeper). Maybe this would also be easier to remember if it will follow same logic?

**Comment by rishav12s** [comment]
> My only thought is hotkey - all other "visual" hotkeys are binded to `$mainMod+Shift+key` (like rofi style/theme/wallpeper). Maybe this would also be easier to remember if it will follow same logic?

A=Animation

`$mainMod+A` and `$mainMod+Shift+A` is already occupied what else do you have in mind

**Review by zeerayne — APPROVED** [review]

**Review by cyb3rgh0u1 — APPROVED** [review]

**Review by abenezerw — APPROVED** [review]
All good here.

**Comment by kRHYME7** [comment]
Hi guys, from now on I'll just mention anyone that is recently active to decide whether a PR can be merged.  I am very hopeful that you won't abandon these new features,as I've already stated that I can't immediately fix anything that might break, upstream or downstream. So any fixes should be coming from you all who approved the PRs. I hope we're cool with that.  At least 5 approvals for a MR to be merged. I hope you'll understand my situation. 🙏💓

**Comment by rishav12s** [comment]
@kRHYME7 @rubiin @abenezerw @zeerayne @cyb3rgh0u1 @mahaveergurjar 

thanks everyone for the approval and merge 

love you guys 🙏❤️❤️

**Comment by kRHYME7** [comment]
BTW @rishav12s  can I copy some animation stuff from here? or you'll make a PR in HyDE 🥺

**Comment by kRHYME7** [comment]
BTW it will give errors to  anyone who will update or  fresh installation. Add the animations directory to ./Scripts/restore_cfg.lst

**Pull request merged**
