### PR TITLE
[OFF STUFFS] pywal and monitor CONNECT notify

### PR DESCRIPTION
**Pull request by nx-smul**
made 2 scripts one is pywal with telegram themeing using wal-telegram another one is monitor connect notification for multi monitor connect  using 
https://github.com/coffebar/hyprland-monitor-attached this package 
[NOTE] ./cache/swww/eDP1 this file is not same for everyone so kindy find a way to make it change automaticly
i'm a ultra noob at bash I hope you can find a way to marge pywall with wall bash  and both scripts works
image

### CODE REVIEW

**Comment by nx-smul** [comment]
al rit no worries

**Comment by kRHYME7** [comment]
Hello @nx-smul  there is a neat way to detect hyprland events, check [this](https://github.com/hyprwm/contrib#shellevents) out. So we can bundle all event-handling in 1  or 2 script .

**Comment by prasanthrangan** [comment]
> made 2 scripts one is pywal with telegram themeing using wal-telegram another one is monitor connect notification for multi monitor connect using

Hi, Thanks for your contribution!
looks like these scripts need more dependencies to run.

if you are trying to generate telegram theme from wallpaper, you can just create a template file as `~/.config/hypr/wallbash/telegram.dcol` and use the use these variables already generated by `wallbash` -

```
<dcol_0>
<dcol_1>
<dcol_2>
<dcol_3>
```

I'm not sure how the config/theme file for telegram looks like, but if could share it, i can help to create its template!

**Comment by nx-smul** [comment]
alrit imma try this one

**Pull request closed without merging**
