### PR TITLE
Upgraded spotify widget in waybar

### PR DESCRIPTION
**Pull request by joshrandall8478**
> *Hi! I've been enjoying using this project/rice for personal and school work with Arch, and want to share the small changes and improvements I made to the Spotify widget on waybar. Thank you for creating and maintaining hyprdots!*

- `dunst`
- `playerctl`

### Changes
- Scrolling on the widget now changes the volume of Spotify itself using the `spotifyvolume.sh` script, which gives feedback notifications using `dunst`.
- Right click to skip track, middle click to go to previous track.
- Maximum length of widget imposed as to not affect the other widgets.
- Order of icons changed on `spotify.json` module.

<hr>

image

### CODE REVIEW

**Comment by T-Crypt** [comment]
@joshrandall8478 Thank you for the PR! 

1. Looks like you added an additional waybar configuration to the config.ctl which should retain the original value of 7 lines.
2. There is already a spotifyvolumecontrol.sh file in `~/.config/hypr/scripts/spotifyvolumecontrol.sh` so we would want to add that to the original spotify.jsonc file instead of adding 2 files for the same function!

Good PR, but this would probably remain a user preference for the config.ctl changes as we would like to keep it uniform and Tittu as already created the styles and provided a customization wiki on making your own changes to waybar! Here is the link to the theming wiki! [Waybar Style](https://github.com/prasanthrangan/hyprdots/wiki/Theming#waybar)

**Comment by joshrandall8478** [comment]
Understood, I also just found that script in hypr/scripts. If I modify that script to show notifications, and reinstate the original waybar `config.ctl`, would that be of help to the project?

**Comment by T-Crypt** [comment]
It could be! 

There is technically already a volume control option with the pulseaudio module! 

So it would just add functionality to the spotify module to lower the spotify volume but allow the system volume to remain the same so I say go for it.

```
"pulseaudio": {
        "format": "{icon} {volume}",
        "format-muted": "婢",
        "on-click": "pavucontrol -t 3",
        "on-click-middle": "~/.config/hypr/scripts/volumecontrol.sh -o m",
        "on-scroll-up": "~/.config/hypr/scripts/volumecontrol.sh -o i",
        "on-scroll-down": "~/.config/hypr/scripts/volumecontrol.sh -o d",
        "tooltip-format": "{icon} {desc} // {volume}%",
        "scroll-step": 5,
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
```

**Comment by joshrandall8478** [comment]
That is the plan :) i’ll come back with another PR shortly

**Comment by joshrandall8478** [comment]
The branch has now been modified, appears I do not have to make a new PR to reflect my edits.

### Issues corrected:
- Modified `spotifyvolumecontrol.sh`
- Deleted `spotifyvolume.sh`
- Modified `spotify.jsonc` to use `spotifyvolumecontrol.sh`.
- `config.ctl` is reverted back to main repository's default.

Feel free to look at all the changes yourself! Thank you for your consideration :)

**Review by prasanthrangan — APPROVED** [review]
Cool, thank you for the fix!

**Comment by joshrandall8478** [comment]
Conflicts have been resolved, also merged `"escape":true` into spotify.jsonc
```json
    "custom/spotify": {
        "exec": "/usr/bin/python3 $HOME/.config/waybar/modules/mediaplayer.py --player spotify",
        "format": " {}",
        "return-type": "json",
        "on-click": "playerctl play-pause --player spotify",
	"on-click-right": "playerctl next --player spotify",
	"on-click-middle": "playerctl previous --player spotify",
	"on-scroll-up": "~/.config/hypr/scripts/spotifyvolumecontrol.sh up",
	"on-scroll-down": "~/.config/hypr/scripts/spotifyvolumecontrol.sh down",
	"max-length": 25,
        "escape": true
    },
```

**Comment by prasanthrangan** [comment]
cool thanks!
i guess it will be better to integrate `spotifyvolumecontrol.sh` with `volumecontrol.sh` itself, but i'll do that later :)

**Pull request merged**
