### PR TITLE
feat: add pin function to screenshot

### PR DESCRIPTION
**Pull request by hdm9527**
# Pull Request

## Description

The screenshot pinning function makes it easy to refer to when writing code. And no need to switch windows.
Need to install `feh` to display pictures.

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

image

### CODE REVIEW

**Comment by kRHYME7** [comment]
@hdm9527  Hello buddy, is it the same with Swappy? which is already on this repo? Also, we can give Swappy a pin dispatcher.  And Feh is not fully compatible with Wayland (My guess)? 


image

**Comment by prasanthrangan** [comment]
> Need to install `feh` to display pictures.

I would suggest using `swappy` as its already installed as dependency for screenshot.
 

> The screenshot pinning function makes it easy to refer to when writing code.

cool idea, but why not directly pin the actual window (using kb shortcut) instead of a screenshot.
screenshot pinning can also be added as a function to the script.

**Comment by hdm9527** [comment]
> > Need to install `feh` to display pictures.
> 
> I would suggest using `swappy` as its already installed as dependency for screenshot.
> 
> > The screenshot pinning function makes it easy to refer to when writing code.
> 
> cool idea, but why not directly pin the actual window (using kb shortcut) instead of a screenshot. screenshot pinning can also be added as a function to the script.

Because feh can achieve borderless effects and image scaling functions similar to Snipaste. Image scaling is now supported https://github.com/prasanthrangan/hyprdots/pull/708/commits/c538936fac4f88af1d1c77f015e7e72e533c31f6. Because my laptop motherboard is broken, I don’t have any screenshots to show.
image

**Comment by hdm9527** [comment]
> @hdm9527 Hello buddy, is it the same with Swappy? which is already on this repo? Also, we can give Swappy a pin dispatcher. And Feh is not fully compatible with Wayland (My guess)?
> 
> image

The test works fine on my laptop. Does the compatibility issue you are talking about refer to the transparent background when zooming? That's normal. Why use `feh`? You can read this comment. https://github.com/prasanthrangan/hyprdots/pull/708#issuecomment-1890587282

**Comment by prasanthrangan** [comment]
Cool, I'll look into this!

**Comment by kRHYME7** [comment]
AHA I see, Tested this now, and this act like how ``` imv ``` works right ? 

imv works the same (borderless and scaling except that it maintains an upper and lower black border by defautl )

**Comment by hdm9527** [comment]
> AHA I see, Tested this now, and this act like how `imv` works right ?
> 
> imv works the same (borderless and scaling except that it maintains an upper and lower black border by defautl )

I tried imv, and the effect is almost the same. The places where imv's scaling doesn't work are filled with black, and feh is a transparent layer similar to Photoshop. My solution is to fill in the missing areas when the image is scaled. It seems that hyprland cannot implement the function of scaling the window length and width at the same ratio.
>imv and feh
image
>feh fill mode and not fill mode
image

**Comment by kRHYME7** [comment]
Disclaimer: I hope my opinions can be considered as a healthy conversation of something. So, I will try to persuade you to use imv haha. 😄 

Here's how to have the same effect as feh  ``` grimblast save output - | imv  -s crop  - ``` 

I preferred IMV, actually. It's quiet smoother on my system, but I can't say for all.  
Also base on some asked questions in this repo (relating to image viewer ) most of the time they/we  recommended using ``` imv ```.  
imv supports gif and more.
imv is not blured due to being in wayland 
imv ++


image

**Comment by hdm9527** [comment]
> Disclaimer: I hope my opinions can be considered as a healthy conversation of something. So, I will try to persuade you to use imv haha. 😄
> 
> Here's how to have the same effect as feh `grimblast save output - | imv -s crop -`
> 
> I preferred IMV, actually. It's quiet smoother on my system, but I can't say for all. Also base on some asked questions in this repo (relating to image viewer ) most of the time they/we recommended using `imv`. imv supports gif and more. imv is not blured due to being in wayland imv ++
> 
> image



> Disclaimer: I hope my opinions can be considered as a healthy conversation of something. So, I will try to persuade you to use imv haha. 😄
> 
> Here's how to have the same effect as feh `grimblast save output - | imv -s crop -`
> 
> I preferred IMV, actually. It's quiet smoother on my system, but I can't say for all. Also base on some asked questions in this repo (relating to image viewer ) most of the time they/we recommended using `imv`. imv supports gif and more. imv is not blured due to being in wayland imv ++
> 
> image

I added floats to both feh and imv. The display of feh is the actual size of the screenshot. The window of imv will not be displayed according to the actual size of the picture. It covers most of the screen and needs to be reduced manually. If this problem can be solved, there is no problem using imv.
image
image

**Comment by kRHYME7** [comment]
I think the desired flags is ``` crop ``` not ``` none ```

image

**Comment by hdm9527** [comment]
> I think the desired flags is `crop` not `none`
> 
> image

Aera screenshots will enlarge the picture by default, causing it to become blurry. My monitor zoom is 2x.
```bash
grimblast save area - | imv -s crop -
```
image

**Comment by kRHYME7** [comment]
yeah, you're right. I guess I can't convince you to use imv. 😄

**Comment by hdm9527** [comment]
> yeah, you're right. I guess I can't convince you to use imv. 😄

The main reason is that imv has been archived, and some functions cannot meet my needs. I only use feh to display screenshots for reference when writing code. I only learned about the imv software yesterday, and it’s pretty good for browsing pictures.

**Comment by kRHYME7** [comment]
yup yup, definitely different tooling.

**Pull request closed without merging**
