### PR TITLE
update themepatcher.lst for the upcoming hyprland 0.45.0

### PR DESCRIPTION
**Pull request by rishav12s**
# Pull Request

## Description
Makes themepatcher grab themes from the forked repo of the official themes by @kRHYME7 so that we can fix the breaking changes related to shadow syntax in the upcoming hyprland version 0.45.0

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [x] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

**OLD :** 
383896255-9233d204-15d0-40c0-bef2-b94fe1c0a47d

**NEW :**
383901145-7fba4c67-f115-40b5-849b-2d777b0b0eab

### CODE REVIEW

**Comment by kRHYME7** [comment]
This is necessary because hyprland "sometimes" crach if it can't handle too many errors on sourced files.

**Comment by rishav12s** [comment]
> Looks good. BTW why have we forked the themes. Is the older one not going to receive updates?

prasanth is inactive now and no one can merge prs on his theme repo so forking and updating them is only way

**Comment by rubiin** [comment]
> > Looks good. BTW why have we forked the themes. Is the older one not going to receive updates?
> 
> prasanth is inactive now and no one can merge prs on his theme repo so forking and updating them is only way

That is true. I haven't seen any activity in a while

**Comment by kRHYME7** [comment]
My mirror is kinda late but https://archlinux.org/packages/?name=hyprland is v0.45.0. so should be fine

**Review by kRHYME7 — APPROVED** [review]
@rishav12s  Thanks again. Also for the fixes please don't hesistate to open a PR. thank you!

**Pull request merged**
