### PR TITLE
replace convert with magick

### PR DESCRIPTION
**Pull request by zadjadr**
# Pull Request

## Description

`convert` is outdated and is replaced with the current and correct usage of `magick`

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [X] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
Have you tested this on new wallpaper? Can you send SS?

**Comment by zadjadr** [comment]
Yes here are some screenshots:

240724_17h32m20s_screenshot
240724_17h31m43s_screenshot
240724_17h30m05s_screenshot

Only issue I see during cache recreation was this but don't know if it is directly related:

```
magick: no images found for operation `-strip' at CLI arg 1 @ error/operation.c/CLIOption/5479.
```

**Comment by kRHYME7** [comment]
I see the error said  -strip arg is not available. What can be the new arg that is the same with -strip

**Comment by zadjadr** [comment]
> I see the error said -strip arg is not available. What can be the new arg that is the same with -strip

Sorry for the late reply. The problem was that magick expects the image to be an argument before the additional parameters - so just moving the parameter to the correct place fixed it.

**Review by kRHYME7 — APPROVED** [review]
Thank you, Works perfectly!

**Pull request merged**
