### PR TITLE
Discord Wallbash

### PR DESCRIPTION
**Pull request by kRHYME7**
Vesktop.dcol

### TODO
- [ ] Need to adjust colors
- [x] ~Sometimes the themes won't change dynamically, should we force a relaunch?~ No
- [x] Should we add flatpak support? 

- [x] vencord
- [x] vencord flatpak
- [x] webcord
- [x] webcord flatpak 

image

image
image
image

#931 
@Enigma1309 
@RookiexCookie
@akashgagda

### CODE REVIEW

**Comment by akashgagda** [comment]
Thank you bro I will try this

**Comment by Enigma1309** [comment]
Checked just now 🔥 , i use webcord instead, so after changing 
` $HOME/.config/vesktop/settings/quickCss.css`
to 
`$HOME/.config/WebCord/Themes/theme.css`

Webcord is updating the colors according to the wallpaper, i hope it's the case with vencord too.

> Sometimes the themes won't change dynamically, should we force a relaunch?

nope don't try to do it, it will kill the ongoing call and will ruin the overall experience.

> Should we add flatpak support?

it's kinda subjective, most people don't use flatpak for discord due to screen-sharing issue on wayland, i think we shouldn't 



Also colors are looking good, except in few cases where the text isn't visible
example(with one of the default wallpaper) :-
image


Rest all is working pretty well, Just waiting for a script so that it follows wallbash on/off rules

**Comment by kRHYME7** [comment]
Ended up adding for vencord and webcord (with flatpak variants)

image

**Comment by RookiexCookie** [comment]
Hell ya thats what im talking about

**Comment by RookiexCookie** [comment]
Oh btw yea they sometimes didnt change dynamically for me aswell cuz i was doing the @import xyz.css;  at the top
i made a temp script that just write the whole main Theme.css file and that worked
dont know why the import thing dont work

**Comment by RookiexCookie** [comment]
image

**Comment by kRHYME7** [comment]
Webcord works slightly differently. When the theme.css is touched  they have a function to re-generate the theme.

While Vesktop doesn't do that, they have the feature called quickCss which automatically adapts the colors on the fly.

**Comment by RookiexCookie** [comment]
okay imma try this now
and try to tinker with colors conf
Thanks bruv

**Comment by RookiexCookie** [comment]
how are these color

image
image
image

**Comment by kRHYME7** [comment]
Can you send at least this part (in text) 
image

**Comment by akashgagda** [comment]
i install vesktop flatpak version then i run script but colors not change
image

**Comment by Enigma1309** [comment]
you have to enable wallbash too for this to work

**Comment by akashgagda** [comment]
> you have to enable wallbash too for this to work

aah thank you bro now its working

**Review by prasanthrangan — APPROVED** [review]
great thank you, i don't have discord installed, but will merge this anyways!

**Pull request merged**
