### PR TITLE
FEAT:? Charging Notification

### PR DESCRIPTION
**Pull request by kRHYME7**
* Laptop use only
* Responsive Battery/Charging Notifier
* Reads Dbus-monitor output to tickle the script. 
( The script waits for  changes like the charger plugged in/out or the battery percentage change )
* Prompts/ Notify every 1% if the threshold is reached. 
* Intrusive Notification for Battery's Safety 
*  Suspends the device  after 5minutes of critical threshold 
* Edit vars here: 
 ```  
# User Variables
battery_critical_threshold=10     #? Set  Battery  Critical threshold to suspend
battery_low_threshold=20    #? Set Battery Low threshold
unplug_charger_threshold=80   #? Set Max Battery threshold Warning
countdown=300      #? Countdown timer if critical level reached; if set to less than 60 defaults to 60 seconds
action="suspend" #? Will be appended to systemctl $action
```

image

image

image
image

image
image
image
image
image

Etc.   

Have tried this on two laptops and it works as intended. 

I hope someone can check this out so we can fix errors.

Dependency:
+upower    (Almost all arch distro have this, I think)

### CODE REVIEW

**Comment by prasanthrangan** [comment]
Hi @kRHYME7 , is this still in progress or ready to merge?
I don't have a laptop so I cant test this...

**Comment by kRHYME7** [comment]
Tested this on my two lappys.  I think this is ready but to be confident, we need someone to test this?

**Comment by kRHYME7** [comment]
Also should we need to add  ``` upower ```  to the apps needed  to be installed ?

**Comment by prasanthrangan** [comment]
> Also should we need to add `upower` to the apps needed to be installed ?
> And should I add it on ./custom_hypr.lst

its not required, as `upower` is already being installed as dependency...

**Review by prasanthrangan — APPROVED** [review]
I'll merge it anyways... hope it works :)

**Comment by kRHYME7** [comment]
Thanks I'll actively monitor for regressions regarding this.

**Pull request merged**
