### PR TITLE
hyprcursor: add Bibata Modern Ice hyprcursor theme

### PR DESCRIPTION
**Pull request by hdm9527**
# Pull Request

## Description

Made Bibata Modern Ice hyprcursor theme. Use svg instead of png, cursor is clearer.

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by kRHYME7** [comment]
Nice! I'm actually trying to do it.  cool!

**Comment by hdm9527** [comment]
> Nice! I'm actually trying to do it. Cool! Do you need help setting this up?

My cursor config
```
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
```

**Comment by kRHYME7** [comment]
I'm a little bit confused as why

**Comment by kRHYME7** [comment]
image


Opsie so this tarball is the functional one. lol

**Comment by hdm9527** [comment]
> > use hyprctl setcursor Bibata-Modern-Ice 24 command to take effect immediately, if it does not take effect, please logout or reboot
> 
> I'm a little bit confused as why `hyprctl setcursor Bibata-Modern-Ice 24` is not working. I can make it work using the ENV. Is this same on your system? But using env is not dynamic

Maybe this is the reason, it has been executing https://github.com/prasanthrangan/hyprdots/blob/29b199ab210772055685642e6b57cdd3cb78929b/Configs/.config/hypr/themes/common.conf#L5

**Review by rubiin — APPROVED** [review]

**Review by kRHYME7 — APPROVED** [review]
Cool

**Comment by kRHYME7** [comment]
Sorry forgot to press merge. Thanks !

**Pull request merged**
